//! Test utilities for HEVC decoder validation against golden reference data.
//!
//! Loads fixtures generated by tests/fixtures/hevc/generate.sh and provides
//! comparison helpers for per-stage validation.

use std::path::{Path, PathBuf};

/// Base directory for HEVC generated fixtures.
fn fixtures_dir() -> PathBuf {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap_or_else(|_| ".".into());
    PathBuf::from(manifest)
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("tests/fixtures/hevc/generated")
}

/// Check if HEVC fixtures have been generated.
pub fn fixtures_available() -> bool {
    let dir = fixtures_dir();
    dir.exists() && dir.join(".manifest_hash").exists()
}

/// Load a fixture file by test case name and suffix.
///
/// Example: `load_fixture("flat_64x64_q22", "hevc")` loads the Annex B bitstream.
pub fn load_fixture(case: &str, suffix: &str) -> Option<Vec<u8>> {
    let path = fixtures_dir().join(format!("{case}.{suffix}"));
    std::fs::read(&path).ok()
}

/// Load the decoded RGB reference for a test case.
pub fn load_reference_rgb(case: &str) -> Option<Vec<u8>> {
    load_fixture(&format!("{case}_decoded"), "rgb")
}

/// Load the decoded YUV reference for a test case.
pub fn load_reference_yuv(case: &str) -> Option<Vec<u8>> {
    load_fixture(&format!("{case}_decoded"), "yuv")
}

/// Load the stream info JSON for a test case.
pub fn load_info_json(case: &str) -> Option<String> {
    let data = load_fixture(&format!("{case}_info"), "json")?;
    String::from_utf8(data).ok()
}

/// Compare two pixel buffers with a per-pixel tolerance.
///
/// Returns the number of pixels that exceed the tolerance, along with the
/// maximum absolute difference found.
pub fn compare_pixels(actual: &[u8], expected: &[u8], tolerance: u8) -> PixelComparison {
    assert_eq!(
        actual.len(),
        expected.len(),
        "pixel buffer size mismatch: {} vs {}",
        actual.len(),
        expected.len()
    );

    let mut max_diff = 0u8;
    let mut mismatches = 0usize;
    let mut sum_sq_diff = 0.0f64;

    for (i, (&a, &e)) in actual.iter().zip(expected.iter()).enumerate() {
        let diff = (a as i16 - e as i16).unsigned_abs() as u8;
        if diff > tolerance {
            mismatches += 1;
        }
        if diff > max_diff {
            max_diff = diff;
        }
        sum_sq_diff += (diff as f64) * (diff as f64);
        let _ = i; // suppress unused
    }

    let mse = sum_sq_diff / actual.len() as f64;
    let psnr = if mse > 0.0 {
        10.0 * (255.0f64 * 255.0 / mse).log10()
    } else {
        f64::INFINITY
    };

    PixelComparison {
        total_pixels: actual.len(),
        mismatches,
        max_diff,
        psnr,
    }
}

/// Result of comparing two pixel buffers.
#[derive(Debug)]
pub struct PixelComparison {
    pub total_pixels: usize,
    pub mismatches: usize,
    pub max_diff: u8,
    pub psnr: f64,
}

impl PixelComparison {
    /// Whether the comparison is pixel-exact.
    pub fn is_exact(&self) -> bool {
        self.max_diff == 0
    }

    /// Whether the comparison passes the given PSNR threshold.
    pub fn passes_psnr(&self, min_psnr: f64) -> bool {
        self.psnr >= min_psnr
    }
}

/// Macro to skip a test if HEVC fixtures are not available.
#[macro_export]
macro_rules! skip_if_no_fixtures {
    () => {
        if !$crate::testutil::fixtures_available() {
            eprintln!("SKIPPED: HEVC fixtures not generated. Run: tests/fixtures/hevc/generate.sh");
            return;
        }
    };
}

/// Available test cases (name without extension).
pub const TEST_CASES: &[(&str, u32, u32)] = &[
    ("flat_64x64_q22", 64, 64),
    ("flat_64x64_q37", 64, 64),
    ("gradient_128x128_q22", 128, 128),
    ("gradient_128x128_q37", 128, 128),
    ("checker_256x256_q22", 256, 256),
    ("checker_256x256_q37", 256, 256),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn compare_exact_match() {
        let a = vec![100u8; 64];
        let b = vec![100u8; 64];
        let cmp = compare_pixels(&a, &b, 0);
        assert!(cmp.is_exact());
        assert_eq!(cmp.mismatches, 0);
        assert_eq!(cmp.psnr, f64::INFINITY);
    }

    #[test]
    fn compare_with_tolerance() {
        let a = vec![100u8; 64];
        let mut b = vec![100u8; 64];
        b[0] = 102; // diff = 2
        b[1] = 98; // diff = 2

        let cmp = compare_pixels(&a, &b, 2);
        assert_eq!(cmp.mismatches, 0); // within tolerance
        assert_eq!(cmp.max_diff, 2);

        let cmp2 = compare_pixels(&a, &b, 1);
        assert_eq!(cmp2.mismatches, 2); // exceeds tolerance
    }

    #[test]
    fn compare_psnr() {
        let a = vec![100u8; 1000];
        let mut b = vec![100u8; 1000];
        b[0] = 110; // single pixel diff of 10
        let cmp = compare_pixels(&a, &b, 0);
        assert!(cmp.psnr > 40.0); // Should be very high PSNR
        assert!(cmp.passes_psnr(40.0));
    }

    #[test]
    fn fixtures_dir_exists_or_not() {
        // Just verify the function doesn't panic
        let _ = fixtures_available();
    }

    #[test]
    fn load_fixtures_if_available() {
        if !fixtures_available() {
            return;
        }
        // If fixtures exist, verify we can load them
        let hevc = load_fixture("flat_64x64_q22", "hevc");
        assert!(hevc.is_some(), "should load flat_64x64_q22.hevc");
        let data = hevc.unwrap();
        assert!(data.len() > 100, "bitstream should be non-trivial");

        let rgb = load_reference_rgb("flat_64x64_q22");
        assert!(rgb.is_some(), "should load decoded RGB");
        let rgb_data = rgb.unwrap();
        assert_eq!(rgb_data.len(), 64 * 64 * 3, "RGB should be 64x64x3");
    }

    #[test]
    fn validate_params_against_golden() {
        skip_if_no_fixtures!();

        // Load the bitstream and parse its parameter sets
        let hevc_data = load_fixture("flat_64x64_q22", "hevc").unwrap();

        // Parse NAL units from the Annex B stream
        let nals: Vec<&[u8]> = crate::nal::NalIterator::new(&hevc_data).collect();
        assert!(nals.len() >= 3, "should have VPS+SPS+PPS+slice NALs");

        // Parse each NAL and find SPS
        for nal_data in &nals {
            let nal = crate::nal::parse_nal_unit(nal_data).unwrap();
            if nal.nal_type == crate::types::NalUnitType::SpsNut {
                let sps = crate::params::parse_sps(&nal.rbsp).unwrap();
                assert_eq!(sps.pic_width, 64, "SPS width should be 64");
                assert_eq!(sps.pic_height, 64, "SPS height should be 64");
                assert_eq!(sps.chroma_format_idc, 1, "should be 4:2:0");
                assert_eq!(sps.bit_depth_luma, 8);
                return;
            }
        }
        panic!("SPS NAL not found in bitstream");
    }
}
