#ifndef RCIMG_H
#define RCIMG_H

/* Auto-generated by cbindgen + post-processing — do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Opaque handles — internal layout is private. */
typedef struct rcimg_pipeline rcimg_pipeline;
typedef struct rcimg_layer_cache rcimg_layer_cache;

/* ─── Error reporting ─── */

/**
 * Return a pointer to the last error message (NUL-terminated, UTF-8).
 * The pointer is valid until the next call to any rasmcore_* function
 * on the same thread.
 */
const char *rasmcore_last_error(void);

/* ─── Pipeline lifecycle ─── */

/**
 * Create a new pipeline with `cache_budget_mb` megabytes of spatial cache.
 */
rcimg_pipeline *rasmcore_pipeline_new(uint32_t cache_budget_mb);

/**
 * Free a pipeline handle. Safe to call with NULL.
 */
void rasmcore_pipeline_free(rcimg_pipeline *pipe);

/* ─── Layer cache (cross-pipeline persistence) ─── */

/**
 * Create a shared layer cache with `budget_mb` megabytes.
 */
rcimg_layer_cache *rasmcore_layer_cache_new(uint32_t budget_mb);

/**
 * Free a layer cache handle. Safe to call with NULL.
 */
void rasmcore_layer_cache_free(rcimg_layer_cache *cache);

/**
 * Attach a shared layer cache to a pipeline.
 */
void rasmcore_pipeline_set_cache(rcimg_pipeline *pipe, rcimg_layer_cache *cache);

/* ─── Source reading ─── */

/**
 * Decode an image from an in-memory buffer and return a node id.
 * Returns UINT32_MAX on error — call rasmcore_last_error() for details.
 */
uint32_t rasmcore_read(rcimg_pipeline *pipe, const uint8_t *data, size_t len);

/**
 * Decode an image from a file path and return a node id.
 * Returns UINT32_MAX on error.
 */
uint32_t rasmcore_read_file(rcimg_pipeline *pipe, const char *path);

/* ─── Filter dispatch ─── */

/**
 * Apply a filter/transform to a source node, returning the new node id.
 *
 * `name` is the operation name (e.g. "blur", "brightness", "flip").
 * `params_json` is a JSON object with parameter names and values,
 * e.g. '{"radius": 5}'. Pass NULL or "{}" for defaults.
 *
 * Returns UINT32_MAX on error.
 */
uint32_t rasmcore_filter(rcimg_pipeline *pipe,
                         uint32_t source,
                         const char *name,
                         const char *params_json);

/* ─── Write / encode ─── */

/**
 * Encode the result of `node` into `format` (e.g. "png", "jpeg", "webp").
 *
 * `quality` is 1-100 for lossy formats; pass 0 for default.
 * On success, returns a heap-allocated buffer and writes its length to
 * *out_len. Free the buffer with rasmcore_buffer_free().
 *
 * Returns NULL on error.
 */
uint8_t *rasmcore_write(rcimg_pipeline *pipe,
                        uint32_t node,
                        const char *format,
                        uint32_t quality,
                        size_t *out_len);

/**
 * Encode and write the result of `node` to a file.
 * Format is inferred from the file extension. quality 1-100; 0 = default.
 * Returns 0 on success, -1 on error.
 */
int32_t rasmcore_write_file(rcimg_pipeline *pipe,
                            uint32_t node,
                            const char *path,
                            uint32_t quality);

/**
 * Free a buffer previously returned by rasmcore_write().
 */
void rasmcore_buffer_free(uint8_t *buf, size_t len);

/* ─── GPU executor ─── */

/**
 * Callback type for GPU compute execution.
 *
 * ops_json: JSON array of GPU operation descriptors
 * input/input_len: RGBA8 pixel buffer
 * width, height: image dimensions
 * out_ptr, out_len: write output buffer here (caller frees via rasmcore_buffer_free)
 * user_data: opaque pointer passed through from rasmcore_set_gpu_executor
 *
 * Return 0 on success, -1 on error.
 */
typedef int32_t (*rcimg_gpu_execute_fn)(const char *ops_json,
                                        const uint8_t *input,
                                        size_t input_len,
                                        uint32_t width,
                                        uint32_t height,
                                        uint8_t **out_ptr,
                                        size_t *out_len,
                                        void *user_data);

/**
 * Register a GPU executor callback for hardware-accelerated processing.
 *
 * callback: function called for GPU-capable operations (NULL to disable)
 * user_data: opaque pointer passed to callback
 * max_buffer_bytes: max GPU buffer size (0 = 256MB default)
 */
void rasmcore_set_gpu_executor(rcimg_pipeline *pipe,
                               rcimg_gpu_execute_fn callback,
                               void *user_data,
                               size_t max_buffer_bytes);

/* ─── Info ─── */

/**
 * Return a JSON string describing the image at `node`.
 * The pointer is valid until the next rasmcore_* call on the same thread.
 * Returns NULL on error.
 */
const char *rasmcore_node_info_json(rcimg_pipeline *pipe, uint32_t node);

#ifdef __cplusplus
}  /* extern "C" */
#endif /* __cplusplus */

#endif /* RCIMG_H */
