# Code generated by cmd/generate; DO NOT EDIT.

from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .pipeline import Pipeline


class Chain:
    """Fluent image processing chain. Create via Pipeline.read()."""

    def __init__(self, pipe: 'Pipeline', input_bytes: bytes) -> None:
        self._pipe = pipe
        self._input = input_bytes
        self._ops: list[dict] = []

    def _add(self, name: str, *params: float) -> 'Chain':
        self._ops.append({'name': name, 'params': list(params)})
        return self

    def write_png(self) -> bytes:
        """Encode result as PNG."""
        return self._pipe.process_chain(self._input, self._ops, 'png')

    def write_jpeg(self, quality: int = 85) -> bytes:
        """Encode result as JPEG."""
        return self._pipe.process_chain(self._input, self._ops, 'jpeg', quality)

    def write_webp(self, quality: int = 80) -> bytes:
        """Encode result as WebP."""
        return self._pipe.process_chain(self._input, self._ops, 'webp', quality)

    def write(self, fmt: str, quality: int | None = None) -> bytes:
        """Encode result in the specified format."""
        return self._pipe.process_chain(self._input, self._ops, fmt, quality)

    def auto_orient(self, orientation: float) -> 'Chain':
        """Apply auto_orient."""
        return self._add('auto_orient', orientation)

    def rotate(self, rotation: float) -> 'Chain':
        """Apply rotate."""
        return self._add('rotate', rotation)

    def flip(self, direction: float) -> 'Chain':
        """Apply flip."""
        return self._add('flip', direction)

    def crop(self, x: int, y: int, width: int, height: int) -> 'Chain':
        """Apply crop."""
        return self._add('crop', x, y, width, height)

    def resize(self, width: int, height: int, filter: float) -> 'Chain':
        """Apply resize."""
        return self._add('resize', width, height, filter)

    def icc_to_srgb(self, icc_profile: float) -> 'Chain':
        """Apply icc_to_srgb."""
        return self._add('icc_to_srgb', icc_profile)

    def perspective_correct(self, strength: float) -> 'Chain':
        """Apply perspective_correct."""
        return self._add('perspective_correct', strength)

    def perspective_warp(self, out_width: int, out_height: int) -> 'Chain':
        """Apply perspective_warp."""
        return self._add('perspective_warp', out_width, out_height)

    def equalize(self) -> 'Chain':
        """Apply equalize."""
        return self._add('equalize')

    def dehaze(self, patch_radius: int, omega: float, t_min: float) -> 'Chain':
        """Apply dehaze."""
        return self._add('dehaze', patch_radius, omega, t_min)

    def retinex_msr(self, sigma_small: float, sigma_medium: float, sigma_large: float) -> 'Chain':
        """Apply retinex_msr."""
        return self._add('retinex_msr', sigma_small, sigma_medium, sigma_large)

    def frequency_high(self, sigma: float) -> 'Chain':
        """Apply frequency_high."""
        return self._add('frequency_high', sigma)

    def vignette_powerlaw(self, strength: float, falloff: float, full_width: int, full_height: int, offset_x: int, offset_y: int) -> 'Chain':
        """Apply vignette_powerlaw."""
        return self._add('vignette_powerlaw', strength, falloff, full_width, full_height, offset_x, offset_y)

    def normalize(self) -> 'Chain':
        """Apply normalize."""
        return self._add('normalize')

    def auto_level(self) -> 'Chain':
        """Apply auto_level."""
        return self._add('auto_level')

    def retinex_ssr(self, sigma: float) -> 'Chain':
        """Apply retinex_ssr."""
        return self._add('retinex_ssr', sigma)

    def clahe(self, clip_limit: float, tile_grid: int) -> 'Chain':
        """Apply clahe."""
        return self._add('clahe', clip_limit, tile_grid)

    def clarity(self, amount: float, sigma: float) -> 'Chain':
        """Apply clarity."""
        return self._add('clarity', amount, sigma)

    def pyramid_detail_remap(self, sigma: float, num_levels: int) -> 'Chain':
        """Apply pyramid_detail_remap."""
        return self._add('pyramid_detail_remap', sigma, num_levels)

    def shadow_highlight(self, shadows: float, highlights: float, whitepoint: float, radius: float, compress: float, shadows_ccorrect: float, highlights_ccorrect: float) -> 'Chain':
        """Apply shadow_highlight."""
        return self._add('shadow_highlight', shadows, highlights, whitepoint, radius, compress, shadows_ccorrect, highlights_ccorrect)

    def frequency_low(self, sigma: float) -> 'Chain':
        """Apply frequency_low."""
        return self._add('frequency_low', sigma)

    def dodge(self, exposure: float, range: int) -> 'Chain':
        """Apply dodge."""
        return self._add('dodge', exposure, range)

    def vignette(self, sigma: float, x_inset: int, y_inset: int, full_width: int, full_height: int, tile_offset_x: int, tile_offset_y: int) -> 'Chain':
        """Apply vignette."""
        return self._add('vignette', sigma, x_inset, y_inset, full_width, full_height, tile_offset_x, tile_offset_y)

    def nlm_denoise(self, h: float, patch_size: int, search_size: int) -> 'Chain':
        """Apply nlm_denoise."""
        return self._add('nlm_denoise', h, patch_size, search_size)

    def retinex_msrcr(self, sigma_small: float, sigma_medium: float, sigma_large: float, alpha: float, beta: float) -> 'Chain':
        """Apply retinex_msrcr."""
        return self._add('retinex_msrcr', sigma_small, sigma_medium, sigma_large, alpha, beta)

    def burn(self, exposure: float, range: int) -> 'Chain':
        """Apply burn."""
        return self._add('burn', exposure, range)

    def sigmoidal_contrast(self, strength: float, midpoint: float, sharpen: bool) -> 'Chain':
        """Apply sigmoidal_contrast."""
        return self._add('sigmoidal_contrast', strength, midpoint, sharpen)

    def exposure(self, ev: float, offset: float, gamma_correction: float) -> 'Chain':
        """Apply exposure."""
        return self._add('exposure', ev, offset, gamma_correction)

    def gamma(self, gamma_value: float) -> 'Chain':
        """Apply gamma."""
        return self._add('gamma', gamma_value)

    def contrast(self, amount: float) -> 'Chain':
        """Apply contrast."""
        return self._add('contrast', amount)

    def levels(self, black_point: float, white_point: float, gamma: float) -> 'Chain':
        """Apply levels."""
        return self._add('levels', black_point, white_point, gamma)

    def invert(self) -> 'Chain':
        """Apply invert."""
        return self._add('invert')

    def brightness(self, amount: float) -> 'Chain':
        """Apply brightness."""
        return self._add('brightness', amount)

    def color_balance(self, shadow_cyan_red: float, shadow_magenta_green: float, shadow_yellow_blue: float, midtone_cyan_red: float, midtone_magenta_green: float, midtone_yellow_blue: float, highlight_cyan_red: float, highlight_magenta_green: float, highlight_yellow_blue: float, preserve_luminosity: bool) -> 'Chain':
        """Apply color_balance."""
        return self._add('color_balance', shadow_cyan_red, shadow_magenta_green, shadow_yellow_blue, midtone_cyan_red, midtone_magenta_green, midtone_yellow_blue, highlight_cyan_red, highlight_magenta_green, highlight_yellow_blue, preserve_luminosity)

    def posterize(self, levels: int) -> 'Chain':
        """Apply posterize."""
        return self._add('posterize', levels)

    def curves_green(self, points: float) -> 'Chain':
        """Apply curves_green."""
        return self._add('curves_green', points)

    def lift_gamma_gain(self, lift_r: float, lift_g: float, lift_b: float, gamma_r: float, gamma_g: float, gamma_b: float, gain_r: float, gain_g: float, gain_b: float) -> 'Chain':
        """Apply lift_gamma_gain."""
        return self._add('lift_gamma_gain', lift_r, lift_g, lift_b, gamma_r, gamma_g, gamma_b, gain_r, gain_g, gain_b)

    def curves_red(self, points: float) -> 'Chain':
        """Apply curves_red."""
        return self._add('curves_red', points)

    def apply_hald_lut(self, hald_dim: int) -> 'Chain':
        """Apply apply_hald_lut."""
        return self._add('apply_hald_lut', hald_dim)

    def apply_cube_lut(self, cube_data: float) -> 'Chain':
        """Apply apply_cube_lut."""
        return self._add('apply_cube_lut', cube_data)

    def split_toning(self, highlight_hue: float, shadow_hue: float, balance: float) -> 'Chain':
        """Apply split_toning."""
        return self._add('split_toning', highlight_hue, shadow_hue, balance)

    def hue_vs_sat(self, points: float) -> 'Chain':
        """Apply hue_vs_sat."""
        return self._add('hue_vs_sat', points)

    def curves_master(self, points: float) -> 'Chain':
        """Apply curves_master."""
        return self._add('curves_master', points)

    def curves_blue(self, points: float) -> 'Chain':
        """Apply curves_blue."""
        return self._add('curves_blue', points)

    def hue_vs_lum(self, points: float) -> 'Chain':
        """Apply hue_vs_lum."""
        return self._add('hue_vs_lum', points)

    def asc_cdl(self, slope_r: float, slope_g: float, slope_b: float, offset_r: float, offset_g: float, offset_b: float, power_r: float, power_g: float, power_b: float) -> 'Chain':
        """Apply asc_cdl."""
        return self._add('asc_cdl', slope_r, slope_g, slope_b, offset_r, offset_g, offset_b, power_r, power_g, power_b)

    def lum_vs_sat(self, points: float) -> 'Chain':
        """Apply lum_vs_sat."""
        return self._add('lum_vs_sat', points)

    def sat_vs_sat(self, points: float) -> 'Chain':
        """Apply sat_vs_sat."""
        return self._add('sat_vs_sat', points)

    def connected_components(self, connectivity: int) -> 'Chain':
        """Apply connected_components."""
        return self._add('connected_components', connectivity)

    def hough_lines(self, threshold: int, min_length: int, max_gap: int) -> 'Chain':
        """Apply hough_lines."""
        return self._add('hough_lines', threshold, min_length, max_gap)

    def depolar(self) -> 'Chain':
        """Apply depolar."""
        return self._add('depolar')

    def wave(self, amplitude: float, wavelength: float, vertical: float) -> 'Chain':
        """Apply wave."""
        return self._add('wave', amplitude, wavelength, vertical)

    def polar(self) -> 'Chain':
        """Apply polar."""
        return self._add('polar')

    def barrel(self, k1: float, k2: float) -> 'Chain':
        """Apply barrel."""
        return self._add('barrel', k1, k2)

    def mesh_warp(self, grid_cols: int, grid_rows: int, grid_json: float) -> 'Chain':
        """Apply mesh_warp."""
        return self._add('mesh_warp', grid_cols, grid_rows, grid_json)

    def ripple(self, amplitude: float, wavelength: float, center_x: float, center_y: float) -> 'Chain':
        """Apply ripple."""
        return self._add('ripple', amplitude, wavelength, center_x, center_y)

    def swirl(self, angle: float, radius: float) -> 'Chain':
        """Apply swirl."""
        return self._add('swirl', angle, radius)

    def spherize(self, amount: float) -> 'Chain':
        """Apply spherize."""
        return self._add('spherize', amount)

    def tonemap_drago(self, bias: float) -> 'Chain':
        """Apply tonemap_drago."""
        return self._add('tonemap_drago', bias)

    def tonemap_reinhard(self) -> 'Chain':
        """Apply tonemap_reinhard."""
        return self._add('tonemap_reinhard')

    def tonemap_filmic(self, shoulder_strength: float, linear_strength: float, linear_angle: float, toe_strength: float, toe_numerator: float) -> 'Chain':
        """Apply tonemap_filmic."""
        return self._add('tonemap_filmic', shoulder_strength, linear_strength, linear_angle, toe_strength, toe_numerator)

    def sepia(self, intensity: float) -> 'Chain':
        """Apply sepia."""
        return self._add('sepia', intensity)

    def saturate(self, factor: float) -> 'Chain':
        """Apply saturate."""
        return self._add('saturate', factor)

    def photo_filter(self, color_r: int, color_g: int, color_b: int, density: float, preserve_luminosity: int) -> 'Chain':
        """Apply photo_filter."""
        return self._add('photo_filter', color_r, color_g, color_b, density, preserve_luminosity)

    def hue_rotate(self, degrees: float) -> 'Chain':
        """Apply hue_rotate."""
        return self._add('hue_rotate', degrees)

    def quantize(self, max_colors: int) -> 'Chain':
        """Apply quantize."""
        return self._add('quantize', max_colors)

    def gradient_map(self, stops: float) -> 'Chain':
        """Apply gradient_map."""
        return self._add('gradient_map', stops)

    def modulate(self, brightness: float, saturation: float, hue: float) -> 'Chain':
        """Apply modulate."""
        return self._add('modulate', brightness, saturation, hue)

    def selective_color(self, target_hue: float, hue_range: float, hue_shift: float, saturation: float, lightness: float) -> 'Chain':
        """Apply selective_color."""
        return self._add('selective_color', target_hue, hue_range, hue_shift, saturation, lightness)

    def channel_mixer(self, rr: float, rg: float, rb: float, gr: float, gg: float, gb: float, br: float, bg: float, bb: float) -> 'Chain':
        """Apply channel_mixer."""
        return self._add('channel_mixer', rr, rg, rb, gr, gg, gb, br, bg, bb)

    def lab_sharpen(self, amount: float, radius: float) -> 'Chain':
        """Apply lab_sharpen."""
        return self._add('lab_sharpen', amount, radius)

    def lab_adjust(self, a_offset: float, b_offset: float) -> 'Chain':
        """Apply lab_adjust."""
        return self._add('lab_adjust', a_offset, b_offset)

    def white_balance_gray_world(self) -> 'Chain':
        """Apply white_balance_gray_world."""
        return self._add('white_balance_gray_world')

    def dither_ordered(self, max_colors: int, map_size: int) -> 'Chain':
        """Apply dither_ordered."""
        return self._add('dither_ordered', max_colors, map_size)

    def dither_floyd_steinberg(self, max_colors: int) -> 'Chain':
        """Apply dither_floyd_steinberg."""
        return self._add('dither_floyd_steinberg', max_colors)

    def colorize(self, target: float, amount: float) -> 'Chain':
        """Apply colorize."""
        return self._add('colorize', target, amount)

    def kmeans_quantize(self, k: int, max_iterations: int, seed: int) -> 'Chain':
        """Apply kmeans_quantize."""
        return self._add('kmeans_quantize', k, max_iterations, seed)

    def sparse_color(self, points: float, power: float) -> 'Chain':
        """Apply sparse_color."""
        return self._add('sparse_color', points, power)

    def vibrance(self, amount: float) -> 'Chain':
        """Apply vibrance."""
        return self._add('vibrance', amount)

    def white_balance_temperature(self, temperature: float, tint: float) -> 'Chain':
        """Apply white_balance_temperature."""
        return self._add('white_balance_temperature', temperature, tint)

    def oil_paint(self, radius: int) -> 'Chain':
        """Apply oil_paint."""
        return self._add('oil_paint', radius)

    def poisson_noise(self, scale: float, seed: int) -> 'Chain':
        """Apply poisson_noise."""
        return self._add('poisson_noise', scale, seed)

    def solarize(self, threshold: int) -> 'Chain':
        """Apply solarize."""
        return self._add('solarize', threshold)

    def salt_pepper_noise(self, density: float, seed: int) -> 'Chain':
        """Apply salt_pepper_noise."""
        return self._add('salt_pepper_noise', density, seed)

    def film_grain(self, amount: float, size: float, seed: int) -> 'Chain':
        """Apply film_grain."""
        return self._add('film_grain', amount, size, seed)

    def pixelate(self, block_size: int) -> 'Chain':
        """Apply pixelate."""
        return self._add('pixelate', block_size)

    def uniform_noise(self, range: float, seed: int) -> 'Chain':
        """Apply uniform_noise."""
        return self._add('uniform_noise', range, seed)

    def gaussian_noise(self, amount: float, mean: float, sigma: float, seed: int) -> 'Chain':
        """Apply gaussian_noise."""
        return self._add('gaussian_noise', amount, mean, sigma, seed)

    def halftone(self, dot_size: float, angle_offset: float) -> 'Chain':
        """Apply halftone."""
        return self._add('halftone', dot_size, angle_offset)

    def emboss(self) -> 'Chain':
        """Apply emboss."""
        return self._add('emboss')

    def evaluate_multiply(self, factor: float) -> 'Chain':
        """Apply evaluate_multiply."""
        return self._add('evaluate_multiply', factor)

    def evaluate_subtract(self, value: float) -> 'Chain':
        """Apply evaluate_subtract."""
        return self._add('evaluate_subtract', value)

    def evaluate_min(self, value: int) -> 'Chain':
        """Apply evaluate_min."""
        return self._add('evaluate_min', value)

    def evaluate_abs(self) -> 'Chain':
        """Apply evaluate_abs."""
        return self._add('evaluate_abs')

    def evaluate_log(self, base: float) -> 'Chain':
        """Apply evaluate_log."""
        return self._add('evaluate_log', base)

    def evaluate_add(self, value: float) -> 'Chain':
        """Apply evaluate_add."""
        return self._add('evaluate_add', value)

    def evaluate_pow(self, exponent: float) -> 'Chain':
        """Apply evaluate_pow."""
        return self._add('evaluate_pow', exponent)

    def evaluate_max(self, value: int) -> 'Chain':
        """Apply evaluate_max."""
        return self._add('evaluate_max', value)

    def evaluate_divide(self, factor: float) -> 'Chain':
        """Apply evaluate_divide."""
        return self._add('evaluate_divide', factor)

    def threshold_binary(self, thresh: int, max_value: int) -> 'Chain':
        """Apply threshold_binary."""
        return self._add('threshold_binary', thresh, max_value)

    def triangle_threshold(self) -> 'Chain':
        """Apply triangle_threshold."""
        return self._add('triangle_threshold')

    def otsu_threshold(self) -> 'Chain':
        """Apply otsu_threshold."""
        return self._add('otsu_threshold')

    def adaptive_threshold(self, max_value: int, method: int, block_size: int, c: float) -> 'Chain':
        """Apply adaptive_threshold."""
        return self._add('adaptive_threshold', max_value, method, block_size, c)

    def morph_close(self, ksize: int, shape: int) -> 'Chain':
        """Apply morph_close."""
        return self._add('morph_close', ksize, shape)

    def morph_tophat(self, ksize: int, shape: int) -> 'Chain':
        """Apply morph_tophat."""
        return self._add('morph_tophat', ksize, shape)

    def morph_gradient(self, ksize: int, shape: int) -> 'Chain':
        """Apply morph_gradient."""
        return self._add('morph_gradient', ksize, shape)

    def erode(self, ksize: int, shape: int) -> 'Chain':
        """Apply erode."""
        return self._add('erode', ksize, shape)

    def morph_blackhat(self, ksize: int, shape: int) -> 'Chain':
        """Apply morph_blackhat."""
        return self._add('morph_blackhat', ksize, shape)

    def morph_open(self, ksize: int, shape: int) -> 'Chain':
        """Apply morph_open."""
        return self._add('morph_open', ksize, shape)

    def skeletonize(self, max_iterations: int) -> 'Chain':
        """Apply skeletonize."""
        return self._add('skeletonize', max_iterations)

    def dilate(self, ksize: int, shape: int) -> 'Chain':
        """Apply dilate."""
        return self._add('dilate', ksize, shape)

    def guided_filter(self, radius: int, epsilon: float) -> 'Chain':
        """Apply guided_filter."""
        return self._add('guided_filter', radius, epsilon)

    def lens_blur(self, radius: int, blade_count: int, rotation: float) -> 'Chain':
        """Apply lens_blur."""
        return self._add('lens_blur', radius, blade_count, rotation)

    def kuwahara(self, radius: int) -> 'Chain':
        """Apply kuwahara."""
        return self._add('kuwahara', radius)

    def sharpen(self, amount: float) -> 'Chain':
        """Apply sharpen."""
        return self._add('sharpen', amount)

    def displacement_map(self, map_x: float, map_y: float) -> 'Chain':
        """Apply displacement_map."""
        return self._add('displacement_map', map_x, map_y)

    def zoom_blur(self, center_x: float, center_y: float, factor: float) -> 'Chain':
        """Apply zoom_blur."""
        return self._add('zoom_blur', center_x, center_y, factor)

    def convolve(self, kw: int, kh: int, divisor: float) -> 'Chain':
        """Apply convolve."""
        return self._add('convolve', kw, kh, divisor)

    def smart_sharpen(self, amount: float, radius: int, threshold: float) -> 'Chain':
        """Apply smart_sharpen."""
        return self._add('smart_sharpen', amount, radius, threshold)

    def high_pass(self, radius: float) -> 'Chain':
        """Apply high_pass."""
        return self._add('high_pass', radius)

    def rank_filter(self, radius: int, rank: float) -> 'Chain':
        """Apply rank_filter."""
        return self._add('rank_filter', radius, rank)

    def box_blur(self, radius: int) -> 'Chain':
        """Apply box_blur."""
        return self._add('box_blur', radius)

    def bokeh_blur(self, radius: int, shape: int) -> 'Chain':
        """Apply bokeh_blur."""
        return self._add('bokeh_blur', radius, shape)

    def average_blur(self) -> 'Chain':
        """Apply average_blur."""
        return self._add('average_blur')

    def gaussian_blur_cv(self, sigma: float) -> 'Chain':
        """Apply gaussian_blur_cv."""
        return self._add('gaussian_blur_cv', sigma)

    def tilt_shift(self, focus_position: float, band_size: float, blur_radius: float, angle: float) -> 'Chain':
        """Apply tilt_shift."""
        return self._add('tilt_shift', focus_position, band_size, blur_radius, angle)

    def motion_blur(self, length: int, angle_degrees: float) -> 'Chain':
        """Apply motion_blur."""
        return self._add('motion_blur', length, angle_degrees)

    def median(self, radius: int) -> 'Chain':
        """Apply median."""
        return self._add('median', radius)

    def blur(self, radius: float) -> 'Chain':
        """Apply blur."""
        return self._add('blur', radius)

    def bilateral(self, diameter: int, sigma_color: float, sigma_space: float) -> 'Chain':
        """Apply bilateral."""
        return self._add('bilateral', diameter, sigma_color, sigma_space)

    def spin_blur(self, center_x: float, center_y: float, angle: float) -> 'Chain':
        """Apply spin_blur."""
        return self._add('spin_blur', center_x, center_y, angle)

    def unpremultiply(self) -> 'Chain':
        """Apply unpremultiply."""
        return self._add('unpremultiply')

    def premultiply(self) -> 'Chain':
        """Apply premultiply."""
        return self._add('premultiply')

    def seam_carve_width(self, target_width: int) -> 'Chain':
        """Apply seam_carve_width."""
        return self._add('seam_carve_width', target_width)

    def seam_carve_height(self, target_height: int) -> 'Chain':
        """Apply seam_carve_height."""
        return self._add('seam_carve_height', target_height)

    def smart_crop(self, target_width: int, target_height: int) -> 'Chain':
        """Apply smart_crop."""
        return self._add('smart_crop', target_width, target_height)

    def draw_polygon(self, fill_color: float, stroke_color: float, stroke_width: float, filled: bool) -> 'Chain':
        """Apply draw_polygon."""
        return self._add('draw_polygon', fill_color, stroke_color, stroke_width, filled)

    def draw_rect(self, x: float, y: float, rect_width: float, rect_height: float, color: float, stroke_width: float, filled: bool) -> 'Chain':
        """Apply draw_rect."""
        return self._add('draw_rect', x, y, rect_width, rect_height, color, stroke_width, filled)

    def draw_line(self, x1: float, y1: float, x2: float, y2: float, color: float, width: float) -> 'Chain':
        """Apply draw_line."""
        return self._add('draw_line', x1, y1, x2, y2, color, width)

    def draw_ellipse(self, cx: float, cy: float, rx: float, ry: float, color: float, stroke_width: float, filled: bool) -> 'Chain':
        """Apply draw_ellipse."""
        return self._add('draw_ellipse', cx, cy, rx, ry, color, stroke_width, filled)

    def draw_text(self, x: int, y: int, scale: int, color: float) -> 'Chain':
        """Apply draw_text."""
        return self._add('draw_text', x, y, scale, color)

    def draw_text_ttf(self, x: int, y: int, font_size_pt: float, color_r: int, color_g: int, color_b: int, color_a: int) -> 'Chain':
        """Apply draw_text_ttf."""
        return self._add('draw_text_ttf', x, y, font_size_pt, color_r, color_g, color_b, color_a)

    def draw_arc(self, cx: float, cy: float, rx: float, ry: float, start_angle: float, end_angle: float, color: float, stroke_width: float) -> 'Chain':
        """Apply draw_arc."""
        return self._add('draw_arc', cx, cy, rx, ry, start_angle, end_angle, color, stroke_width)

    def draw_circle(self, cx: float, cy: float, radius: float, color: float, stroke_width: float, filled: bool) -> 'Chain':
        """Apply draw_circle."""
        return self._add('draw_circle', cx, cy, radius, color, stroke_width, filled)

    def flood_fill(self, seed_x: int, seed_y: int, new_val: int, tolerance: int, connectivity: int) -> 'Chain':
        """Apply flood_fill."""
        return self._add('flood_fill', seed_x, seed_y, new_val, tolerance, connectivity)

    def gradient_linear(self) -> 'Chain':
        """Apply gradient_linear."""
        return self._add('gradient_linear')

    def plasma(self) -> 'Chain':
        """Apply plasma."""
        return self._add('plasma')

    def gradient_radial(self) -> 'Chain':
        """Apply gradient_radial."""
        return self._add('gradient_radial')

    def simplex_noise(self) -> 'Chain':
        """Apply simplex_noise."""
        return self._add('simplex_noise')

    def perlin_noise(self) -> 'Chain':
        """Apply perlin_noise."""
        return self._add('perlin_noise')

    def checkerboard(self) -> 'Chain':
        """Apply checkerboard."""
        return self._add('checkerboard')

    def grayscale(self) -> 'Chain':
        """Apply grayscale."""
        return self._add('grayscale')

    def lab_extract_l(self) -> 'Chain':
        """Apply lab_extract_l."""
        return self._add('lab_extract_l')

    def lab_extract_a(self) -> 'Chain':
        """Apply lab_extract_a."""
        return self._add('lab_extract_a')

    def lab_extract_b(self) -> 'Chain':
        """Apply lab_extract_b."""
        return self._add('lab_extract_b')

    def charcoal(self, radius: float, sigma: float) -> 'Chain':
        """Apply charcoal."""
        return self._add('charcoal', radius, sigma)

    def canny(self, low_threshold: float, high_threshold: float) -> 'Chain':
        """Apply canny."""
        return self._add('canny', low_threshold, high_threshold)

    def laplacian(self) -> 'Chain':
        """Apply laplacian."""
        return self._add('laplacian')

    def scharr(self) -> 'Chain':
        """Apply scharr."""
        return self._add('scharr')

    def sobel(self) -> 'Chain':
        """Apply sobel."""
        return self._add('sobel')

    def flatten(self, bg_r: int, bg_g: int, bg_b: int) -> 'Chain':
        """Apply flatten."""
        return self._add('flatten', bg_r, bg_g, bg_b)

    def add_alpha(self, alpha: int) -> 'Chain':
        """Apply add_alpha."""
        return self._add('add_alpha', alpha)

    def remove_alpha(self) -> 'Chain':
        """Apply remove_alpha."""
        return self._add('remove_alpha')

