pub mod avif;
pub mod bmp;
pub mod cube;
pub mod dds;
// LUT encoder modules (registered via StaticLutEncoderRegistration, not pixel encoders)
pub mod hald;
pub mod lut3dl;
pub mod lutcsp;
pub mod exr;
pub mod fits;
pub mod gif;
pub mod hdr;
pub mod heic;
pub mod ico;
pub mod jp2;
pub mod jpeg;
pub mod native_trivial;
pub mod png;
pub mod pnm;
pub mod qoi;
pub mod streaming;
pub mod tga;
pub mod tiff;
pub mod webp;

use super::error::ImageError;
use super::types::{FrameSequence, ImageInfo};

// ─── Generated encode dispatch ──────────────────────────────────────────────
include!(concat!(env!("OUT_DIR"), "/generated_encode_dispatch.rs"));

// ─── Static Registration (for proc macro + inventory) ─────────────────────

/// Static encoder registration metadata — generated by `#[register_encoder]`.
#[derive(Debug)]
pub struct StaticEncoderRegistration {
    pub name: &'static str,
    pub format: &'static str,
    pub mime: &'static str,
    pub extensions: &'static [&'static str],
    pub fn_name: &'static str,
}

inventory::collect!(&'static StaticEncoderRegistration);

/// List all registered encoders (from all linked crates).
pub fn registered_encoders() -> Vec<&'static StaticEncoderRegistration> {
    inventory::iter::<&'static StaticEncoderRegistration>
        .into_iter()
        .copied()
        .collect()
}


// ─── LUT Encoder Registry ───────────────────────────────────────────────────

/// Static LUT encoder registration — for formats that encode a ColorLut3D
/// instead of pixel data (e.g., .cube, .3dl, .csp, Hald CLUT).
///
/// LUT encoders short-circuit the pixel pipeline: they extract the fused
/// ColorLut3D from the color op chain and serialize directly.
pub struct StaticLutEncoderRegistration {
    pub format: &'static str,
    pub extensions: &'static [&'static str],
    pub encode_fn: fn(&super::color_lut::ColorLut3D) -> Result<Vec<u8>, ImageError>,
}

inventory::collect!(&'static StaticLutEncoderRegistration);

/// Try to encode a ColorLut3D using a registered LUT encoder.
///
/// Returns `Some(Ok(bytes))` if a LUT encoder is registered for this format,
/// `Some(Err(...))` if the encoder failed, or `None` if no LUT encoder matches.
pub fn encode_lut(
    lut: &super::color_lut::ColorLut3D,
    format: &str,
) -> Option<Result<Vec<u8>, ImageError>> {
    for reg in inventory::iter::<&'static StaticLutEncoderRegistration> {
        if reg.format == format || reg.extensions.contains(&format) {
            return Some((reg.encode_fn)(lut));
        }
    }
    None
}

/// Check if a format is a registered LUT encoder format.
pub fn is_lut_format(format: &str) -> bool {
    inventory::iter::<&'static StaticLutEncoderRegistration>
        .into_iter()
        .any(|r| r.format == format || r.extensions.contains(&format))
}

/// Encode pixel data to a specific image format (convenience wrapper).
///
/// Dispatches to per-format encoders with default configs. The match is
/// auto-generated from encoder config structs at build time.
/// For fine-grained control, use per-format encode functions directly.
pub fn encode(
    pixels: &[u8],
    info: &ImageInfo,
    format: &str,
    quality: Option<u8>,
) -> Result<Vec<u8>, ImageError> {
    generated_encode_dispatch!(pixels, info, format, quality)
}

/// Embed an ICC color profile into encoded image data.
///
/// Currently supports JPEG and PNG. For other formats, returns the
/// encoded data unchanged.
pub fn embed_icc_profile(
    encoded_data: &[u8],
    format: &str,
    icc_profile: &[u8],
) -> Result<Vec<u8>, ImageError> {
    if icc_profile.is_empty() {
        return Ok(encoded_data.to_vec());
    }
    match format {
        "jpeg" | "jpg" => jpeg::embed_icc_profile(encoded_data, icc_profile),
        "png" => png::embed_icc_profile(encoded_data, icc_profile),
        _ => Ok(encoded_data.to_vec()),
    }
}

/// Encode a FrameSequence to a multi-frame format (convenience wrapper).
///
/// Dispatches to format-specific multi-frame encoders. Supports GIF, TIFF,
/// and APNG (animated PNG). All other formats return an error.
pub fn encode_sequence(
    seq: &FrameSequence,
    format: &str,
    quality: Option<u8>,
) -> Result<Vec<u8>, ImageError> {
    let _ = quality; // reserved for future lossy multi-frame formats
    match format {
        "gif" => {
            let config = gif::GifEncodeConfig::default();
            gif::encode_sequence(seq, &config)
        }
        "tiff" | "tif" => {
            let config = tiff::TiffEncodeConfig::default();
            tiff::encode_pages(seq, &config)
        }
        "png" | "apng" => {
            let config = png::PngEncodeConfig::default();
            png::encode_sequence(seq, &config)
        }
        "webp" => Err(ImageError::UnsupportedFormat(
            "animated WebP encode is not supported (image-webp crate limitation)".into(),
        )),
        "jpeg" | "jpg" | "avif" | "heic" | "heif" | "bmp" | "ico" | "qoi" | "tga" | "hdr"
        | "pnm" | "exr" | "dds" | "jp2" => Err(ImageError::UnsupportedFormat(format!(
            "format '{format}' does not support multi-frame encoding"
        ))),
        other => Err(ImageError::UnsupportedFormat(format!(
            "encode_sequence: format '{other}' not supported"
        ))),
    }
}

/// List supported encode formats (derived from encoder registry).
pub fn supported_formats() -> Vec<String> {
    registered_encoders().iter().map(|r| r.format.to_string()).collect()
}

/// Format metadata: name, MIME type, and file extensions.
#[derive(Debug, Clone)]
pub struct FormatInfo {
    pub name: String,
    pub mime_type: String,
    pub extensions: Vec<String>,
}

/// Get format metadata for a specific format (from encoder registry).
pub fn format_info(format: &str) -> Option<FormatInfo> {
    registered_encoders().iter()
        .find(|r| r.format == format || r.extensions.contains(&format))
        .map(|r| FormatInfo {
            name: r.format.to_string(),
            mime_type: r.mime.to_string(),
            extensions: r.extensions.iter().map(|s| s.to_string()).collect(),
        })
}

/// Get format metadata for all supported encode formats (from encoder registry).
pub fn all_format_info() -> Vec<FormatInfo> {
    registered_encoders().iter()
        .map(|r| FormatInfo {
            name: r.format.to_string(),
            mime_type: r.mime.to_string(),
            extensions: r.extensions.iter().map(|s| s.to_string()).collect(),
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::domain::types::{
        ColorSpace, DecodedImage, DisposalMethod, FrameInfo, FrameSequence, PixelFormat,
    };

    fn make_rgb8_pixels(width: u32, height: u32) -> (Vec<u8>, ImageInfo) {
        let pixels: Vec<u8> = (0..(width * height * 3)).map(|i| (i % 256) as u8).collect();
        let info = ImageInfo {
            width,
            height,
            format: PixelFormat::Rgb8,
            color_space: ColorSpace::Srgb,
        };
        (pixels, info)
    }

    fn make_rgba8_pixels(width: u32, height: u32) -> (Vec<u8>, ImageInfo) {
        let pixels: Vec<u8> = (0..(width * height * 4)).map(|i| (i % 256) as u8).collect();
        let info = ImageInfo {
            width,
            height,
            format: PixelFormat::Rgba8,
            color_space: ColorSpace::Srgb,
        };
        (pixels, info)
    }

    #[test]
    fn encode_png_produces_valid_png() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "png", None).unwrap();
        assert_eq!(&result[..4], &[0x89, 0x50, 0x4E, 0x47]);
    }

    #[test]
    fn encode_jpeg_produces_valid_jpeg() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "jpeg", Some(90)).unwrap();
        assert_eq!(&result[..2], &[0xFF, 0xD8]);
    }

    #[test]
    fn encode_jpeg_default_quality() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "jpeg", None);
        assert!(result.is_ok());
    }

    #[test]
    fn encode_webp_produces_output() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "webp", None);
        assert!(result.is_ok());
        assert!(!result.unwrap().is_empty());
    }

    #[test]
    fn encode_rgba8_to_png() {
        let (pixels, info) = make_rgba8_pixels(8, 8);
        let result = encode(&pixels, &info, "png", None);
        assert!(result.is_ok());
    }

    #[test]
    fn encode_unsupported_format_returns_error() {
        let (pixels, info) = make_rgb8_pixels(8, 8);
        let result = encode(&pixels, &info, "svg", None);
        assert!(result.is_err());
        match result.unwrap_err() {
            ImageError::UnsupportedFormat(_) => {}
            other => panic!("expected UnsupportedFormat, got {other:?}"),
        }
    }

    #[test]
    fn encode_mismatched_pixel_data_returns_error() {
        let info = ImageInfo {
            width: 100,
            height: 100,
            format: PixelFormat::Rgb8,
            color_space: ColorSpace::Srgb,
        };
        let result = encode(&[0u8; 10], &info, "png", None);
        assert!(result.is_err());
    }

    #[test]
    fn encode_unsupported_pixel_format_returns_error() {
        let info = ImageInfo {
            width: 8,
            height: 8,
            format: PixelFormat::Yuv420p,
            color_space: ColorSpace::Srgb,
        };
        let pixels = vec![0u8; 8 * 8 * 3];
        let result = encode(&pixels, &info, "png", None);
        assert!(result.is_err());
    }

    #[test]
    fn roundtrip_png_preserves_pixels() {
        let (pixels, info) = make_rgb8_pixels(8, 8);
        let encoded = encode(&pixels, &info, "png", None).unwrap();
        let decoded = crate::domain::decoder::decode(&encoded).unwrap();
        assert_eq!(decoded.info.width, 8);
        assert_eq!(decoded.info.height, 8);
        assert_eq!(decoded.pixels, pixels);
    }

    #[test]
    fn encode_gif_produces_valid_gif() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "gif", None).unwrap();
        assert_eq!(&result[..3], b"GIF");
    }

    #[test]
    fn encode_gif_rgba8() {
        let (pixels, info) = make_rgba8_pixels(8, 8);
        let result = encode(&pixels, &info, "gif", None);
        assert!(result.is_ok());
    }

    #[test]
    fn roundtrip_gif_preserves_dimensions() {
        let (pixels, info) = make_rgb8_pixels(8, 8);
        let encoded = encode(&pixels, &info, "gif", None).unwrap();
        let decoded = crate::domain::decoder::decode(&encoded).unwrap();
        assert_eq!(decoded.info.width, 8);
        assert_eq!(decoded.info.height, 8);
    }

    #[test]
    fn encode_avif_returns_unsupported() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "avif", Some(50));
        assert!(
            result.is_err(),
            "AVIF encode should return UnsupportedFormat (rav1e removed)"
        );
    }

    #[test]
    fn supported_formats_lists_expected() {
        let fmts = supported_formats();
        for f in [
            "png", "jpeg", "webp", "gif", "tiff", "bmp", "ico", "qoi", "tga", "hdr", "pnm", "exr",
            "dds", "jp2",
        ] {
            assert!(fmts.contains(&f.to_string()), "missing format: {f}");
        }
    }

    // ---- New trivial format tests ----

    #[test]
    fn encode_tga_produces_output() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "tga", None);
        assert!(result.is_ok());
        assert!(!result.unwrap().is_empty());
    }

    #[test]
    fn roundtrip_tga_preserves_dimensions() {
        let (pixels, info) = make_rgb8_pixels(8, 8);
        let encoded = encode(&pixels, &info, "tga", None).unwrap();
        let decoded = crate::domain::decoder::decode(&encoded).unwrap();
        assert_eq!(decoded.info.width, 8);
        assert_eq!(decoded.info.height, 8);
    }

    #[test]
    fn encode_hdr_produces_output() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "hdr", None);
        assert!(result.is_ok());
        let data = result.unwrap();
        // HDR files start with "#?RADIANCE" or "#?RGBE"
        assert!(
            data.starts_with(b"#?RADIANCE") || data.starts_with(b"#?RGBE"),
            "HDR should start with Radiance signature"
        );
    }

    #[test]
    fn roundtrip_hdr_preserves_dimensions() {
        let (pixels, info) = make_rgb8_pixels(8, 8);
        let encoded = encode(&pixels, &info, "hdr", None).unwrap();
        let decoded = crate::domain::decoder::decode(&encoded).unwrap();
        assert_eq!(decoded.info.width, 8);
        assert_eq!(decoded.info.height, 8);
    }

    #[test]
    fn encode_pnm_produces_output() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "pnm", None);
        assert!(result.is_ok());
        let data = result.unwrap();
        // PPM starts with "P6" (binary) or "P3" (ASCII)
        assert!(data[0] == b'P', "PNM should start with 'P'");
    }

    #[test]
    fn roundtrip_pnm_preserves_pixels() {
        let (pixels, info) = make_rgb8_pixels(8, 8);
        let encoded = encode(&pixels, &info, "pnm", None).unwrap();
        let decoded = crate::domain::decoder::decode(&encoded).unwrap();
        assert_eq!(decoded.info.width, 8);
        assert_eq!(decoded.info.height, 8);
        // PNM is lossless
        assert_eq!(decoded.pixels, pixels);
    }

    #[test]
    fn encode_exr_produces_output() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "exr", None);
        assert!(result.is_ok());
        let data = result.unwrap();
        // EXR magic: 0x76, 0x2F, 0x31, 0x01
        assert_eq!(&data[..4], &[0x76, 0x2F, 0x31, 0x01]);
    }

    #[test]
    fn roundtrip_exr_preserves_dimensions() {
        let (pixels, info) = make_rgb8_pixels(8, 8);
        let encoded = encode(&pixels, &info, "exr", None).unwrap();
        let decoded = crate::domain::decoder::decode(&encoded).unwrap();
        assert_eq!(decoded.info.width, 8);
        assert_eq!(decoded.info.height, 8);
    }

    #[test]
    fn encode_dds_produces_output() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "dds", None);
        assert!(result.is_ok());
        let data = result.unwrap();
        assert_eq!(&data[..4], b"DDS ");
    }

    #[test]
    fn roundtrip_dds_header_and_pixels() {
        let (pixels, info) = make_rgb8_pixels(8, 8);
        let encoded = encode(&pixels, &info, "dds", None).unwrap();
        // Verify DDS magic
        assert_eq!(&encoded[..4], b"DDS ");
        // Read dimensions from header (offset 12 = height, 16 = width)
        let h = u32::from_le_bytes([encoded[12], encoded[13], encoded[14], encoded[15]]);
        let w = u32::from_le_bytes([encoded[16], encoded[17], encoded[18], encoded[19]]);
        assert_eq!(w, 8);
        assert_eq!(h, 8);
        // Pixel data starts at offset 128, should be 8*8*4 = 256 bytes of BGRA
        assert_eq!(encoded.len(), 128 + 8 * 8 * 4);
        // Verify first pixel: RGB input (0,1,2) -> BGRA (2,1,0,255)
        assert_eq!(encoded[128], 2); // B
        assert_eq!(encoded[129], 1); // G
        assert_eq!(encoded[130], 0); // R
        assert_eq!(encoded[131], 255); // A
    }

    #[test]
    fn encode_tga_rgba8() {
        let (pixels, info) = make_rgba8_pixels(8, 8);
        let result = encode(&pixels, &info, "tga", None);
        assert!(result.is_ok());
    }

    #[test]
    fn encode_dds_rgba8() {
        let (pixels, info) = make_rgba8_pixels(8, 8);
        let result = encode(&pixels, &info, "dds", None);
        assert!(result.is_ok());
    }

    // ---- BMP/ICO/QOI encoder tests ----

    #[test]
    fn encode_bmp_produces_valid_bmp() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "bmp", None).unwrap();
        assert_eq!(&result[..2], b"BM");
    }

    #[test]
    fn roundtrip_bmp_preserves_pixels() {
        let (pixels, info) = make_rgb8_pixels(8, 8);
        let encoded = encode(&pixels, &info, "bmp", None).unwrap();
        let decoded = crate::domain::decoder::decode(&encoded).unwrap();
        assert_eq!(decoded.info.width, 8);
        assert_eq!(decoded.info.height, 8);
        // BMP is lossless — pixels should match exactly
        assert_eq!(decoded.pixels, pixels);
    }

    #[test]
    fn encode_ico_produces_valid_ico() {
        let (pixels, info) = make_rgba8_pixels(16, 16);
        let result = encode(&pixels, &info, "ico", None).unwrap();
        // ICO magic: 00 00 01 00
        assert_eq!(&result[..4], &[0x00, 0x00, 0x01, 0x00]);
    }

    #[test]
    fn roundtrip_ico_preserves_dimensions() {
        let (pixels, info) = make_rgba8_pixels(32, 32);
        let encoded = encode(&pixels, &info, "ico", None).unwrap();
        let decoded = crate::domain::decoder::decode(&encoded).unwrap();
        assert_eq!(decoded.info.width, 32);
        assert_eq!(decoded.info.height, 32);
    }

    #[test]
    fn encode_qoi_produces_valid_qoi() {
        let (pixels, info) = make_rgb8_pixels(16, 16);
        let result = encode(&pixels, &info, "qoi", None).unwrap();
        assert_eq!(&result[..4], b"qoif");
    }

    #[test]
    fn roundtrip_qoi_preserves_pixels() {
        let (pixels, info) = make_rgba8_pixels(8, 8);
        let encoded = encode(&pixels, &info, "qoi", None).unwrap();
        let decoded = crate::domain::decoder::decode(&encoded).unwrap();
        assert_eq!(decoded.info.width, 8);
        assert_eq!(decoded.info.height, 8);
        // QOI is lossless
        assert_eq!(decoded.pixels, pixels);
    }

    #[test]
    fn format_info_jpeg() {
        let fi = format_info("jpeg").expect("jpeg should be supported");
        assert_eq!(fi.name, "jpeg");
        assert_eq!(fi.mime_type, "image/jpeg");
        assert!(fi.extensions.contains(&"jpg".to_string()));
        assert!(fi.extensions.contains(&"jpeg".to_string()));
    }

    #[test]
    fn format_info_unknown_returns_none() {
        assert!(format_info("nosuchformat").is_none());
    }

    #[test]
    fn all_format_info_covers_supported() {
        let infos = all_format_info();
        let names: Vec<&str> = infos.iter().map(|fi| fi.name.as_str()).collect();
        assert!(names.contains(&"jpeg"));
        assert!(names.contains(&"png"));
        assert!(names.contains(&"webp"));
        assert!(names.contains(&"tiff"));
        assert!(names.contains(&"bmp"));
        assert!(names.contains(&"qoi"));
        assert!(names.contains(&"gif"));
        assert_eq!(infos.len(), registered_encoders().len());
    }

    #[test]
    fn all_format_info_has_mime_for_every_format() {
        for fi in all_format_info() {
            assert!(
                !fi.mime_type.is_empty(),
                "format {} has empty MIME",
                fi.name
            );
            // Every format should have at least one extension
            assert!(
                !fi.extensions.is_empty(),
                "format {} has no extensions",
                fi.name
            );
        }
    }

    #[test]
    fn format_info_default_mime() {
        // Formats without well-known IANA types should get a mime anyway
        for fmt in &["tga", "hdr", "exr", "dds"] {
            let fi = format_info(fmt).unwrap();
            assert!(!fi.mime_type.is_empty(), "{fmt} should have a MIME type");
        }
    }

    // ── encode_sequence convenience router tests ───────────────────

    fn make_test_sequence(n: usize) -> FrameSequence {
        let mut seq = FrameSequence::new(4, 4);
        for i in 0..n {
            let pixels: Vec<u8> = (0..16).flat_map(|_| [(i * 80) as u8, 0u8, 0u8]).collect();
            let image = DecodedImage {
                pixels,
                info: ImageInfo {
                    width: 4,
                    height: 4,
                    format: PixelFormat::Rgb8,
                    color_space: ColorSpace::Srgb,
                },
                icc_profile: None,
            };
            let fi = FrameInfo {
                index: i as u32,
                delay_ms: 100,
                disposal: DisposalMethod::None,
                width: 4,
                height: 4,
                x_offset: 0,
                y_offset: 0,
            };
            seq.push(image, fi);
        }
        seq
    }

    #[test]
    fn encode_sequence_gif_dispatches() {
        let seq = make_test_sequence(2);
        let result = encode_sequence(&seq, "gif", None).unwrap();
        assert_eq!(&result[..3], b"GIF");
    }

    #[test]
    fn encode_sequence_tiff_dispatches() {
        let seq = make_test_sequence(2);
        let result = encode_sequence(&seq, "tiff", None).unwrap();
        assert!(&result[..2] == b"II" || &result[..2] == b"MM");
    }

    #[test]
    fn encode_sequence_tif_alias() {
        let seq = make_test_sequence(2);
        let result = encode_sequence(&seq, "tif", None);
        assert!(result.is_ok());
    }

    #[test]
    fn encode_sequence_webp_returns_unsupported() {
        let seq = make_test_sequence(2);
        let result = encode_sequence(&seq, "webp", None);
        assert!(result.is_err());
        match result.unwrap_err() {
            ImageError::UnsupportedFormat(msg) => {
                assert!(msg.contains("animated WebP"), "message: {msg}");
            }
            other => panic!("expected UnsupportedFormat, got {other:?}"),
        }
    }

    #[test]
    fn encode_sequence_jpeg_returns_unsupported() {
        let seq = make_test_sequence(2);
        let result = encode_sequence(&seq, "jpeg", None);
        assert!(result.is_err());
        match result.unwrap_err() {
            ImageError::UnsupportedFormat(msg) => {
                assert!(msg.contains("multi-frame"), "message: {msg}");
            }
            other => panic!("expected UnsupportedFormat, got {other:?}"),
        }
    }

    #[test]
    fn encode_sequence_unknown_format_returns_error() {
        let seq = make_test_sequence(2);
        let result = encode_sequence(&seq, "nosuchformat", None);
        assert!(result.is_err());
    }
}
