// Command generate reads param-manifest.json and generates fluent Chain methods
// for the rcimg Go SDK and optionally a Python SDK.
//
// Usage:
//
//	go run ./cmd/generate -manifest path/to/param-manifest.json [-python path/to/output.py]
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"
	"unicode"
)

type Manifest struct {
	Filters     []OpEntry      `json:"filters"`
	Transforms  []OpEntry      `json:"transforms"`
	Generators  []OpEntry      `json:"generators"`
	Compositors []OpEntry      `json:"compositors"`
	Mappers     []OpEntry      `json:"mappers"`
	Encoders    []EncoderEntry `json:"encoders"`
}

type OpEntry struct {
	Name       string  `json:"name"`
	Params     []Param `json:"params"`
	Category   string  `json:"category"`
	Group      string  `json:"group"`
	MultiInput bool    `json:"multi_input"`
}

type Param struct {
	Name    string      `json:"name"`
	Type    string      `json:"type"`
	Default interface{} `json:"default"`
}

type EncoderEntry struct {
	Format        string         `json:"format"`
	Params        []EncoderParam `json:"params"`
	TakesMetadata bool           `json:"takes_metadata"`
}

type EncoderParam struct {
	Name         string   `json:"name"`
	Type         string   `json:"type"`
	Default      interface{} `json:"default"`
	EnumVariants []string `json:"enum_variants"`
}

func main() {
	manifestPath := flag.String("manifest", "", "Path to param-manifest.json")
	pythonOut := flag.String("python", "", "Path for Python output (optional)")
	flag.Parse()

	if *manifestPath == "" {
		fmt.Fprintf(os.Stderr, "Usage: generate -manifest <path> [-python <path>]\n")
		os.Exit(1)
	}

	data, err := os.ReadFile(*manifestPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading manifest: %v\n", err)
		os.Exit(1)
	}

	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing manifest: %v\n", err)
		os.Exit(1)
	}

	goCode := generateGo(&m)
	if err := os.WriteFile("rcimg/chain_generated.go", []byte(goCode), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing Go output: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Generated rcimg/chain_generated.go (%d ops)\n", countOps(&m))

	if *pythonOut != "" {
		pyCode := generatePython(&m)
		if err := os.WriteFile(*pythonOut, []byte(pyCode), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing Python output: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "Generated %s\n", *pythonOut)
	}
}

func countOps(m *Manifest) int {
	return len(m.Filters) + len(m.Transforms) + len(m.Generators) + len(m.Mappers)
}

// snakeToPascal converts "foo_bar" to "FooBar"
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		runes := []rune(p)
		runes[0] = unicode.ToUpper(runes[0])
		result.WriteString(string(runes))
	}
	return result.String()
}

// snakeToCamel converts "foo_bar" to "fooBar"
func snakeToCamel(s string) string {
	p := snakeToPascal(s)
	if len(p) == 0 {
		return p
	}
	runes := []rune(p)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

// Go reserved words that can't be used as parameter names
var goReserved = map[string]string{
	"range": "rng", "type": "typ", "func": "fn", "map": "m",
	"var": "v", "chan": "ch", "select": "sel", "default": "def",
	"interface": "iface", "switch": "sw", "case": "cs", "break": "brk",
	"continue": "cont", "go": "goVal", "return": "ret", "defer": "deferVal",
	"c": "cVal",
	"fallthrough": "ft", "for": "f", "if": "cond", "else": "alt",
	"import": "imp", "package": "pkg", "struct": "st", "const": "c",
}

func safeGoName(name string) string {
	if safe, ok := goReserved[name]; ok {
		return safe
	}
	return name
}

// rustTypeToGo maps Rust types to Go types for method signatures
func rustTypeToGo(t string) string {
	switch t {
	case "f32":
		return "float32"
	case "f64":
		return "float64"
	case "u8":
		return "uint8"
	case "u16":
		return "uint16"
	case "u32":
		return "uint32"
	case "u64":
		return "uint64"
	case "i8":
		return "int8"
	case "i16":
		return "int16"
	case "i32":
		return "int32"
	case "i64":
		return "int64"
	case "bool":
		return "bool"
	default:
		// Enums and complex types → float32 (positional param)
		return "float32"
	}
}

// rustTypeToPython maps Rust types to Python type hints
func rustTypeToPython(t string) string {
	switch t {
	case "f32", "f64":
		return "float"
	case "u8", "u16", "u32", "u64", "i8", "i16", "i32", "i64":
		return "int"
	case "bool":
		return "bool"
	default:
		return "float"
	}
}

func generateGo(m *Manifest) string {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/generate; DO NOT EDIT.\n\n")
	b.WriteString("package rcimg\n\n")
	b.WriteString("func boolToFloat(v bool) float32 {\n")
	b.WriteString("\tif v {\n\t\treturn 1.0\n\t}\n\treturn 0.0\n}\n\n")

	// Collect all ops: filters, transforms (skip multi_input), generators, mappers
	type entry struct {
		name   string
		params []Param
	}
	var ops []entry

	for _, t := range m.Transforms {
		if t.MultiInput {
			continue // skip composite etc
		}
		ops = append(ops, entry{t.Name, t.Params})
	}
	for _, f := range m.Filters {
		ops = append(ops, entry{f.Name, f.Params})
	}
	for _, g := range m.Generators {
		ops = append(ops, entry{g.Name, g.Params})
	}
	for _, mp := range m.Mappers {
		ops = append(ops, entry{mp.Name, mp.Params})
	}

	for _, op := range ops {
		methodName := snakeToPascal(op.name)

		if len(op.params) == 0 {
			// No-param op
			fmt.Fprintf(&b, "// %s applies the %s operation.\n", methodName, op.name)
			fmt.Fprintf(&b, "func (c *Chain) %s() *Chain {\n", methodName)
			fmt.Fprintf(&b, "\treturn c.add(\"%s\")\n", op.name)
			fmt.Fprintf(&b, "}\n\n")
		} else {
			// Parameterized op
			var paramSig []string
			var paramArgs []string
			for _, p := range op.params {
				goType := rustTypeToGo(p.Type)
				goName := safeGoName(snakeToCamel(p.Name))
				paramSig = append(paramSig, fmt.Sprintf("%s %s", goName, goType))
				switch goType {
				case "float32":
					paramArgs = append(paramArgs, goName)
				case "bool":
					paramArgs = append(paramArgs, fmt.Sprintf("boolToFloat(%s)", goName))
				default:
					paramArgs = append(paramArgs, fmt.Sprintf("float32(%s)", goName))
				}
			}
			fmt.Fprintf(&b, "// %s applies the %s operation.\n", methodName, op.name)
			fmt.Fprintf(&b, "func (c *Chain) %s(%s) *Chain {\n", methodName, strings.Join(paramSig, ", "))
			fmt.Fprintf(&b, "\treturn c.add(\"%s\", %s)\n", op.name, strings.Join(paramArgs, ", "))
			fmt.Fprintf(&b, "}\n\n")
		}
	}

	return b.String()
}

func generatePython(m *Manifest) string {
	var b strings.Builder
	b.WriteString("# Code generated by cmd/generate; DO NOT EDIT.\n\n")
	b.WriteString("from __future__ import annotations\n")
	b.WriteString("from typing import TYPE_CHECKING\n\n")
	b.WriteString("if TYPE_CHECKING:\n")
	b.WriteString("    from .pipeline import Pipeline\n\n\n")
	b.WriteString("class Chain:\n")
	b.WriteString("    \"\"\"Fluent image processing chain. Create via Pipeline.read().\"\"\"\n\n")
	b.WriteString("    def __init__(self, pipe: 'Pipeline', input_bytes: bytes) -> None:\n")
	b.WriteString("        self._pipe = pipe\n")
	b.WriteString("        self._input = input_bytes\n")
	b.WriteString("        self._ops: list[dict] = []\n\n")
	b.WriteString("    def _add(self, name: str, *params: float) -> 'Chain':\n")
	b.WriteString("        self._ops.append({'name': name, 'params': list(params)})\n")
	b.WriteString("        return self\n\n")

	// Write terminal methods
	b.WriteString("    def write_png(self) -> bytes:\n")
	b.WriteString("        \"\"\"Encode result as PNG.\"\"\"\n")
	b.WriteString("        return self._pipe.process_chain(self._input, self._ops, 'png')\n\n")
	b.WriteString("    def write_jpeg(self, quality: int = 85) -> bytes:\n")
	b.WriteString("        \"\"\"Encode result as JPEG.\"\"\"\n")
	b.WriteString("        return self._pipe.process_chain(self._input, self._ops, 'jpeg', quality)\n\n")
	b.WriteString("    def write_webp(self, quality: int = 80) -> bytes:\n")
	b.WriteString("        \"\"\"Encode result as WebP.\"\"\"\n")
	b.WriteString("        return self._pipe.process_chain(self._input, self._ops, 'webp', quality)\n\n")
	b.WriteString("    def write(self, fmt: str, quality: int | None = None) -> bytes:\n")
	b.WriteString("        \"\"\"Encode result in the specified format.\"\"\"\n")
	b.WriteString("        return self._pipe.process_chain(self._input, self._ops, fmt, quality)\n\n")

	// Collect all ops
	type entry struct {
		name   string
		params []Param
	}
	var ops []entry
	for _, t := range m.Transforms {
		if t.MultiInput {
			continue
		}
		ops = append(ops, entry{t.Name, t.Params})
	}
	for _, f := range m.Filters {
		ops = append(ops, entry{f.Name, f.Params})
	}
	for _, g := range m.Generators {
		ops = append(ops, entry{g.Name, g.Params})
	}
	for _, mp := range m.Mappers {
		ops = append(ops, entry{mp.Name, mp.Params})
	}

	for _, op := range ops {
		if len(op.params) == 0 {
			fmt.Fprintf(&b, "    def %s(self) -> 'Chain':\n", op.name)
			fmt.Fprintf(&b, "        \"\"\"Apply %s.\"\"\"\n", op.name)
			fmt.Fprintf(&b, "        return self._add('%s')\n\n", op.name)
		} else {
			var paramSig []string
			var paramArgs []string
			for _, p := range op.params {
				pyType := rustTypeToPython(p.Type)
				paramSig = append(paramSig, fmt.Sprintf("%s: %s", p.Name, pyType))
				paramArgs = append(paramArgs, p.Name)
			}
			fmt.Fprintf(&b, "    def %s(self, %s) -> 'Chain':\n", op.name, strings.Join(paramSig, ", "))
			fmt.Fprintf(&b, "        \"\"\"Apply %s.\"\"\"\n", op.name)
			fmt.Fprintf(&b, "        return self._add('%s', %s)\n\n", op.name, strings.Join(paramArgs, ", "))
		}
	}

	return b.String()
}
