//! Generate Rust filter adapter dispatch code.

use crate::types::{FilterReg, ParamField};
use std::collections::HashMap;

/// Generate the filter adapter impl block (filters::Guest for Component).
pub fn generate(filters: &[FilterReg], param_structs: &HashMap<String, Vec<ParamField>>) -> String {
    let mut code = String::new();
    code.push_str("// Auto-generated by rasmcore-codegen from #[register_filter] annotations.\n");
    code.push_str("// Do not edit — regenerate by changing filters.rs and rebuilding.\n\n");
    code.push_str("impl filters::Guest for Component {\n");

    for f in filters {
        let trait_method = &f.name;
        let domain_fn = &f.fn_name;

        if f.derive_style {
            // Derive-style filters: delegate to CpuFilter::compute() on a Default config
            generate_derive_style_method(&mut code, f, trait_method);
        } else if !f.params.is_empty() {
            // All filters with params use a single config record in WIT
            generate_config_method(&mut code, f, trait_method, domain_fn, param_structs);
        } else {
            // Zero-param filters
            generate_individual_method(&mut code, f, trait_method, domain_fn);
        }
    }

    code.push_str("}\n");
    code
}

fn generate_derive_style_method(
    code: &mut String,
    f: &FilterReg,
    trait_method: &str,
) {
    let config_type = f.config_struct.as_deref().unwrap_or("()");

    code.push_str(&format!(
        "    fn {trait_method}(pixels: Vec<u8>, info: types::ImageInfo) -> Result<Vec<u8>, RasmcoreError> {{\n"
    ));
    code.push_str("        let di = to_domain_image_info(&info);\n");
    code.push_str("        let full_rect = rasmcore_pipeline::Rect::new(0, 0, di.width, di.height);\n");
    code.push_str("        let mut upstream = |_rect: rasmcore_pipeline::Rect| -> Result<Vec<u8>, crate::domain::error::ImageError> { Ok(pixels.clone()) };\n");
    code.push_str("        use crate::domain::filter_traits::CpuFilter;\n");
    code.push_str(&format!(
        "        let cfg = crate::domain::filters::{config_type}::default();\n"
    ));
    code.push_str("        cfg.compute(full_rect, &mut upstream, &di).map_err(to_wit_error)\n");
    code.push_str("    }\n\n");
}

fn generate_config_method(
    code: &mut String,
    f: &FilterReg,
    trait_method: &str,
    domain_fn: &str,
    param_structs: &HashMap<String, Vec<ParamField>>,
) {
    let wit_config_type = format!("filters::{}Config", super::helpers::to_pascal_case(&f.name));
    let qualified = super::helpers::to_qualified_binding_type;

    // All params come from a single WIT config record (if any params exist)
    let mut call_params = Vec::new();
    let mut body_lines = Vec::new();
    let has_any_params = !f.params.is_empty();

    // Config struct field names — skip extra params already in the struct
    let config_field_names: std::collections::HashSet<String> = f.params.iter()
        .filter(|(_n, t)| t.starts_with('&') && t.ends_with("Params"))
        .flat_map(|(_n, t)| {
            let struct_name = &t[1..];
            param_structs.get(struct_name)
                .map(|fields| fields.iter().map(|f| f.name.trim_start_matches('_').to_string()).collect::<Vec<_>>())
                .unwrap_or_default()
        })
        .collect();

    for (n, t) in &f.params {
        let clean_n = n.trim_start_matches('_');
        if t.starts_with('&') && t.ends_with("Params") {
            let struct_name = &t[1..];
            let domain_type = qualified(t);
            if let Some(fields) = param_structs.get(struct_name) {
                let field_inits: Vec<String> = fields
                    .iter()
                    .map(|field| {
                        let fname = field.name.trim_start_matches('_');
                        let nested = param_structs.get(&field.param_type);
                        if let Some(nested_fields) = nested {
                            let nested_type = qualified(&field.param_type);
                            let nested_inits: Vec<String> = nested_fields
                                .iter()
                                .map(|nf| {
                                    let nfname = nf.name.trim_start_matches('_');
                                    format!("                {nfname}: wit_config.{fname}.{nfname}")
                                })
                                .collect();
                            format!(
                                "            {fname}: {nested_type} {{\n{}\n            }}",
                                nested_inits.join(",\n")
                            )
                        } else {
                            format!("            {fname}: wit_config.{fname}")
                        }
                    })
                    .collect();
                body_lines.push(format!(
                    "        let domain_config = {domain_type} {{\n{}\n        }};",
                    field_inits.join(",\n")
                ));
            }
            call_params.push("&domain_config".to_string());
        } else {
            // Extra param — extract from config record
            let needs_clone = config_field_names.contains(clean_n);
            let accessor = if needs_clone {
                format!("wit_config.{clean_n}.clone()")
            } else {
                format!("wit_config.{clean_n}")
            };
            let call_expr = match t.as_str() {
                "&[f32]" | "&[f64]" | "&[u8]" | "&[u32]" => {
                    body_lines.push(format!("        let {clean_n} = {accessor};"));
                    format!("&{clean_n}")
                }
                "&[Point2D]" => {
                    body_lines.push(format!(
                        "        let {clean_n}_domain: Vec<crate::domain::param_types::Point2D> = {accessor}.iter().map(|p| crate::domain::param_types::Point2D {{ x: p.x, y: p.y }}).collect();"
                    ));
                    format!("&{clean_n}_domain")
                }
                "&str" => {
                    body_lines.push(format!("        let {clean_n} = {accessor};"));
                    format!("&{clean_n}")
                }
                "String" => {
                    body_lines.push(format!("        let {clean_n} = {accessor};"));
                    clean_n.to_string()
                }
                _ => {
                    body_lines.push(format!("        let {clean_n} = {accessor};"));
                    clean_n.to_string()
                }
            };
            call_params.push(call_expr);
        }
    }

    let mut sig_parts = vec![
        "pixels: Vec<u8>".to_string(),
        "info: types::ImageInfo".to_string(),
    ];
    if has_any_params {
        sig_parts.push(format!("wit_config: {wit_config_type}"));
    }

    code.push_str(&format!(
        "    fn {trait_method}({}) -> Result<Vec<u8>, RasmcoreError> {{\n",
        sig_parts.join(", ")
    ));
    code.push_str("        let di = to_domain_image_info(&info);\n");
    for line in &body_lines {
        code.push_str(line);
        code.push('\n');
    }

    let extra_call = if call_params.is_empty() {
        String::new()
    } else {
        format!(", {}", call_params.join(", "))
    };
    code.push_str(
        "        let full_rect = rasmcore_pipeline::Rect::new(0, 0, di.width, di.height);\n",
    );
    code.push_str("        let mut upstream = |_rect: rasmcore_pipeline::Rect| -> Result<Vec<u8>, crate::domain::error::ImageError> { Ok(pixels.clone()) };\n");
    code.push_str(&format!(
        "        domain::filters::{domain_fn}(full_rect, &mut upstream, &di{extra_call}).map_err(to_wit_error)\n"
    ));
    code.push_str("    }\n\n");
}

fn generate_individual_method(
    code: &mut String,
    f: &FilterReg,
    trait_method: &str,
    domain_fn: &str,
) {
    let mut sig_params = Vec::new();
    let mut call_params = Vec::new();
    for (n, t) in &f.params {
        let clean_n = n.trim_start_matches('_');
        let (binding_type, call_expr) = match t.as_str() {
            "&[f32]" => ("Vec<f32>", format!("&{clean_n}")),
            "&[f64]" => ("Vec<f64>", format!("&{clean_n}")),
            "&[u8]" => ("Vec<u8>", format!("&{clean_n}")),
            "&[u32]" => ("Vec<u32>", format!("&{clean_n}")),
            "&[Point2D]" => ("Vec<Point2D>", format!("&{clean_n}")),
            "&str" => ("String", format!("&{clean_n}")),
            "String" => ("String", clean_n.to_string()),
            _ => (t.as_str(), clean_n.to_string()),
        };
        sig_params.push(format!("{clean_n}: {binding_type}"));
        call_params.push(call_expr);
    }

    let full_sig = if sig_params.is_empty() {
        "pixels: Vec<u8>, info: types::ImageInfo".to_string()
    } else {
        format!(
            "pixels: Vec<u8>, info: types::ImageInfo, {}",
            sig_params.join(", ")
        )
    };

    code.push_str(&format!(
        "    fn {trait_method}({full_sig}) -> Result<Vec<u8>, RasmcoreError> {{\n"
    ));
    code.push_str("        let di = to_domain_image_info(&info);\n");

    let extra_call = if call_params.is_empty() {
        String::new()
    } else {
        format!(", {}", call_params.join(", "))
    };
    code.push_str(
        "        let full_rect = rasmcore_pipeline::Rect::new(0, 0, di.width, di.height);\n",
    );
    code.push_str("        let mut upstream = |_rect: rasmcore_pipeline::Rect| -> Result<Vec<u8>, crate::domain::error::ImageError> { Ok(pixels.clone()) };\n");
    code.push_str(&format!(
        "        domain::filters::{domain_fn}(full_rect, &mut upstream, &di{extra_call}).map_err(to_wit_error)\n"
    ));
    code.push_str("    }\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_adapter_basic() {
        let filters = vec![FilterReg {
            name: "blur".to_string(),
            category: "spatial".to_string(),
            group: String::new(),
            variant: String::new(),
            reference: String::new(),
            fn_name: "blur".to_string(),
            params: vec![("radius".to_string(), "f32".to_string())],
            config_struct: None,
            point_op: false,
            color_op: false,
            rect_request: true,
        }];
        let code = generate(&filters, &HashMap::new());
        assert!(code.contains("fn blur("));
        assert!(code.contains("radius: f32"));
        // rect-request style: full_rect + upstream closure
        assert!(code.contains("domain::filters::blur(full_rect, &mut upstream, &di, radius)"));
    }

    #[test]
    fn generate_adapter_slice_params() {
        let filters = vec![FilterReg {
            name: "test".to_string(),
            category: "test".to_string(),
            group: String::new(),
            variant: String::new(),
            reference: String::new(),
            fn_name: "test".to_string(),
            params: vec![("data".to_string(), "&[u8]".to_string())],
            config_struct: None,
            point_op: false,
            color_op: false,
            rect_request: true,
        }];
        let code = generate(&filters, &HashMap::new());
        assert!(code.contains("data: Vec<u8>"));
        assert!(code.contains("&data"));
    }

    #[test]
    fn generate_adapter_config_struct() {
        let filters = vec![FilterReg {
            name: "blur".to_string(),
            category: "spatial".to_string(),
            group: String::new(),
            variant: String::new(),
            reference: String::new(),
            fn_name: "blur".to_string(),
            params: vec![("radius".to_string(), "f32".to_string())],
            config_struct: Some("BlurParams".to_string()),
            point_op: false,
            color_op: false,
            rect_request: true,
        }];
        let code = generate(&filters, &HashMap::new());
        assert!(
            code.contains("config: filters::BlurConfig"),
            "should use config struct param: {code}"
        );
        assert!(
            code.contains("config.radius"),
            "should destructure config: {code}"
        );
        assert!(
            !code.contains("radius: f32"),
            "should NOT have individual param: {code}"
        );
    }
}
