//! Rust native SDK generator — fluent builder API wrapping domain functions.
//!
//! Generates a `RcImage` struct with chainable methods for all registered filters.
//! No WASM overhead — direct Rust linking to rasmcore-image domain.

use crate::types::FilterReg;

/// Generate the Rust SDK source code.
pub fn generate(filters: &[FilterReg]) -> String {
    let mut code = String::with_capacity(32 * 1024);

    // Module header — outer doc comments only (inner not allowed in include!)
    code.push_str("// Auto-generated Rust native SDK — fluent builder API.\n");
    code.push_str("// Do not edit manually. Regenerated by rasmcore-codegen.\n\n");
    code.push_str("use rasmcore_image::domain::{decoder, encoder, filters};\n");
    code.push_str("use rasmcore_image::domain::filters::*; // ConfigParams structs\n\n");

    // RcImage struct
    code.push_str("/// An image with a fluent processing API.\n");
    code.push_str("///\n");
    code.push_str(
        "/// Chain filter/transform methods and finalize with `to_jpeg()`, `to_png()`, etc.\n",
    );
    code.push_str("pub struct RcImage {\n");
    code.push_str("    pixels: Vec<u8>,\n");
    code.push_str("    info: ImageInfo,\n");
    code.push_str("}\n\n");

    // Constructor methods
    code.push_str("impl RcImage {\n");
    code.push_str("    /// Load an image from encoded bytes (auto-detects format).\n");
    code.push_str("    pub fn load(data: &[u8]) -> Result<Self, ImageError> {\n");
    code.push_str("        let decoded = decoder::decode(data)?;\n");
    code.push_str("        Ok(Self {\n");
    code.push_str("            pixels: decoded.pixels,\n");
    code.push_str("            info: decoded.info,\n");
    code.push_str("        })\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Create from raw pixels and info.\n");
    code.push_str("    pub fn from_raw(pixels: Vec<u8>, info: ImageInfo) -> Self {\n");
    code.push_str("        Self { pixels, info }\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Get image dimensions.\n");
    code.push_str("    pub fn dimensions(&self) -> (u32, u32) {\n");
    code.push_str("        (self.info.width, self.info.height)\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Get image info.\n");
    code.push_str("    pub fn info(&self) -> &ImageInfo {\n");
    code.push_str("        &self.info\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Get raw pixel data.\n");
    code.push_str("    pub fn pixels(&self) -> &[u8] {\n");
    code.push_str("        &self.pixels\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Consume and return raw pixels + info.\n");
    code.push_str("    pub fn into_raw(self) -> (Vec<u8>, ImageInfo) {\n");
    code.push_str("        (self.pixels, self.info)\n");
    code.push_str("    }\n\n");

    // Encode methods
    code.push_str("    /// Encode as JPEG.\n");
    code.push_str("    pub fn to_jpeg(&self, quality: u8) -> Result<Vec<u8>, ImageError> {\n");
    code.push_str("        encoder::encode(&self.pixels, &self.info, \"jpeg\", Some(quality))\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Encode as PNG.\n");
    code.push_str("    pub fn to_png(&self) -> Result<Vec<u8>, ImageError> {\n");
    code.push_str("        encoder::encode(&self.pixels, &self.info, \"png\", None)\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Encode as WebP.\n");
    code.push_str("    pub fn to_webp(&self, quality: u8) -> Result<Vec<u8>, ImageError> {\n");
    code.push_str("        encoder::encode(&self.pixels, &self.info, \"webp\", Some(quality))\n");
    code.push_str("    }\n\n");

    code.push_str("    /// Encode to any supported format.\n");
    code.push_str("    pub fn encode(&self, format: &str, quality: Option<u8>) -> Result<Vec<u8>, ImageError> {\n");
    code.push_str("        encoder::encode(&self.pixels, &self.info, format, quality)\n");
    code.push_str("    }\n\n");

    // Transform methods
    code.push_str("    // ─── Transforms ───\n\n");

    // Note: transforms use domain types directly (not generated from FilterReg).
    // These are hand-written wrappers using the public API.

    // Filter methods — generated from FilterReg
    code.push_str("    // ─── Filters (auto-generated) ───\n\n");

    for filter in filters {
        let method_name = &filter.fn_name;
        let params = &filter.params;

        // Build method signature params
        let method_params: Vec<String> = params
            .iter()
            .map(|(name, ty)| format!("{name}: {ty}"))
            .collect();

        // Build call args
        let call_args: Vec<String> = params.iter().map(|(name, _)| name.clone()).collect();

        let sig_params = if method_params.is_empty() {
            String::new()
        } else {
            format!(", {}", method_params.join(", "))
        };

        let call_args_str = if call_args.is_empty() {
            String::new()
        } else {
            format!(", {}", call_args.join(", "))
        };

        // Doc comment with reference
        code.push_str(&format!("    /// {}", filter.name.replace('_', " ")));
        if !filter.reference.is_empty() {
            code.push_str(&format!(" ({})", filter.reference));
        }
        code.push_str(".\n");

        code.push_str(&format!(
            "    pub fn {method_name}(self{sig_params}) -> Result<Self, ImageError> {{\n"
        ));
        code.push_str(&format!(
            "        let pixels = filters::{method_name}(&self.pixels, &self.info{call_args_str})?;\n"
        ));
        code.push_str("        Ok(Self { pixels, info: self.info })\n");
        code.push_str("    }\n\n");
    }

    code.push_str("}\n");

    code
}
