use image::ImageFormat;

use super::color;
use super::error::ImageError;
use super::types::{ColorSpace, DecodedImage, ImageInfo, PixelFormat};

// ─── Static Registration (for proc macro + inventory) ─────────────────────

/// Static decoder registration metadata — generated by `#[register_decoder]`.
#[derive(Debug)]
pub struct StaticDecoderRegistration {
    pub name: &'static str,
    pub formats: &'static str,
    pub fn_name: &'static str,
}

inventory::collect!(&'static StaticDecoderRegistration);

/// List all registered decoders (from all linked crates).
pub fn registered_decoders() -> Vec<&'static StaticDecoderRegistration> {
    inventory::iter::<&'static StaticDecoderRegistration>
        .into_iter()
        .copied()
        .collect()
}

/// Supported decode formats
const SUPPORTED_FORMATS: &[&str] = &[
    "png", "jpeg", "gif", "webp", "bmp", "tiff", "qoi", "ico", "tga", "hdr", "pnm", "exr", "dds",
    "jxl", "jp2", "heic", "fits", "svg",
];

/// Detect image format from header bytes
pub fn detect_format(header: &[u8]) -> Option<String> {
    // Check formats not supported by image crate first
    if is_jxl(header) {
        return Some("jxl".to_string());
    }
    if is_jp2(header) {
        return Some("jp2".to_string());
    }
    #[cfg(feature = "native-heif")]
    if is_heif(header) {
        return Some("heic".to_string());
    }
    if rasmcore_fits::is_fits(header) {
        return Some("fits".to_string());
    }
    if is_svg(header) {
        return Some("svg".to_string());
    }
    image::guess_format(header)
        .ok()
        .and_then(|fmt| format_to_str(fmt))
        .map(String::from)
}

/// Check if data starts with a HEIF/HEIC/AVIF ftyp box with a recognized brand.
#[cfg(feature = "native-heif")]
fn is_heif(header: &[u8]) -> bool {
    rasmcore_isobmff::detect(header).is_some()
}

/// Check if data starts with JPEG 2000 magic bytes.
/// JP2 container: 0x00 0x00 0x00 0x0C 0x6A 0x50 0x20 0x20 (JP2 signature box)
/// J2K codestream: 0xFF 0x4F (SOC marker)
fn is_jp2(header: &[u8]) -> bool {
    // JP2 container signature
    if header.len() >= 12 && header[..4] == [0x00, 0x00, 0x00, 0x0C] && &header[4..8] == b"jP  " {
        return true;
    }
    // Raw J2K codestream (SOC marker)
    if header.len() >= 2 && header[0] == 0xFF && header[1] == 0x4F {
        return true;
    }
    false
}

/// Check if data starts with JPEG XL magic bytes.
/// Bare codestream: 0xFF 0x0A
/// ISOBMFF container: 0x00 0x00 0x00 0x0C 0x4A 0x58 0x4C 0x20 ("....JXL ")
fn is_jxl(header: &[u8]) -> bool {
    if header.len() >= 2 && header[0] == 0xFF && header[1] == 0x0A {
        return true;
    }
    if header.len() >= 12 && header[..4] == [0x00, 0x00, 0x00, 0x0C] && &header[4..8] == b"JXL " {
        return true;
    }
    false
}

/// Check if data starts with SVG content.
/// Matches XML prolog (`<?xml`) or direct `<svg` element, ignoring leading whitespace/BOM.
fn is_svg(header: &[u8]) -> bool {
    // Skip UTF-8 BOM if present
    let data = if header.starts_with(&[0xEF, 0xBB, 0xBF]) {
        &header[3..]
    } else {
        header
    };
    // Skip leading whitespace
    let trimmed = data
        .iter()
        .position(|&b| !b.is_ascii_whitespace())
        .map(|i| &data[i..])
        .unwrap_or(data);

    if trimmed.starts_with(b"<svg") || trimmed.starts_with(b"<SVG") {
        return true;
    }
    // XML prolog followed by svg element somewhere in the first 4KB
    if trimmed.starts_with(b"<?xml") {
        let check_len = trimmed.len().min(4096);
        let check = &trimmed[..check_len];
        // Look for <svg in the header region
        for w in check.windows(4) {
            if w == b"<svg" || w == b"<SVG" {
                return true;
            }
        }
    }
    false
}

/// Decode SVG to RGBA8 pixels using resvg.
fn decode_svg(data: &[u8]) -> Result<DecodedImage, ImageError> {
    let svg_str = std::str::from_utf8(data)
        .map_err(|e| ImageError::InvalidInput(format!("SVG: invalid UTF-8: {e}")))?;

    let tree = resvg::usvg::Tree::from_str(svg_str, &resvg::usvg::Options::default())
        .map_err(|e| ImageError::InvalidInput(format!("SVG parse error: {e}")))?;

    let size = tree.size();
    let width = size.width().ceil() as u32;
    let height = size.height().ceil() as u32;

    if width == 0 || height == 0 || width > 16384 || height > 16384 {
        return Err(ImageError::InvalidInput(format!(
            "SVG: invalid dimensions {width}x{height}"
        )));
    }

    let mut pixmap = resvg::tiny_skia::Pixmap::new(width, height)
        .ok_or_else(|| ImageError::ProcessingFailed("SVG: failed to create pixmap".into()))?;

    resvg::render(
        &tree,
        resvg::tiny_skia::Transform::default(),
        &mut pixmap.as_mut(),
    );

    // tiny-skia outputs premultiplied RGBA8 — demultiply alpha
    let pixels = pixmap
        .pixels()
        .iter()
        .flat_map(|px| {
            let r = px.red();
            let g = px.green();
            let b = px.blue();
            let a = px.alpha();
            if a == 0 {
                [0, 0, 0, 0]
            } else if a == 255 {
                [r, g, b, a]
            } else {
                // Demultiply: original = premultiplied * 255 / alpha
                [
                    ((r as u16 * 255 + a as u16 / 2) / a as u16) as u8,
                    ((g as u16 * 255 + a as u16 / 2) / a as u16) as u8,
                    ((b as u16 * 255 + a as u16 / 2) / a as u16) as u8,
                    a,
                ]
            }
        })
        .collect();

    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width,
            height,
            format: PixelFormat::Rgba8,
            color_space: ColorSpace::Srgb,
        },
        icc_profile: None,
    })
}

/// Decode an image from raw bytes
pub fn decode(data: &[u8]) -> Result<DecodedImage, ImageError> {
    // Formats not supported by image crate — handle first
    if is_jxl(data) {
        return decode_jxl(data);
    }
    if is_jp2(data) {
        return decode_jp2(data);
    }
    #[cfg(feature = "native-heif")]
    if is_heif(data) {
        return decode_heif(data);
    }
    if rasmcore_fits::is_fits(data) {
        return decode_fits(data);
    }
    if is_svg(data) {
        return decode_svg(data);
    }

    // JPEG — native decode via rasmcore-jpeg (always on)
    if data.len() >= 2 && data[0] == 0xFF && data[1] == 0xD8 {
        return decode_native_jpeg(data);
    }

    // Native trivial codecs — opt-in via feature flags, bypass image crate
    #[cfg(feature = "native-qoi")]
    if data.len() >= 4 && &data[..4] == b"qoif" {
        return decode_native_qoi(data);
    }
    #[cfg(feature = "native-bmp")]
    if data.len() >= 2 && &data[..2] == b"BM" {
        return decode_native_bmp(data);
    }
    #[cfg(feature = "native-pnm")]
    if data.len() >= 2 && (data[0] == b'P' && data[1].is_ascii_digit()) {
        return decode_native_pnm(data);
    }
    // TGA — native decode when feature enabled (TGA has no magic; detected after image crate)
    #[cfg(feature = "native-tga")]
    if detect_tga(data) {
        return decode_native_tga(data);
    }

    // TIFF — decode via tiff crate directly (dropped from image features)
    if data.len() >= 4
        && ((data[0] == b'I' && data[1] == b'I' && data[2] == 42 && data[3] == 0)
            || (data[0] == b'M' && data[1] == b'M' && data[2] == 0 && data[3] == 42))
    {
        return decode_tiff_native(data);
    }

    let img = image::load_from_memory(data).map_err(|e| ImageError::InvalidInput(e.to_string()))?;

    let format = detect_pixel_format(&img);
    let pixels = match format {
        PixelFormat::Rgba8 => img.to_rgba8().into_raw(),
        PixelFormat::Rgb8 => img.to_rgb8().into_raw(),
        PixelFormat::Gray8 => img.to_luma8().into_raw(),
        PixelFormat::Gray16 => img
            .to_luma16()
            .as_raw()
            .iter()
            .flat_map(|v| v.to_le_bytes())
            .collect(),
        PixelFormat::Rgb16 => img
            .to_rgb16()
            .as_raw()
            .iter()
            .flat_map(|v| v.to_le_bytes())
            .collect(),
        PixelFormat::Rgba16 => img
            .to_rgba16()
            .as_raw()
            .iter()
            .flat_map(|v| v.to_le_bytes())
            .collect(),
        _ => img.to_rgba8().into_raw(),
    };

    // Extract ICC profile from raw bytes (before the image crate strips metadata)
    let icc_profile = extract_icc_profile(data);

    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width: img.width(),
            height: img.height(),
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile,
    })
}

/// Extract ICC profile from raw image bytes based on detected format.
fn extract_icc_profile(data: &[u8]) -> Option<Vec<u8>> {
    match detect_format(data)?.as_str() {
        "jpeg" => color::extract_icc_from_jpeg(data),
        "png" => color::extract_icc_from_png(data),
        _ => None,
    }
}

/// Decode and convert to a specific pixel format
pub fn decode_as(data: &[u8], target_format: PixelFormat) -> Result<DecodedImage, ImageError> {
    // JP2/J2K: decode then convert if needed
    if is_jp2(data) {
        let decoded = decode_jp2(data)?;
        if decoded.info.format == target_format {
            return Ok(decoded);
        }
        let img = crate::domain::encoder::pixels_to_dynamic_image(&decoded.pixels, &decoded.info)?;
        let (pixels, format) = match target_format {
            PixelFormat::Rgb8 => (img.to_rgb8().into_raw(), PixelFormat::Rgb8),
            PixelFormat::Rgba8 => (img.to_rgba8().into_raw(), PixelFormat::Rgba8),
            PixelFormat::Gray8 => (img.to_luma8().into_raw(), PixelFormat::Gray8),
            other => {
                return Err(ImageError::UnsupportedFormat(format!(
                    "conversion to {other:?} not supported"
                )));
            }
        };
        return Ok(DecodedImage {
            pixels,
            info: ImageInfo {
                width: decoded.info.width,
                height: decoded.info.height,
                format,
                color_space: decoded.info.color_space,
            },
            icc_profile: decoded.icc_profile,
        });
    }

    // SVG: decode then convert if needed
    if is_svg(data) {
        let decoded = decode_svg(data)?;
        if decoded.info.format == target_format {
            return Ok(decoded);
        }
        let img = crate::domain::encoder::pixels_to_dynamic_image(&decoded.pixels, &decoded.info)?;
        let (pixels, format) = match target_format {
            PixelFormat::Rgb8 => (img.to_rgb8().into_raw(), PixelFormat::Rgb8),
            PixelFormat::Rgba8 => (img.to_rgba8().into_raw(), PixelFormat::Rgba8),
            PixelFormat::Gray8 => (img.to_luma8().into_raw(), PixelFormat::Gray8),
            other => {
                return Err(ImageError::UnsupportedFormat(format!(
                    "SVG conversion to {other:?} not supported"
                )));
            }
        };
        return Ok(DecodedImage {
            pixels,
            info: ImageInfo {
                width: decoded.info.width,
                height: decoded.info.height,
                format,
                color_space: decoded.info.color_space,
            },
            icc_profile: decoded.icc_profile,
        });
    }

    // FITS: decode then convert
    if rasmcore_fits::is_fits(data) {
        let decoded = decode_fits(data)?;
        if decoded.info.format == target_format {
            return Ok(decoded);
        }
        let img = crate::domain::encoder::pixels_to_dynamic_image(&decoded.pixels, &decoded.info)?;
        let (pixels, format) = match target_format {
            PixelFormat::Rgb8 => (img.to_rgb8().into_raw(), PixelFormat::Rgb8),
            PixelFormat::Rgba8 => (img.to_rgba8().into_raw(), PixelFormat::Rgba8),
            PixelFormat::Gray8 => (img.to_luma8().into_raw(), PixelFormat::Gray8),
            other => {
                return Err(ImageError::UnsupportedFormat(format!(
                    "conversion to {other:?} not supported"
                )));
            }
        };
        return Ok(DecodedImage {
            pixels,
            info: ImageInfo {
                width: decoded.info.width,
                height: decoded.info.height,
                format,
                color_space: decoded.info.color_space,
            },
            icc_profile: decoded.icc_profile,
        });
    }

    // JXL: decode then convert
    if is_jxl(data) {
        let decoded = decode_jxl(data)?;
        // If already in target format, return as-is
        if decoded.info.format == target_format {
            return Ok(decoded);
        }
        // Otherwise, use image crate for format conversion
        let img = crate::domain::encoder::pixels_to_dynamic_image(&decoded.pixels, &decoded.info)?;
        let (pixels, format) = match target_format {
            PixelFormat::Rgb8 => (img.to_rgb8().into_raw(), PixelFormat::Rgb8),
            PixelFormat::Rgba8 => (img.to_rgba8().into_raw(), PixelFormat::Rgba8),
            PixelFormat::Gray8 => (img.to_luma8().into_raw(), PixelFormat::Gray8),
            other => {
                return Err(ImageError::UnsupportedFormat(format!(
                    "conversion to {other:?} not supported"
                )));
            }
        };
        return Ok(DecodedImage {
            pixels,
            info: ImageInfo {
                width: decoded.info.width,
                height: decoded.info.height,
                format,
                color_space: decoded.info.color_space,
            },
            icc_profile: decoded.icc_profile,
        });
    }

    // JPEG — use native decoder, then convert format
    if data.len() >= 2 && data[0] == 0xFF && data[1] == 0xD8 {
        let decoded = decode_native_jpeg(data)?;
        if decoded.info.format == target_format {
            return Ok(decoded);
        }
        let img = crate::domain::encoder::pixels_to_dynamic_image(&decoded.pixels, &decoded.info)?;
        let (pixels, format) = match target_format {
            PixelFormat::Rgb8 => (img.to_rgb8().into_raw(), PixelFormat::Rgb8),
            PixelFormat::Rgba8 => (img.to_rgba8().into_raw(), PixelFormat::Rgba8),
            PixelFormat::Gray8 => (img.to_luma8().into_raw(), PixelFormat::Gray8),
            other => {
                return Err(ImageError::UnsupportedFormat(format!(
                    "conversion to {other:?} not supported"
                )));
            }
        };
        return Ok(DecodedImage {
            pixels,
            info: ImageInfo {
                width: decoded.info.width,
                height: decoded.info.height,
                format,
                color_space: decoded.info.color_space,
            },
            icc_profile: decoded.icc_profile,
        });
    }

    let img = image::load_from_memory(data).map_err(|e| ImageError::InvalidInput(e.to_string()))?;

    let (pixels, format) = match target_format {
        PixelFormat::Rgb8 => (img.to_rgb8().into_raw(), PixelFormat::Rgb8),
        PixelFormat::Rgba8 => (img.to_rgba8().into_raw(), PixelFormat::Rgba8),
        PixelFormat::Gray8 => (img.to_luma8().into_raw(), PixelFormat::Gray8),
        PixelFormat::Gray16 => {
            let luma16 = img.to_luma16();
            let bytes = luma16
                .as_raw()
                .iter()
                .flat_map(|v| v.to_le_bytes())
                .collect();
            (bytes, PixelFormat::Gray16)
        }
        other => {
            return Err(ImageError::UnsupportedFormat(format!(
                "conversion to {other:?} not supported"
            )));
        }
    };

    let icc_profile = extract_icc_profile(data);

    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width: img.width(),
            height: img.height(),
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile,
    })
}

/// List supported decode formats
pub fn supported_formats() -> Vec<String> {
    SUPPORTED_FORMATS.iter().map(|s| String::from(*s)).collect()
}

fn detect_pixel_format(img: &image::DynamicImage) -> PixelFormat {
    match img.color() {
        image::ColorType::Rgb8 => PixelFormat::Rgb8,
        image::ColorType::Rgba8 => PixelFormat::Rgba8,
        image::ColorType::L8 => PixelFormat::Gray8,
        image::ColorType::L16 => PixelFormat::Gray16,
        image::ColorType::Rgb16 => PixelFormat::Rgb16,
        image::ColorType::Rgba16 => PixelFormat::Rgba16,
        image::ColorType::La16 => PixelFormat::Rgba16, // promote LA16 to RGBA16
        _ => PixelFormat::Rgba8,
    }
}

/// Decode a JPEG 2000 image using justjp2.
fn decode_jp2(data: &[u8]) -> Result<DecodedImage, ImageError> {
    let image =
        justjp2::decode(data).map_err(|e| ImageError::InvalidInput(format!("JP2 decode: {e}")))?;

    let width = image.width;
    let height = image.height;
    let num_components = image.components.len();
    let num_pixels = (width * height) as usize;

    // justjp2 returns separate i32 component planes — interleave to u8
    let (pixels, format) = match num_components {
        1 => {
            // Grayscale
            let comp = &image.components[0];
            let precision = comp.precision;
            let pixels: Vec<u8> = comp
                .data
                .iter()
                .map(|&v| clamp_to_u8(v, precision))
                .collect();
            (pixels, PixelFormat::Gray8)
        }
        3 => {
            // RGB (or YCbCr already converted by justjp2)
            let mut pixels = Vec::with_capacity(num_pixels * 3);
            let precision = image.components[0].precision;
            for i in 0..num_pixels {
                pixels.push(clamp_to_u8(image.components[0].data[i], precision));
                pixels.push(clamp_to_u8(image.components[1].data[i], precision));
                pixels.push(clamp_to_u8(image.components[2].data[i], precision));
            }
            (pixels, PixelFormat::Rgb8)
        }
        4 => {
            // RGBA
            let mut pixels = Vec::with_capacity(num_pixels * 4);
            let precision = image.components[0].precision;
            for i in 0..num_pixels {
                pixels.push(clamp_to_u8(image.components[0].data[i], precision));
                pixels.push(clamp_to_u8(image.components[1].data[i], precision));
                pixels.push(clamp_to_u8(image.components[2].data[i], precision));
                pixels.push(clamp_to_u8(image.components[3].data[i], precision));
            }
            (pixels, PixelFormat::Rgba8)
        }
        _ => {
            return Err(ImageError::UnsupportedFormat(format!(
                "JP2 with {num_components} components not supported"
            )));
        }
    };

    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width,
            height,
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile: None,
    })
}

/// Clamp an i32 sample to u8 range, handling different bit precisions.
fn clamp_to_u8(value: i32, precision: u32) -> u8 {
    if precision <= 8 {
        value.clamp(0, 255) as u8
    } else {
        // Scale down from higher precision (e.g., 12-bit → 8-bit)
        let max = (1i32 << precision) - 1;
        (value.clamp(0, max) as u64 * 255 / max as u64) as u8
    }
}

/// Decode a JPEG XL image using jxl-oxide.
fn decode_jxl(data: &[u8]) -> Result<DecodedImage, ImageError> {
    use jxl_oxide::JxlImage;

    let image = JxlImage::builder()
        .read(std::io::Cursor::new(data))
        .map_err(|e| ImageError::InvalidInput(format!("JXL decode: {e}")))?;

    let width = image.width();
    let height = image.height();
    let render = image
        .render_frame(0)
        .map_err(|e| ImageError::ProcessingFailed(format!("JXL render: {e}")))?;

    // Get interleaved pixel buffer (f32) and convert to u8
    let fb = render.image_all_channels();
    let channels = fb.channels();
    let float_buf = fb.buf();
    let pixels: Vec<u8> = float_buf
        .iter()
        .map(|&v| (v.clamp(0.0, 1.0) * 255.0 + 0.5) as u8)
        .collect();

    let format = match channels {
        1 => PixelFormat::Gray8,
        3 => PixelFormat::Rgb8,
        4 => PixelFormat::Rgba8,
        _ => PixelFormat::Rgba8,
    };

    // Extract ICC profile if present
    let icc_profile = image.original_icc().map(|icc| icc.to_vec());

    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width,
            height,
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile,
    })
}

/// Decode a HEIF/HEIC file using rasmcore-isobmff container parser.
///
/// Currently parses the container and extracts metadata. Pixel decoding requires
/// the HEVC decoder (nonfree-hevc feature) which is not yet implemented.
/// Returns metadata-only result with dimensions and codec info.
#[cfg(feature = "native-heif")]
fn decode_heif(data: &[u8]) -> Result<DecodedImage, ImageError> {
    let file = rasmcore_isobmff::parse(data)
        .map_err(|e| ImageError::InvalidInput(format!("HEIF parse: {e}")))?;

    let img = &file.primary_image;

    // Attempt pixel decode based on codec type
    match img.codec {
        #[cfg(feature = "nonfree-hevc")]
        rasmcore_isobmff::CodecType::Hevc => decode_heif_hevc(&file),

        rasmcore_isobmff::CodecType::Av1 => {
            // AVIF-in-HEIF: delegate to existing AVIF decode path via image crate
            Err(ImageError::UnsupportedFormat(
                "AVIF-in-HEIF: use native AVIF decode path instead".into(),
            ))
        }

        _ => {
            let codec_name = match img.codec {
                rasmcore_isobmff::CodecType::Hevc => "HEVC",
                rasmcore_isobmff::CodecType::Av1 => "AV1",
                rasmcore_isobmff::CodecType::Jpeg => "JPEG",
                rasmcore_isobmff::CodecType::Unknown(_) => "unknown",
            };

            #[cfg(not(feature = "nonfree-hevc"))]
            if matches!(img.codec, rasmcore_isobmff::CodecType::Hevc) {
                return Err(ImageError::UnsupportedFormat(format!(
                    "HEIF container parsed ({}x{}, codec: HEVC, {} bytes) — \
                     enable the 'nonfree-hevc' feature to decode HEVC content",
                    img.width,
                    img.height,
                    img.bitstream.len()
                )));
            }

            Err(ImageError::UnsupportedFormat(format!(
                "HEIF codec {codec_name} not supported",
            )))
        }
    }
}

/// Decode HEIC file using rasmcore-hevc (nonfree).
#[cfg(all(feature = "native-heif", feature = "nonfree-hevc"))]
fn decode_heif_hevc(file: &rasmcore_isobmff::IsobmffFile) -> Result<DecodedImage, ImageError> {
    let img = &file.primary_image;

    // Handle grid images (multiple tiles composited)
    if let Some(grid) = &img.grid {
        return decode_heif_grid(grid, img);
    }

    // Single image decode
    let frame = rasmcore_hevc::decode_frame(&img.bitstream, None)
        .map_err(|e| ImageError::ProcessingFailed(format!("HEVC decode: {e}")))?;

    let icc_profile = img.icc_profile.clone();

    Ok(DecodedImage {
        pixels: frame.pixels,
        info: ImageInfo {
            width: frame.width,
            height: frame.height,
            format: PixelFormat::Rgb8,
            color_space: ColorSpace::Srgb,
        },
        icc_profile,
    })
}

/// Decode a grid HEIC image (multiple tiles composited into one output).
#[cfg(all(feature = "native-heif", feature = "nonfree-hevc"))]
fn decode_heif_grid(
    grid: &rasmcore_isobmff::GridDescriptor,
    img: &rasmcore_isobmff::ImageItem,
) -> Result<DecodedImage, ImageError> {
    let out_w = grid.output_width as usize;
    let out_h = grid.output_height as usize;
    let mut output = vec![0u8; out_w * out_h * 3];

    let cols = grid.cols as usize;

    for (tile_idx, tile) in grid.tiles.iter().enumerate() {
        let tile_row = tile_idx / cols;
        let tile_col = tile_idx % cols;

        // Decode this tile
        let frame = rasmcore_hevc::decode_frame(&tile.bitstream, None).map_err(|e| {
            ImageError::ProcessingFailed(format!("HEVC tile {tile_idx} decode: {e}"))
        })?;

        let tw = frame.width as usize;
        let th = frame.height as usize;
        let tile_x = tile_col * tw;
        let tile_y = tile_row * th;

        // Blit tile into output buffer
        for row in 0..th {
            let out_y = tile_y + row;
            if out_y >= out_h {
                break;
            }
            let src_start = row * tw * 3;
            let src_end = src_start + tw.min(out_w - tile_x) * 3;
            let dst_start = (out_y * out_w + tile_x) * 3;
            let copy_len = src_end - src_start;
            if dst_start + copy_len <= output.len() {
                output[dst_start..dst_start + copy_len]
                    .copy_from_slice(&frame.pixels[src_start..src_end]);
            }
        }
    }

    Ok(DecodedImage {
        pixels: output,
        info: ImageInfo {
            width: grid.output_width,
            height: grid.output_height,
            format: PixelFormat::Rgb8,
            color_space: ColorSpace::Srgb,
        },
        icc_profile: img.icc_profile.clone(),
    })
}

// ─── Native Trivial Codec Decoders ─────────────────────────────────────────

#[cfg(feature = "native-qoi")]
fn decode_native_qoi(data: &[u8]) -> Result<DecodedImage, ImageError> {
    let (hdr, pixels) =
        rasmcore_qoi::decode(data).map_err(|e| ImageError::InvalidInput(format!("QOI: {e}")))?;
    let format = match hdr.channels {
        rasmcore_qoi::Channels::Rgba => PixelFormat::Rgba8,
        rasmcore_qoi::Channels::Rgb => PixelFormat::Rgb8,
    };
    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width: hdr.width,
            height: hdr.height,
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile: None,
    })
}

#[cfg(feature = "native-bmp")]
fn decode_native_bmp(data: &[u8]) -> Result<DecodedImage, ImageError> {
    let (hdr, mut pixels) =
        rasmcore_bmp::decode(data).map_err(|e| ImageError::InvalidInput(format!("BMP: {e}")))?;
    // Native BMP decoder may output RGBA8 even for 24-bit BMP (padding alpha).
    // Detect actual format from data size and strip alpha if BMP was 24-bit.
    let npixels = (hdr.width * hdr.height) as usize;
    let format = if pixels.len() == npixels * 4 && hdr.bits_per_pixel <= 24 {
        // Strip alpha channel — convert RGBA8 to RGB8
        let mut rgb = Vec::with_capacity(npixels * 3);
        for chunk in pixels.chunks_exact(4) {
            rgb.extend_from_slice(&chunk[..3]);
        }
        pixels = rgb;
        PixelFormat::Rgb8
    } else if pixels.len() == npixels * 4 {
        PixelFormat::Rgba8
    } else {
        PixelFormat::Rgb8
    };
    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width: hdr.width,
            height: hdr.height,
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile: None,
    })
}

#[cfg(feature = "native-pnm")]
fn decode_native_pnm(data: &[u8]) -> Result<DecodedImage, ImageError> {
    let (hdr, pixels) =
        rasmcore_pnm::decode(data).map_err(|e| ImageError::InvalidInput(format!("PNM: {e}")))?;
    let format = match hdr.depth {
        4 => PixelFormat::Rgba8,
        3 => PixelFormat::Rgb8,
        _ => PixelFormat::Gray8,
    };
    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width: hdr.width,
            height: hdr.height,
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile: None,
    })
}

/// Decode a FITS image using rasmcore-fits.
fn decode_fits(data: &[u8]) -> Result<DecodedImage, ImageError> {
    let (header, float_pixels) =
        rasmcore_fits::decode(data).map_err(|e| ImageError::InvalidInput(format!("FITS: {e}")))?;

    let pixels = rasmcore_fits::to_gray8(&float_pixels);

    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width: header.width,
            height: header.height,
            format: PixelFormat::Gray8,
            color_space: ColorSpace::Srgb,
        },
        icc_profile: None,
    })
}

/// Decode JPEG using rasmcore-jpeg (pure Rust, supports sequential/progressive/arithmetic).
fn decode_native_jpeg(data: &[u8]) -> Result<DecodedImage, ImageError> {
    // Extract ICC profile from APP2 markers before decoding pixels
    let icc_profile = extract_jpeg_icc_profile(data);

    let decoded =
        rasmcore_jpeg::decode(data).map_err(|e| ImageError::InvalidInput(format!("JPEG: {e}")))?;
    let format = match decoded.format {
        rasmcore_jpeg::PixelFormat::Rgb8 => PixelFormat::Rgb8,
        rasmcore_jpeg::PixelFormat::Gray8 => PixelFormat::Gray8,
        rasmcore_jpeg::PixelFormat::Rgba8 => PixelFormat::Rgba8,
    };
    Ok(DecodedImage {
        pixels: decoded.pixels,
        info: ImageInfo {
            width: decoded.width,
            height: decoded.height,
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile,
    })
}

/// Extract ICC profile from JPEG APP2 markers (ICC_PROFILE signature).
///
/// Handles multi-chunk profiles per the ICC spec: each APP2 marker contains
/// a chunk with sequence number and total count.
fn extract_jpeg_icc_profile(data: &[u8]) -> Option<Vec<u8>> {
    const ICC_SIG: &[u8] = b"ICC_PROFILE\0";
    let mut chunks: Vec<(u8, Vec<u8>)> = Vec::new();
    let mut pos = 2; // skip SOI

    while pos + 4 < data.len() {
        if data[pos] != 0xFF {
            pos += 1;
            continue;
        }
        let marker = data[pos + 1];
        if marker == 0xD9 {
            break; // EOI
        }
        if marker == 0x00 || marker == 0x01 || (0xD0..=0xD7).contains(&marker) {
            pos += 2;
            continue;
        }
        if pos + 4 > data.len() {
            break;
        }
        let seg_len = u16::from_be_bytes([data[pos + 2], data[pos + 3]]) as usize;
        if marker == 0xE2 && seg_len > ICC_SIG.len() + 4 {
            // APP2 marker — check for ICC_PROFILE signature
            let seg_start = pos + 4;
            if seg_start + ICC_SIG.len() + 2 <= data.len()
                && &data[seg_start..seg_start + ICC_SIG.len()] == ICC_SIG
            {
                let seq = data[seg_start + ICC_SIG.len()]; // chunk sequence (1-based)
                let _total = data[seg_start + ICC_SIG.len() + 1];
                let profile_data = &data[seg_start + ICC_SIG.len() + 2..pos + 2 + seg_len];
                chunks.push((seq, profile_data.to_vec()));
            }
        }
        pos += 2 + seg_len;
    }

    if chunks.is_empty() {
        return None;
    }

    // Sort by sequence number and concatenate
    chunks.sort_by_key(|(seq, _)| *seq);
    let profile: Vec<u8> = chunks.into_iter().flat_map(|(_, data)| data).collect();
    Some(profile)
}

/// Decode TIFF using the tiff crate directly (bypasses image crate).
fn decode_tiff_native(data: &[u8]) -> Result<DecodedImage, ImageError> {
    let cursor = std::io::Cursor::new(data);
    let mut decoder = tiff::decoder::Decoder::new(cursor)
        .map_err(|e| ImageError::InvalidInput(format!("TIFF: {e}")))?;
    let (width, height) = decoder
        .dimensions()
        .map_err(|e| ImageError::InvalidInput(format!("TIFF: {e}")))?;
    let color_type = decoder
        .colortype()
        .map_err(|e| ImageError::InvalidInput(format!("TIFF: {e}")))?;
    let result = decoder
        .read_image()
        .map_err(|e| ImageError::InvalidInput(format!("TIFF: {e}")))?;

    let (pixels, format) = match (color_type, result) {
        (tiff::ColorType::Gray(8), tiff::decoder::DecodingResult::U8(buf)) => {
            (buf, PixelFormat::Gray8)
        }
        (tiff::ColorType::Gray(16), tiff::decoder::DecodingResult::U16(buf)) => {
            let bytes: Vec<u8> = buf.iter().flat_map(|v| v.to_le_bytes()).collect();
            (bytes, PixelFormat::Gray16)
        }
        (tiff::ColorType::RGB(8), tiff::decoder::DecodingResult::U8(buf)) => {
            (buf, PixelFormat::Rgb8)
        }
        (tiff::ColorType::RGB(16), tiff::decoder::DecodingResult::U16(buf)) => {
            let bytes: Vec<u8> = buf.iter().flat_map(|v| v.to_le_bytes()).collect();
            (bytes, PixelFormat::Rgb16)
        }
        (tiff::ColorType::RGBA(8), tiff::decoder::DecodingResult::U8(buf)) => {
            (buf, PixelFormat::Rgba8)
        }
        (tiff::ColorType::RGBA(16), tiff::decoder::DecodingResult::U16(buf)) => {
            let bytes: Vec<u8> = buf.iter().flat_map(|v| v.to_le_bytes()).collect();
            (bytes, PixelFormat::Rgba16)
        }
        _ => {
            return Err(ImageError::UnsupportedFormat(format!(
                "TIFF color type {color_type:?} not supported"
            )));
        }
    };

    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width,
            height,
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile: None,
    })
}

/// Heuristic TGA detection (TGA has no magic bytes).
///
/// Checks header plausibility: valid image type, reasonable dimensions,
/// valid bit depth, and data length consistent with declared size.
#[cfg(feature = "native-tga")]
fn detect_tga(data: &[u8]) -> bool {
    if data.len() < 18 {
        return false;
    }
    let image_type = data[2];
    // Valid image types: 1,2,3 (raw) or 9,10,11 (RLE)
    if !matches!(image_type, 1 | 2 | 3 | 9 | 10 | 11) {
        return false;
    }
    let width = u16::from_le_bytes([data[12], data[13]]) as usize;
    let height = u16::from_le_bytes([data[14], data[15]]) as usize;
    let bpp = data[16];
    if width == 0 || height == 0 || !matches!(bpp, 8 | 16 | 24 | 32) {
        return false;
    }
    // Basic size plausibility
    let min_size = 18 + width * height * (bpp as usize / 8) / 4; // RLE can compress
    data.len() >= min_size.min(64)
}

#[cfg(feature = "native-tga")]
fn decode_native_tga(data: &[u8]) -> Result<DecodedImage, ImageError> {
    let (header, pixels) =
        rasmcore_tga::decode(data).map_err(|e| ImageError::InvalidInput(format!("TGA: {e}")))?;
    let channels = pixels.len() / (header.width as usize * header.height as usize);
    let format = match channels {
        4 => PixelFormat::Rgba8,
        3 => PixelFormat::Rgb8,
        1 => PixelFormat::Gray8,
        _ => {
            return Err(ImageError::UnsupportedFormat(format!(
                "TGA: unexpected {channels} channels"
            )));
        }
    };
    Ok(DecodedImage {
        pixels,
        info: ImageInfo {
            width: header.width as u32,
            height: header.height as u32,
            format,
            color_space: ColorSpace::Srgb,
        },
        icc_profile: None,
    })
}

fn format_to_str(fmt: ImageFormat) -> Option<&'static str> {
    match fmt {
        ImageFormat::Png => Some("png"),
        ImageFormat::Jpeg => Some("jpeg"),
        ImageFormat::Gif => Some("gif"),
        ImageFormat::WebP => Some("webp"),
        ImageFormat::Bmp => Some("bmp"),
        ImageFormat::Tiff => Some("tiff"),
        ImageFormat::Avif => Some("avif"),
        ImageFormat::Qoi => Some("qoi"),
        ImageFormat::Ico => Some("ico"),
        ImageFormat::Tga => Some("tga"),
        ImageFormat::Hdr => Some("hdr"),
        ImageFormat::Pnm => Some("pnm"),
        ImageFormat::OpenExr => Some("exr"),
        ImageFormat::Dds => Some("dds"),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_png(width: u32, height: u32) -> Vec<u8> {
        let img = image::RgbImage::from_fn(width, height, |x, y| {
            image::Rgb([(x % 256) as u8, (y % 256) as u8, 128])
        });
        let mut buf = Vec::new();
        let mut cursor = std::io::Cursor::new(&mut buf);
        img.write_to(&mut cursor, ImageFormat::Png).unwrap();
        buf
    }

    fn make_jpeg(width: u32, height: u32) -> Vec<u8> {
        let pixels: Vec<u8> = (0..width * height)
            .flat_map(|i| {
                let x = i % width;
                let y = i / width;
                [(x % 256) as u8, (y % 256) as u8, 128u8]
            })
            .collect();
        let info = ImageInfo {
            width,
            height,
            format: PixelFormat::Rgb8,
            color_space: ColorSpace::Srgb,
        };
        crate::domain::encoder::encode(&pixels, &info, "jpeg", Some(90)).unwrap()
    }

    #[test]
    fn detect_format_png() {
        let data = make_png(8, 8);
        assert_eq!(detect_format(&data), Some("png".to_string()));
    }

    #[test]
    fn detect_format_jpeg() {
        let data = make_jpeg(8, 8);
        assert_eq!(detect_format(&data), Some("jpeg".to_string()));
    }

    #[test]
    fn detect_format_empty() {
        assert_eq!(detect_format(&[]), None);
    }

    #[test]
    fn detect_format_garbage() {
        assert_eq!(detect_format(&[0xFF, 0x00, 0x42, 0x99]), None);
    }

    #[test]
    fn decode_png_returns_correct_dimensions() {
        let data = make_png(64, 32);
        let result = decode(&data).unwrap();
        assert_eq!(result.info.width, 64);
        assert_eq!(result.info.height, 32);
    }

    #[test]
    fn decode_png_returns_rgb8_format() {
        let data = make_png(8, 8);
        let result = decode(&data).unwrap();
        assert_eq!(result.info.format, PixelFormat::Rgb8);
    }

    #[test]
    fn decode_png_pixel_data_length_matches() {
        let data = make_png(10, 10);
        let result = decode(&data).unwrap();
        let expected_len = 10 * 10 * 3;
        assert_eq!(result.pixels.len(), expected_len);
    }

    #[test]
    fn decode_jpeg_returns_correct_dimensions() {
        let data = make_jpeg(100, 50);
        let result = decode(&data).unwrap();
        assert_eq!(result.info.width, 100);
        assert_eq!(result.info.height, 50);
    }

    #[test]
    fn decode_invalid_data_returns_error() {
        let result = decode(&[0x00, 0x01, 0x02]);
        assert!(result.is_err());
        match result.unwrap_err() {
            ImageError::InvalidInput(_) => {}
            other => panic!("expected InvalidInput, got {other:?}"),
        }
    }

    #[test]
    fn decode_as_rgba8() {
        let data = make_png(8, 8);
        let result = decode_as(&data, PixelFormat::Rgba8).unwrap();
        assert_eq!(result.info.format, PixelFormat::Rgba8);
        assert_eq!(result.pixels.len(), 8 * 8 * 4);
    }

    #[test]
    fn decode_as_gray8() {
        let data = make_png(8, 8);
        let result = decode_as(&data, PixelFormat::Gray8).unwrap();
        assert_eq!(result.info.format, PixelFormat::Gray8);
        assert_eq!(result.pixels.len(), 8 * 8 * 1);
    }

    #[test]
    fn decode_as_unsupported_returns_error() {
        let data = make_png(8, 8);
        let result = decode_as(&data, PixelFormat::Yuv420p);
        assert!(result.is_err());
        match result.unwrap_err() {
            ImageError::UnsupportedFormat(_) => {}
            other => panic!("expected UnsupportedFormat, got {other:?}"),
        }
    }

    #[test]
    fn supported_formats_includes_common_formats() {
        let fmts = supported_formats();
        for f in [
            "png", "jpeg", "webp", "gif", "bmp", "tiff", "qoi", "ico", "tga", "hdr", "pnm", "exr",
            "dds", "jxl", "jp2",
        ] {
            assert!(fmts.contains(&f.to_string()), "missing decode format: {f}");
        }
    }

    #[test]
    fn detect_format_jp2_container() {
        // JP2 signature: 0x00 0x00 0x00 0x0C "jP  " (with trailing spaces)
        let header = [
            0x00, 0x00, 0x00, 0x0C, 0x6A, 0x50, 0x20, 0x20, 0x0D, 0x0A, 0x87, 0x0A,
        ];
        assert_eq!(detect_format(&header), Some("jp2".to_string()));
    }

    #[test]
    fn detect_format_j2k_codestream() {
        // J2K SOC marker: 0xFF 0x4F
        assert_eq!(
            detect_format(&[0xFF, 0x4F, 0xFF, 0x51]),
            Some("jp2".to_string())
        );
    }

    #[test]
    fn detect_format_jxl_bare_codestream() {
        // JXL bare codestream starts with 0xFF 0x0A
        assert_eq!(
            detect_format(&[0xFF, 0x0A, 0x00, 0x00]),
            Some("jxl".to_string())
        );
    }

    #[test]
    fn detect_format_jxl_container() {
        // JXL ISOBMFF container: 0x00 0x00 0x00 0x0C "JXL " 0x0D 0x0A 0x87 0x0A
        let header = [
            0x00, 0x00, 0x00, 0x0C, 0x4A, 0x58, 0x4C, 0x20, 0x0D, 0x0A, 0x87, 0x0A,
        ];
        assert_eq!(detect_format(&header), Some("jxl".to_string()));
    }

    #[test]
    fn decode_color_space_defaults_to_srgb() {
        let data = make_png(8, 8);
        let result = decode(&data).unwrap();
        assert_eq!(result.info.color_space, ColorSpace::Srgb);
    }

    #[test]
    fn decode_png_no_icc_profile() {
        let data = make_png(8, 8);
        let result = decode(&data).unwrap();
        assert!(result.icc_profile.is_none());
    }

    #[test]
    fn decode_jpeg_no_icc_profile() {
        let data = make_jpeg(8, 8);
        let result = decode(&data).unwrap();
        assert!(result.icc_profile.is_none());
    }

    #[test]
    fn decode_jpeg_with_icc_extracts_profile() {
        let jpeg = make_jpeg(8, 8);
        // Embed a fake ICC profile into the JPEG
        let fake_icc = vec![42u8; 128];
        let jpeg_with_icc =
            crate::domain::encoder::jpeg::embed_icc_profile(&jpeg, &fake_icc).unwrap();
        let result = decode(&jpeg_with_icc).unwrap();
        assert_eq!(result.icc_profile, Some(fake_icc));
    }

    #[test]
    fn decode_png_with_icc_extracts_profile() {
        let png = make_png(8, 8);
        // Embed a fake ICC profile into the PNG
        let fake_icc = vec![99u8; 200];
        let png_with_icc = crate::domain::encoder::png::embed_icc_profile(&png, &fake_icc).unwrap();
        let result = decode(&png_with_icc).unwrap();
        assert_eq!(result.icc_profile, Some(fake_icc));
    }

    #[test]
    fn decode_as_preserves_icc_profile() {
        let jpeg = make_jpeg(8, 8);
        let fake_icc = vec![55u8; 64];
        let jpeg_with_icc =
            crate::domain::encoder::jpeg::embed_icc_profile(&jpeg, &fake_icc).unwrap();
        let result = decode_as(&jpeg_with_icc, PixelFormat::Rgba8).unwrap();
        assert_eq!(result.icc_profile, Some(fake_icc));
    }

    // ─── SVG Tests ─────────────────────────────────────────────────────────

    fn simple_svg() -> Vec<u8> {
        br#"<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32">
  <rect width="32" height="32" fill="red"/>
</svg>"#
            .to_vec()
    }

    fn complex_svg() -> Vec<u8> {
        br##"<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="64" height="48" viewBox="0 0 64 48">
  <defs>
    <linearGradient id="g1" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#ff0000"/>
      <stop offset="1" stop-color="#0000ff"/>
    </linearGradient>
  </defs>
  <rect width="64" height="48" fill="url(#g1)"/>
  <circle cx="32" cy="24" r="10" fill="white" opacity="0.8"/>
  <text x="10" y="40" font-size="8" fill="black">Hello</text>
</svg>"##
            .to_vec()
    }

    #[test]
    fn detect_format_svg_direct() {
        let svg = simple_svg();
        assert_eq!(detect_format(&svg), Some("svg".to_string()));
    }

    #[test]
    fn detect_format_svg_xml_prolog() {
        let svg = complex_svg();
        assert_eq!(detect_format(&svg), Some("svg".to_string()));
    }

    #[test]
    fn detect_format_svg_with_bom() {
        let mut svg = vec![0xEF, 0xBB, 0xBF]; // UTF-8 BOM
        svg.extend_from_slice(&simple_svg());
        assert_eq!(detect_format(&svg), Some("svg".to_string()));
    }

    #[test]
    fn decode_svg_simple_icon() {
        let svg = simple_svg();
        let result = decode(&svg).unwrap();
        assert_eq!(result.info.width, 32);
        assert_eq!(result.info.height, 32);
        assert_eq!(result.info.format, PixelFormat::Rgba8);
        assert_eq!(result.pixels.len(), 32 * 32 * 4);
        // First pixel should be red (R=255, G=0, B=0, A=255)
        assert_eq!(result.pixels[0], 255); // R
        assert_eq!(result.pixels[1], 0); // G
        assert_eq!(result.pixels[2], 0); // B
        assert_eq!(result.pixels[3], 255); // A
    }

    #[test]
    fn decode_svg_complex_gradients_text() {
        let svg = complex_svg();
        let result = decode(&svg).unwrap();
        assert_eq!(result.info.width, 64);
        assert_eq!(result.info.height, 48);
        assert_eq!(result.info.format, PixelFormat::Rgba8);
        assert_eq!(result.pixels.len(), 64 * 48 * 4);
        // Should have non-zero alpha (not empty)
        assert!(result.pixels.iter().any(|&b| b > 0));
    }

    #[test]
    fn decode_svg_as_rgb8() {
        let svg = simple_svg();
        let result = decode_as(&svg, PixelFormat::Rgb8).unwrap();
        assert_eq!(result.info.format, PixelFormat::Rgb8);
        assert_eq!(result.pixels.len(), 32 * 32 * 3);
    }

    #[test]
    fn supported_formats_includes_svg() {
        assert!(SUPPORTED_FORMATS.contains(&"svg"));
    }
}
