/**
 * @rasmcore/sdk — Image processing powered by WebAssembly.
 *
 * Two usage modes:
 *
 * Dynamic (works with any module, no codegen needed):
 *   import { RcImage } from '@rasmcore/sdk';
 *   const img = RcImage.load(wasmModule, pngBytes);
 *   const jpeg = img.apply('blur', { radius: 3.0 }).encode('jpeg', { quality: 85 });
 *
 * Typed (generated per-module, full autocomplete):
 *   import { RcImage } from './rasmcore-typed';  // generated by typegen
 *   const jpeg = RcImage.load(wasmModule, pngBytes).blur(3.0).toJpeg({ quality: 85 });
 */

export { RcImage } from './runtime.js';
export type {
  FilterManifest,
  OperationMeta,
  ParamMeta,
  WasmModule,
  WasmPipeline,
} from './types.js';
