// Package rasmcore provides a dynamic image processing SDK powered by WebAssembly.
//
// Load any rasmcore-compatible WASM module and apply filters, transforms,
// and encoders with full parameter validation via manifest introspection.
//
// Dynamic usage:
//
//	img, err := rasmcore.Load("rasmcore_image.wasm", pngData)
//	jpeg, err := img.Apply("blur", map[string]any{"radius": 3.0}).Encode("jpeg", nil)
//
// The runtime is module-agnostic — it works with any WASM component
// that exposes GetFilterManifest() and GetManifestHash().
package rasmcore

import (
	"encoding/json"
	"fmt"
	"strings"
	"unicode"
)

// RcImage is a dynamic image processing chain.
//
// Works with any rasmcore-compatible WASM module. Discovers available
// operations at load time via the module's embedded manifest.
//
// All operations are lazy — pixels are only computed when an Encode
// method is called.
type RcImage struct {
	pipeline       interface{} // The WASM pipeline instance (opaque)
	nodeID         int
	manifest       *FilterManifest
	manifestHash   string
	writeFormats   []string
	operationIndex map[string]*OperationMeta
	lastErr        error // sticky error for chaining
}

// Manifest returns the full manifest describing all operations this module supports.
func (r *RcImage) Manifest() *FilterManifest {
	return r.manifest
}

// ManifestHash returns the manifest content hash for SDK version validation.
func (r *RcImage) ManifestHash() string {
	return r.manifestHash
}

// WriteFormats returns available output formats.
func (r *RcImage) WriteFormats() []string {
	return r.writeFormats
}

// AvailableOperations returns all filter/operation names.
func (r *RcImage) AvailableOperations() []string {
	names := make([]string, 0, len(r.operationIndex))
	for name := range r.operationIndex {
		names = append(names, name)
	}
	return names
}

// OperationMeta returns metadata for a specific operation.
func (r *RcImage) OperationMeta(name string) *OperationMeta {
	return r.operationIndex[name]
}

// Err returns the first error encountered during chaining, if any.
func (r *RcImage) Err() error {
	return r.lastErr
}

// Fork branches the pipeline — returns a new RcImage sharing the same graph.
func (r *RcImage) Fork() *RcImage {
	return &RcImage{
		pipeline:       r.pipeline,
		nodeID:         r.nodeID,
		manifest:       r.manifest,
		manifestHash:   r.manifestHash,
		writeFormats:   r.writeFormats,
		operationIndex: r.operationIndex,
	}
}

// Apply dispatches a named operation with parameters.
//
// Parameters are passed as a map[string]any keyed by parameter name.
// Values are validated against the manifest metadata (types, ranges).
//
// Apply is chainable — errors are sticky and checked via Err() or
// at Encode() time.
//
//	img.Apply("blur", map[string]any{"radius": 3.0}).
//	    Apply("brightness", map[string]any{"amount": 0.1})
func (r *RcImage) Apply(name string, params map[string]any) *RcImage {
	if r.lastErr != nil {
		return r // short-circuit on prior error
	}

	meta, ok := r.operationIndex[name]
	if !ok {
		r.lastErr = fmt.Errorf("unknown operation %q", name)
		return r
	}

	// Validate params against manifest
	for _, pmeta := range meta.Params {
		val, exists := params[pmeta.Name]
		if !exists {
			continue
		}
		if err := validateParam(&pmeta, name+"."+pmeta.Name, val); err != nil {
			r.lastErr = err
			return r
		}
	}

	// NOTE: Actual WASM dispatch will be implemented when wasmtime-go
	// component model bindings are available. For now, the runtime
	// validates params and stores the operation for later dispatch.
	// The typed wrapper (generated by typegen) will call this method.

	_ = params // dispatch placeholder
	return r
}

// Encode encodes the current image to a format.
//
//	jpeg, err := img.Encode("jpeg", map[string]any{"quality": 85})
func (r *RcImage) Encode(format string, config map[string]any) ([]byte, error) {
	if r.lastErr != nil {
		return nil, r.lastErr
	}

	// NOTE: Actual WASM dispatch will be implemented when wasmtime-go
	// component model bindings are available.
	_ = format
	_ = config

	return nil, fmt.Errorf("WASM dispatch not yet implemented — wasmtime-go component model support required")
}

// LoadManifest creates an RcImage from a pre-parsed manifest.
// Useful for testing and for the typegen CLI.
func LoadManifest(manifestJSON []byte, manifestHash string) (*RcImage, error) {
	manifest, err := ParseManifest(manifestJSON)
	if err != nil {
		return nil, fmt.Errorf("failed to parse manifest: %w", err)
	}

	idx := make(map[string]*OperationMeta, len(manifest.Filters))
	for i := range manifest.Filters {
		idx[manifest.Filters[i].Name] = &manifest.Filters[i]
	}

	return &RcImage{
		manifest:       manifest,
		manifestHash:   manifestHash,
		operationIndex: idx,
	}, nil
}

// validateParam checks a parameter value against its manifest metadata.
func validateParam(meta *ParamMeta, name string, value any) error {
	t := meta.Type

	switch {
	case t == "f32" || t == "f64" || t == "u32" || t == "u16" || t == "u8" || t == "i32":
		switch v := value.(type) {
		case float64, float32, int, int32, int64, uint32:
			// ok
			var fv float64
			switch vt := v.(type) {
			case float64:
				fv = vt
			case float32:
				fv = float64(vt)
			case int:
				fv = float64(vt)
			case int32:
				fv = float64(vt)
			case int64:
				fv = float64(vt)
			case uint32:
				fv = float64(vt)
			}
			if meta.Min != nil && fv < *meta.Min {
				return fmt.Errorf("%s: %v is below minimum %v", name, value, *meta.Min)
			}
			if meta.Max != nil && fv > *meta.Max {
				return fmt.Errorf("%s: %v is above maximum %v", name, value, *meta.Max)
			}
		default:
			return fmt.Errorf("%s: expected number, got %T", name, value)
		}

	case t == "bool":
		if _, ok := value.(bool); !ok {
			return fmt.Errorf("%s: expected bool, got %T", name, value)
		}

	case t == "string" || t == "String":
		if _, ok := value.(string); !ok {
			return fmt.Errorf("%s: expected string, got %T", name, value)
		}
	}

	return nil
}

// toCamelCase converts snake_case or kebab-case to camelCase.
func toCamelCase(s string) string {
	var b strings.Builder
	upper := false
	for i, r := range s {
		if r == '_' || r == '-' {
			upper = true
			continue
		}
		if upper && i > 0 {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// MarshalManifest serializes a manifest to JSON (for testing).
func MarshalManifest(m *FilterManifest) ([]byte, error) {
	return json.Marshal(m)
}
