//! CLI dispatch — auto-generated filter dispatch by name.
//!
//! Maps filter name strings to typed node constructors. Generated by
//! rasmcore-codegen from #[register_filter] annotations.

include!(concat!(env!("OUT_DIR"), "/generated_cli_dispatch.rs"));
