//! Build script — scans for #[register_filter] annotations and generates:
//! 1. WIT filter declarations (printed to stderr for manual review/copy)
//! 2. Rust adapter dispatch code (written to $OUT_DIR/generated_filter_adapter.rs)
//!
//! The generated adapter code is included in adapter/mod.rs via:
//!   include!(concat!(env!("OUT_DIR"), "/generated_filter_adapter.rs"));

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use serde_json::{json, Value};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let filters_path = Path::new(&manifest_dir).join("src/domain/filters.rs");
    let param_types_path = Path::new(&manifest_dir).join("src/domain/param_types.rs");
    let composite_path = Path::new(&manifest_dir).join("src/domain/composite.rs");

    // Tell cargo to rerun if filters.rs, param_types.rs, composite.rs, or build.rs changes
    println!("cargo:rerun-if-changed=src/domain/filters.rs");
    println!("cargo:rerun-if-changed=src/domain/param_types.rs");
    println!("cargo:rerun-if-changed=src/domain/composite.rs");
    println!("cargo:rerun-if-changed=build.rs");

    if !filters_path.exists() {
        return;
    }

    // Combine sources: param_types first (defines reusable types), then filters, then composite
    let mut source = String::new();
    if param_types_path.exists() {
        source.push_str(&fs::read_to_string(&param_types_path).unwrap());
        source.push('\n');
    }
    source.push_str(&fs::read_to_string(&filters_path).unwrap());
    if composite_path.exists() {
        source.push('\n');
        source.push_str(&fs::read_to_string(&composite_path).unwrap());
    }
    let filters = parse_registered_filters(&source);

    if filters.is_empty() {
        // Write empty generated file
        let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
        fs::write(
            out_dir.join("generated_filter_adapter.rs"),
            "// No registered filters found\n",
        )
        .unwrap();
        return;
    }

    // Duplicate detection — fail at compile time if two filters share a name
    {
        let mut seen: std::collections::HashMap<&str, &str> = std::collections::HashMap::new();
        for f in &filters {
            if let Some(existing_fn) = seen.get(f.name.as_str()) {
                panic!(
                    "\n\nDuplicate filter name '{}' registered by:\n  {} (fn {})\n  {} (fn {})\n\
                     Rename one to resolve the conflict.\n",
                    f.name, f.fn_name, f.fn_name, existing_fn, existing_fn
                );
            }
            seen.insert(&f.name, &f.fn_name);
        }
    }

    // Print summary to stderr (visible during build)
    eprintln!(
        "rasmcore build.rs: Found {} registered filter(s):",
        filters.len()
    );
    for f in &filters {
        let params: Vec<String> = f.params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
        eprintln!(
            "  {} ({}): {}({})",
            f.name,
            f.category,
            f.fn_name,
            params.join(", ")
        );
    }

    // Generate WIT declarations (printed to stderr for review)
    eprintln!("\n--- Generated WIT (copy to filters.wit if new filters added) ---");
    for f in &filters {
        let wit_params = f
            .params
            .iter()
            .map(|(n, t)| format!("{}: {}", to_wit_name(n), to_wit_type(t)))
            .collect::<Vec<_>>()
            .join(", ");

        let wit_sig = if wit_params.is_empty() {
            format!(
                "    {}: func(pixels: buffer, info: image-info) -> result<buffer, rasmcore-error>;",
                to_wit_name(&f.name)
            )
        } else {
            format!(
                "    {}: func(pixels: buffer, info: image-info, {}) -> result<buffer, rasmcore-error>;",
                to_wit_name(&f.name),
                wit_params
            )
        };
        eprintln!("{wit_sig}");
    }
    eprintln!("--- End WIT ---\n");

    // Generate Rust adapter dispatch code
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let mut adapter_code = String::new();
    adapter_code.push_str("// Auto-generated by build.rs from #[register_filter] annotations.\n");
    adapter_code.push_str("// Do not edit — regenerate by changing filters.rs and rebuilding.\n\n");
    adapter_code.push_str("impl filters::Guest for Component {\n");

    for f in &filters {
        let trait_method = &f.name;
        let domain_fn = &f.fn_name;

        // Map Rust domain types to WIT binding types for the trait signature,
        // and generate the call expression (adding & for slice params)
        let mut sig_params = Vec::new();
        let mut call_params = Vec::new();
        for (n, t) in &f.params {
            let clean_n = n.trim_start_matches('_');
            let (binding_type, call_expr) = match t.as_str() {
                "&[f32]" => ("Vec<f32>", format!("&{clean_n}")),
                "&[f64]" => ("Vec<f64>", format!("&{clean_n}")),
                "&[u8]" => ("Vec<u8>", format!("&{clean_n}")),
                "&[u32]" => ("Vec<u32>", format!("&{clean_n}")),
                "&str" => ("String", format!("&{clean_n}")),
                "String" => ("String", clean_n.to_string()),
                _ => (t.as_str(), clean_n.to_string()), // scalars pass through
            };
            sig_params.push(format!("{clean_n}: {binding_type}"));
            call_params.push(call_expr);
        }

        let full_sig = if sig_params.is_empty() {
            "pixels: Vec<u8>, info: types::ImageInfo".to_string()
        } else {
            format!(
                "pixels: Vec<u8>, info: types::ImageInfo, {}",
                sig_params.join(", ")
            )
        };

        let full_call = if call_params.is_empty() {
            "&pixels, &di".to_string()
        } else {
            format!("&pixels, &di, {}", call_params.join(", "))
        };

        adapter_code.push_str(&format!(
            "    fn {trait_method}({full_sig}) -> Result<Vec<u8>, RasmcoreError> {{\n"
        ));
        adapter_code.push_str("        let di = to_domain_image_info(&info);\n");
        adapter_code.push_str(&format!(
            "        domain::filters::{domain_fn}({full_call}).map_err(to_wit_error)\n"
        ));
        adapter_code.push_str("    }\n\n");
    }

    adapter_code.push_str("}\n"); // close impl filters::Guest for Component

    fs::write(out_dir.join("generated_filter_adapter.rs"), &adapter_code).unwrap();

    eprintln!(
        "rasmcore build.rs: Generated filter adapter ({} filters)",
        filters.len()
    );

    // ── Generate pipeline filter nodes ────────────────────────────────────
    //
    // Each registered filter gets a typed node struct + ImageNode impl.
    // The node stores the upstream node ID, source image info, and all params.
    // compute_region fetches upstream pixels and calls the domain filter function.

    let mut nodes_code = String::new();
    nodes_code.push_str("// Auto-generated pipeline filter nodes.\n");
    nodes_code.push_str("// Do not edit — regenerate by changing filters.rs and rebuilding.\n\n");
    nodes_code.push_str("use crate::domain::error::ImageError;\n");
    nodes_code.push_str("use crate::domain::filters;\n");
    nodes_code.push_str("use crate::domain::pipeline::graph::{AccessPattern, ImageNode, bytes_per_pixel, crop_region};\n");
    nodes_code.push_str("use crate::domain::types::*;\n");
    nodes_code.push_str("use rasmcore_pipeline::{Overlap, Rect};\n\n");

    for f in &filters {
        let node_name = format!("{}Node", to_pascal_case(&f.name));
        let domain_fn = &f.fn_name;

        // Struct fields: upstream, source_info, and each param
        nodes_code.push_str(&format!("pub struct {node_name} {{\n"));
        nodes_code.push_str("    upstream: u32,\n");
        nodes_code.push_str("    source_info: ImageInfo,\n");
        for (pname, ptype) in &f.params {
            let clean_n = pname.trim_start_matches('_');
            let owned_type = to_owned_type(ptype);
            nodes_code.push_str(&format!("    {clean_n}: {owned_type},\n"));
        }
        nodes_code.push_str("}\n\n");

        // Constructor
        let ctor_params: Vec<String> = f
            .params
            .iter()
            .map(|(n, t)| {
                let clean_n = n.trim_start_matches('_');
                format!("{clean_n}: {}", to_owned_type(t))
            })
            .collect();
        let ctor_sig = if ctor_params.is_empty() {
            "upstream: u32, source_info: ImageInfo".to_string()
        } else {
            format!("upstream: u32, source_info: ImageInfo, {}", ctor_params.join(", "))
        };
        let ctor_fields: Vec<String> = f
            .params
            .iter()
            .map(|(n, _)| n.trim_start_matches('_').to_string())
            .collect();
        let mut all_fields = vec!["upstream".to_string(), "source_info".to_string()];
        all_fields.extend(ctor_fields);

        nodes_code.push_str(&format!("impl {node_name} {{\n"));
        nodes_code.push_str(&format!("    pub fn new({ctor_sig}) -> Self {{\n"));
        nodes_code.push_str(&format!(
            "        Self {{ {} }}\n",
            all_fields.join(", ")
        ));
        nodes_code.push_str("    }\n");
        nodes_code.push_str("}\n\n");

        // ImageNode impl
        let overlap_expr = match f.overlap.as_str() {
            "full" => "Overlap::uniform(u32::MAX)".to_string(),
            s if s.starts_with("uniform(") => format!("Overlap::{s}"),
            s if s.starts_with("param(") => {
                let param_name = s.trim_start_matches("param(").trim_end_matches(')');
                format!("Overlap::uniform(self.{param_name} as u32)")
            }
            _ => "Overlap::zero()".to_string(), // default: point operation
        };

        // Build the domain function call
        let call_args: Vec<String> = f
            .params
            .iter()
            .map(|(n, t)| {
                let clean_n = n.trim_start_matches('_');
                if t.starts_with("&[") || t == "&str" {
                    format!("&self.{clean_n}")
                } else if t == "String" {
                    format!("self.{clean_n}.clone()")
                } else {
                    format!("self.{clean_n}")
                }
            })
            .collect();
        let full_domain_call = if call_args.is_empty() {
            format!("filters::{domain_fn}(&src_pixels, &region_info)")
        } else {
            format!(
                "filters::{domain_fn}(&src_pixels, &region_info, {})",
                call_args.join(", ")
            )
        };

        nodes_code.push_str(&format!("impl ImageNode for {node_name} {{\n"));
        nodes_code.push_str("    fn info(&self) -> ImageInfo { self.source_info.clone() }\n\n");
        nodes_code.push_str("    fn compute_region(\n");
        nodes_code.push_str("        &self,\n");
        nodes_code.push_str("        request: Rect,\n");
        nodes_code.push_str("        upstream_fn: &mut dyn FnMut(u32, Rect) -> Result<Vec<u8>, ImageError>,\n");
        nodes_code.push_str("    ) -> Result<Vec<u8>, ImageError> {\n");
        nodes_code.push_str("        let overlap = self.overlap();\n");
        nodes_code.push_str("        let upstream_rect = request.expand(&overlap, self.source_info.width, self.source_info.height);\n");
        nodes_code.push_str("        let src_pixels = upstream_fn(self.upstream, upstream_rect)?;\n");
        nodes_code.push_str("        let region_info = ImageInfo {\n");
        nodes_code.push_str("            width: upstream_rect.width,\n");
        nodes_code.push_str("            height: upstream_rect.height,\n");
        nodes_code.push_str("            ..self.source_info\n");
        nodes_code.push_str("        };\n");
        nodes_code.push_str(&format!("        let filtered = {full_domain_call}?;\n"));
        nodes_code.push_str("        if upstream_rect == request {\n");
        nodes_code.push_str("            Ok(filtered)\n");
        nodes_code.push_str("        } else {\n");
        nodes_code.push_str("            let bpp = bytes_per_pixel(self.source_info.format);\n");
        nodes_code.push_str("            let sub = Rect::new(\n");
        nodes_code.push_str("                request.x - upstream_rect.x,\n");
        nodes_code.push_str("                request.y - upstream_rect.y,\n");
        nodes_code.push_str("                request.width,\n");
        nodes_code.push_str("                request.height,\n");
        nodes_code.push_str("            );\n");
        nodes_code.push_str("            let out_rect = Rect::new(0, 0, upstream_rect.width, upstream_rect.height);\n");
        nodes_code.push_str("            Ok(crop_region(&filtered, out_rect, sub, bpp))\n");
        nodes_code.push_str("        }\n");
        nodes_code.push_str("    }\n\n");
        nodes_code.push_str(&format!("    fn overlap(&self) -> Overlap {{ {overlap_expr} }}\n"));
        nodes_code.push_str("    fn access_pattern(&self) -> AccessPattern { AccessPattern::LocalNeighborhood }\n");
        nodes_code.push_str("}\n\n");
    }

    fs::write(out_dir.join("generated_pipeline_nodes.rs"), &nodes_code).unwrap();

    // ── Generate pipeline adapter filter methods ──────────────────────────
    //
    // Each filter gets a method on PipelineResource that creates the typed node
    // and adds it to the graph.

    let mut pipe_adapter = String::new();
    pipe_adapter.push_str("// Auto-generated pipeline filter adapter methods.\n");
    pipe_adapter.push_str("// Do not edit — regenerate by changing filters.rs and rebuilding.\n\n");
    pipe_adapter.push_str("macro_rules! generated_pipeline_filter_methods {\n");
    pipe_adapter.push_str("    () => {\n");

    for f in &filters {
        let trait_method = &f.name;
        let node_name = format!("{}Node", to_pascal_case(&f.name));

        // WIT binding signature params
        let mut sig_params = Vec::new();
        let mut node_ctor_args = Vec::new();
        for (n, t) in &f.params {
            let clean_n = n.trim_start_matches('_');
            let binding_type = to_binding_type(t);
            sig_params.push(format!("{clean_n}: {binding_type}"));
            // For slice types, the node stores owned data; pass directly from binding
            node_ctor_args.push(clean_n.to_string());
        }

        let full_sig = if sig_params.is_empty() {
            "&self, source: NodeId".to_string()
        } else {
            format!("&self, source: NodeId, {}", sig_params.join(", "))
        };

        let ctor_call = if node_ctor_args.is_empty() {
            format!("filters::{node_name}::new(source, src_info)")
        } else {
            format!(
                "filters::{node_name}::new(source, src_info, {})",
                node_ctor_args.join(", ")
            )
        };

        pipe_adapter.push_str(&format!(
            "    fn {trait_method}({full_sig}) -> Result<NodeId, RasmcoreError> {{\n"
        ));
        pipe_adapter.push_str("        let src_info = self.graph.borrow().node_info(source).map_err(to_wit_error)?;\n");
        pipe_adapter.push_str(&format!(
            "        let node = {ctor_call};\n"
        ));
        pipe_adapter.push_str("        Ok(self.graph.borrow_mut().add_node(Box::new(node)))\n");
        pipe_adapter.push_str("    }\n\n");
    }

    pipe_adapter.push_str("    };\n"); // close macro arm
    pipe_adapter.push_str("}\n"); // close macro_rules!

    fs::write(out_dir.join("generated_pipeline_adapter.rs"), &pipe_adapter).unwrap();

    eprintln!(
        "rasmcore build.rs: Generated pipeline nodes + adapter ({} filters)",
        filters.len()
    );

    // ── Generate param-manifest.json via serde_json ────────────────────────
    let param_structs = parse_config_params_structs(&source);
    let mut filter_entries: Vec<Value> = Vec::new();

    for f in &filters {
        let struct_name = format!("{}Params", to_pascal_case(&f.name));
        let params_struct = param_structs.get(&struct_name);

        let params_json: Vec<Value> = if let Some(fields) = params_struct {
            fields
                .iter()
                .map(|field| {
                    json!({
                        "name": field.name,
                        "type": field.param_type,
                        "min": parse_json_value(&field.min),
                        "max": parse_json_value(&field.max),
                        "step": parse_json_value(&field.step),
                        "default": parse_json_value(&field.default_val),
                        "label": field.label,
                        "hint": field.hint,
                    })
                })
                .collect()
        } else if !f.params.is_empty() {
            f.params
                .iter()
                .map(|(pname, ptype)| {
                    let (min, max, step, def) = default_range_for_type(ptype);
                    json!({
                        "name": pname,
                        "type": ptype,
                        "min": parse_json_value(&min),
                        "max": parse_json_value(&max),
                        "step": parse_json_value(&step),
                        "default": parse_json_value(&def),
                        "label": "",
                        "hint": "",
                    })
                })
                .collect()
        } else {
            vec![]
        };

        filter_entries.push(json!({
            "name": f.name,
            "category": f.category,
            "group": f.group,
            "variant": f.variant,
            "reference": f.reference,
            "params": params_json,
        }));
    }

    // Parse generators, compositors, mappers for manifest
    let generators = parse_registered_by_kind(&source, "register_generator");
    let compositors = parse_registered_by_kind(&source, "register_compositor");
    let mappers = parse_registered_by_kind(&source, "register_mapper");

    let gen_entries: Vec<serde_json::Value> = generators
        .iter()
        .map(|g| {
            json!({
                "name": g.name,
                "category": g.category,
                "group": g.group,
                "variant": g.variant,
                "reference": g.reference,
                "kind": "generator",
            })
        })
        .collect();

    let comp_entries: Vec<serde_json::Value> = compositors
        .iter()
        .map(|c| {
            json!({
                "name": c.name,
                "category": c.category,
                "group": c.group,
                "variant": c.variant,
                "reference": c.reference,
                "kind": "compositor",
            })
        })
        .collect();

    let map_entries: Vec<serde_json::Value> = mappers
        .iter()
        .map(|m| {
            json!({
                "name": m.name,
                "category": m.category,
                "group": m.group,
                "variant": m.variant,
                "reference": m.reference,
                "kind": "mapper",
            })
        })
        .collect();

    let manifest = json!({
        "filters": filter_entries,
        "generators": gen_entries,
        "compositors": comp_entries,
        "mappers": map_entries,
    });
    let manifest_str = serde_json::to_string_pretty(&manifest).unwrap();
    fs::write(out_dir.join("param-manifest.json"), &manifest_str).unwrap();
    eprintln!(
        "rasmcore build.rs: Generated param-manifest.json ({} filters, {} generators, {} compositors, {} mappers)",
        filters.len(), generators.len(), compositors.len(), mappers.len()
    );
}

/// Parsed filter registration.
struct FilterReg {
    name: String,
    category: String,
    group: String,
    variant: String,
    reference: String,
    overlap: String, // "zero" (default), "uniform(N)", "full", "param(name)"
    fn_name: String,
    params: Vec<(String, String)>, // (param_name, rust_type)
}

/// Parse #[register_filter(...)] annotations from Rust source.
fn parse_registered_filters(source: &str) -> Vec<FilterReg> {
    let mut filters = Vec::new();

    // Simple regex-based parsing (avoids full syn in build.rs for speed)
    // Pattern: #[register_filter(name = "...", category = "...")] or
    //          #[rasmcore_macros::register_filter(name = "...", category = "...")]
    //          pub fn name(pixels: &[u8], info: &ImageInfo, param: type, ...) -> Result<...>

    let lines: Vec<&str> = source.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();

        // Look for register_filter attribute (may span multiple lines)
        if line.contains("register_filter(") && !line.starts_with("//") {
            // Collect the full attribute text (may span multiple lines)
            let mut attr_text = line.to_string();
            let mut k = i + 1;
            while !attr_text.contains(")]") && k < lines.len() {
                attr_text.push(' ');
                attr_text.push_str(lines[k].trim());
                k += 1;
            }

            // Extract name and category (required)
            let name = extract_string_attr(&attr_text, "name");
            let category = extract_string_attr(&attr_text, "category");
            // Extract optional group/variant/reference
            let group = extract_string_attr(&attr_text, "group").unwrap_or_default();
            let variant = extract_string_attr(&attr_text, "variant").unwrap_or_default();
            let reference = extract_string_attr(&attr_text, "reference").unwrap_or_default();
            let overlap = extract_string_attr(&attr_text, "overlap").unwrap_or_else(|| "zero".to_string());

            if let (Some(name), Some(category)) = (name, category) {
                // Find the next pub fn AFTER the attribute ends (k is past the closing `)]`)
                let mut j = k;
                while j < lines.len() {
                    let fn_line = lines[j].trim();
                    if fn_line.starts_with("pub fn ") {
                        // Collect lines until we find the closing ')' and '->'
                        let mut full_sig = fn_line.to_string();
                        while !full_sig.contains("->") && j + 1 < lines.len() {
                            j += 1;
                            full_sig.push(' ');
                            full_sig.push_str(lines[j].trim());
                        }
                        if let Some(mut reg) = parse_fn_signature(&full_sig, &name, &category) {
                            reg.group = group.clone();
                            reg.variant = variant.clone();
                            reg.reference = reference.clone();
                            reg.overlap = overlap.clone();
                            filters.push(reg);
                        }
                        break;
                    }
                    // Skip comments, blank lines, and other attributes before pub fn
                    if fn_line.starts_with("//")
                        || fn_line.starts_with("///")
                        || fn_line.starts_with("#[")
                        || fn_line.is_empty()
                    {
                        j += 1;
                        continue;
                    }
                    break; // unexpected line, skip
                }
            }
        }
        i += 1;
    }

    filters
}

/// Simple registration entry for generators/compositors/mappers (no params needed for manifest).
struct SimpleReg {
    name: String,
    category: String,
    group: String,
    variant: String,
    reference: String,
}

/// Parse registrations of a specific kind (e.g., "register_generator").
fn parse_registered_by_kind(source: &str, kind: &str) -> Vec<SimpleReg> {
    let mut regs = Vec::new();
    let lines: Vec<&str> = source.lines().collect();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i].trim();
        if line.contains(kind) && !line.starts_with("//") {
            // Collect full attribute text (may span multiple lines)
            let mut attr_text = line.to_string();
            let mut k = i + 1;
            while !attr_text.contains(")]") && k < lines.len() {
                attr_text.push(' ');
                attr_text.push_str(lines[k].trim());
                k += 1;
            }

            if let Some(name) = extract_string_attr(&attr_text, "name") {
                let category = extract_string_attr(&attr_text, "category").unwrap_or_default();
                let group = extract_string_attr(&attr_text, "group").unwrap_or_default();
                let variant = extract_string_attr(&attr_text, "variant").unwrap_or_default();
                let reference = extract_string_attr(&attr_text, "reference").unwrap_or_default();
                regs.push(SimpleReg {
                    name,
                    category,
                    group,
                    variant,
                    reference,
                });
            }
        }
        i += 1;
    }
    regs
}

fn extract_string_attr(line: &str, attr: &str) -> Option<String> {
    let pattern = format!("{attr} = \"");
    if let Some(start) = line.find(&pattern) {
        let rest = &line[start + pattern.len()..];
        if let Some(end) = rest.find('"') {
            return Some(rest[..end].to_string());
        }
    }
    None
}

/// Split `#[param(...)]` inner text by commas, respecting quoted strings and brackets.
/// e.g., `min = 0, max = 1, default = "[[0,0],[1,1]]"` → 3 parts, not 6.
fn split_param_attrs(s: &str) -> Vec<&str> {
    let mut parts = Vec::new();
    let mut start = 0;
    let mut in_quotes = false;
    let mut bracket_depth = 0i32;
    for (i, ch) in s.char_indices() {
        match ch {
            '"' => in_quotes = !in_quotes,
            '[' | '(' if !in_quotes => bracket_depth += 1,
            ']' | ')' if !in_quotes => bracket_depth -= 1,
            ',' if !in_quotes && bracket_depth == 0 => {
                parts.push(&s[start..i]);
                start = i + 1;
            }
            _ => {}
        }
    }
    if start < s.len() {
        parts.push(&s[start..]);
    }
    parts
}

/// Parse a string into a serde_json::Value. Handles "null", numbers, booleans,
/// JSON arrays/objects, and falls back to a JSON string for anything else.
fn parse_json_value(s: &str) -> Value {
    if s == "null" || s.is_empty() {
        return Value::Null;
    }
    // Try parsing as valid JSON (number, bool, array, object)
    if let Ok(v) = serde_json::from_str::<Value>(s) {
        return v;
    }
    // Fall back to a JSON string
    Value::String(s.to_string())
}

fn parse_fn_signature(line: &str, name: &str, category: &str) -> Option<FilterReg> {
    // pub fn blur(pixels: &[u8], info: &ImageInfo, radius: f32) -> Result<...>
    let fn_start = line.find("fn ")? + 3;
    let paren_start = line.find('(')?;
    let fn_name = line[fn_start..paren_start].trim().to_string();

    let paren_end = line.find(')')?;
    let params_str = &line[paren_start + 1..paren_end];

    // Parse params, skip pixels and info
    let mut params = Vec::new();
    for param in params_str.split(',') {
        let param = param.trim();
        if param.is_empty()
            || param.contains("pixels")
            || param.contains("info")
            || param.contains("&[u8]")
            || param.contains("ImageInfo")
        {
            continue;
        }
        // name: type
        let parts: Vec<&str> = param.splitn(2, ':').collect();
        if parts.len() == 2 {
            let pname = parts[0].trim().to_string();
            let ptype = parts[1].trim().to_string();
            params.push((pname, ptype));
        }
    }

    Some(FilterReg {
        name: name.to_string(),
        category: category.to_string(),
        group: String::new(),
        variant: String::new(),
        reference: String::new(),
        overlap: "zero".to_string(),
        fn_name,
        params,
    })
}

// ─── ConfigParams struct parser ─────────────────────────────────────────────

#[derive(Clone)]
struct ParamField {
    name: String,
    param_type: String,
    min: String,
    max: String,
    step: String,
    default_val: String,
    label: String,
    hint: String,
}

/// Parsed ConfigParams struct metadata (struct-level attributes).
struct ParsedStruct {
    fields: Vec<ParamField>,
    config_hint: String,
}

fn parse_config_params_structs(source: &str) -> std::collections::HashMap<String, Vec<ParamField>> {
    // Pass 1: parse all ConfigParams structs (raw, without resolving nested types)
    let raw = parse_config_params_raw(source);

    // Pass 2: resolve nested struct types — inline their fields with prefix
    let mut result = std::collections::HashMap::new();
    for (name, parsed) in &raw {
        let fields = resolve_nested_fields(&parsed.fields, &parsed.config_hint, &raw);
        result.insert(name.clone(), fields);
    }
    result
}

fn parse_config_params_raw(source: &str) -> std::collections::HashMap<String, ParsedStruct> {
    let mut result = std::collections::HashMap::new();
    let lines: Vec<&str> = source.lines().collect();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i].trim();
        if line.contains("derive") && line.contains("ConfigParams") {
            // Look backwards/forwards for #[config_hint("...")] on the struct
            let mut struct_hint = String::new();

            // Check lines between derive and struct for #[config_hint("...")]
            let mut j = i + 1;
            while j < lines.len() {
                let fl = lines[j].trim();
                if fl.starts_with("#[config_hint(") {
                    if let Some(h) = extract_config_hint_value(fl) {
                        struct_hint = h;
                    }
                } else if fl.starts_with("///") || fl.is_empty() {
                    // skip doc comments and blank lines
                } else {
                    break;
                }
                j += 1;
            }

            // Also check if config_hint was on a line before the derive
            if struct_hint.is_empty() && i > 0 {
                let prev = lines[i - 1].trim();
                if prev.starts_with("#[config_hint(") {
                    if let Some(h) = extract_config_hint_value(prev) {
                        struct_hint = h;
                    }
                }
            }

            if j < lines.len() && lines[j].trim().starts_with("pub struct ") {
                let struct_line = lines[j].trim();
                let struct_name = struct_line
                    .strip_prefix("pub struct ")
                    .and_then(|s| s.split([' ', '{']).next())
                    .unwrap_or("")
                    .to_string();

                // Parse fields until closing brace
                let mut fields = Vec::new();
                let mut doc_comment = String::new();
                let mut param_min = "null".to_string();
                let mut param_max = "null".to_string();
                let mut param_step = "null".to_string();
                let mut param_default = String::new();
                let mut param_hint = String::new();
                j += 1;
                while j < lines.len() {
                    let fl = lines[j].trim();
                    if fl == "}" {
                        break;
                    }

                    if fl.starts_with("///") {
                        doc_comment = fl.trim_start_matches("///").trim().to_string();
                    } else if fl.starts_with("#[param(") {
                        let inner = fl.trim_start_matches("#[param(").trim_end_matches(")]");
                        // Split by comma, but respect quoted strings and brackets
                        for part in split_param_attrs(inner) {
                            let part = part.trim();
                            if let Some((k, v)) = part.split_once('=') {
                                let k = k.trim();
                                let v = v.trim().trim_matches('"');
                                match k {
                                    "min" => param_min = v.to_string(),
                                    "max" => param_max = v.to_string(),
                                    "step" => param_step = v.to_string(),
                                    "default" => param_default = v.to_string(),
                                    "hint" => param_hint = v.to_string(),
                                    _ => {}
                                }
                            }
                        }
                    } else if fl.starts_with("pub ") && fl.contains(':') {
                        let field_str = fl.strip_prefix("pub ").unwrap_or(fl);
                        if let Some((fname, ftype)) = field_str.split_once(':') {
                            let fname = fname.trim().to_string();
                            let ftype = ftype.trim().trim_end_matches(',').trim().to_string();
                            let default = if param_default.is_empty() {
                                default_for_type(&ftype)
                            } else {
                                param_default.clone()
                            };
                            fields.push(ParamField {
                                name: fname,
                                param_type: ftype,
                                min: param_min.clone(),
                                max: param_max.clone(),
                                step: param_step.clone(),
                                default_val: default,
                                label: doc_comment.clone(),
                                hint: param_hint.clone(),
                            });
                            doc_comment.clear();
                            param_min = "null".into();
                            param_max = "null".into();
                            param_step = "null".into();
                            param_default.clear();
                            param_hint.clear();
                        }
                    }
                    j += 1;
                }

                if !fields.is_empty() {
                    result.insert(
                        struct_name,
                        ParsedStruct {
                            fields,
                            config_hint: struct_hint.clone(),
                        },
                    );
                }
            }
        }
        i += 1;
    }
    result
}

/// Extract value from `#[config_hint("rc.color_rgba")]`
fn extract_config_hint_value(line: &str) -> Option<String> {
    let start = line.find("config_hint(\"")? + "config_hint(\"".len();
    let rest = &line[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

/// Resolve nested struct fields: if a field type matches a known ConfigParams struct,
/// inline its fields with a prefix and propagate hints.
fn resolve_nested_fields(
    fields: &[ParamField],
    _struct_hint: &str,
    all_structs: &std::collections::HashMap<String, ParsedStruct>,
) -> Vec<ParamField> {
    let mut result = Vec::new();
    for field in fields {
        // Look up by full type path or just the last segment (e.g., super::param_types::ColorRgba → ColorRgba)
        let type_name = field
            .param_type
            .rsplit("::")
            .next()
            .unwrap_or(&field.param_type);
        if let Some(nested) = all_structs
            .get(&field.param_type)
            .or_else(|| all_structs.get(type_name))
        {
            // Nested ConfigParams struct — inline fields with prefix
            let hint = if field.hint.is_empty() {
                &nested.config_hint
            } else {
                &field.hint
            };
            for nf in &nested.fields {
                result.push(ParamField {
                    name: format!("{}.{}", field.name, nf.name),
                    param_type: nf.param_type.clone(),
                    min: nf.min.clone(),
                    max: nf.max.clone(),
                    step: nf.step.clone(),
                    default_val: nf.default_val.clone(),
                    label: nf.label.clone(),
                    hint: if hint.is_empty() {
                        nf.hint.clone()
                    } else {
                        hint.to_string()
                    },
                });
            }
        } else {
            result.push(field.clone());
        }
    }
    result
}

fn default_for_type(ty: &str) -> String {
    match ty {
        "f32" | "f64" => "0.0".to_string(),
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => "0".to_string(),
        "bool" => "false".to_string(),
        _ => "null".to_string(),
    }
}

fn default_range_for_type(ty: &str) -> (&str, &str, &str, &str) {
    match ty {
        "f32" => ("0.0", "1.0", "0.01", "0.0"),
        "u32" => ("0", "1000", "1", "0"),
        "bool" => ("null", "null", "null", "false"),
        _ => ("null", "null", "null", "null"),
    }
}

fn to_pascal_case(snake: &str) -> String {
    snake
        .split('_')
        .map(|seg| {
            let mut c = seg.chars();
            match c.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

fn to_wit_name(rust_name: &str) -> String {
    rust_name.trim_start_matches('_').replace('_', "-")
}

fn to_wit_type(rust_type: &str) -> String {
    match rust_type {
        "f32" => "f32".to_string(),
        "f64" => "f64".to_string(),
        "u8" => "u8".to_string(),
        "u16" => "u16".to_string(),
        "u32" => "u32".to_string(),
        "u64" => "u64".to_string(),
        "i32" => "s32".to_string(),
        "i64" => "s64".to_string(),
        "bool" => "bool".to_string(),
        "&[f32]" => "list<f32>".to_string(),
        "&[f64]" => "list<f64>".to_string(),
        "&[u8]" => "list<u8>".to_string(),
        "&[u32]" => "list<u32>".to_string(),
        "String" | "&str" => "string".to_string(),
        other => other.to_string(),
    }
}

/// Convert Rust domain type to owned Rust type (for node struct fields).
fn to_owned_type(rust_type: &str) -> &str {
    match rust_type {
        "&[f32]" => "Vec<f32>",
        "&[f64]" => "Vec<f64>",
        "&[u8]" => "Vec<u8>",
        "&[u32]" => "Vec<u32>",
        "&str" => "String",
        other => other,
    }
}

/// Convert Rust domain type to WIT binding type (for trait signatures).
fn to_binding_type(rust_type: &str) -> &str {
    match rust_type {
        "&[f32]" => "Vec<f32>",
        "&[f64]" => "Vec<f64>",
        "&[u8]" => "Vec<u8>",
        "&[u32]" => "Vec<u32>",
        "&str" => "String",
        other => other,
    }
}
