//! Build script — scans for #[register_filter] annotations and generates:
//! 1. WIT filter declarations (printed to stderr for manual review/copy)
//! 2. Rust adapter dispatch code (written to $OUT_DIR/generated_filter_adapter.rs)
//!
//! The generated adapter code is included in adapter/mod.rs via:
//!   include!(concat!(env!("OUT_DIR"), "/generated_filter_adapter.rs"));

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let filters_path = Path::new(&manifest_dir).join("src/domain/filters.rs");

    // Tell cargo to rerun if filters.rs changes
    println!("cargo:rerun-if-changed=src/domain/filters.rs");

    if !filters_path.exists() {
        return;
    }

    let source = fs::read_to_string(&filters_path).unwrap();
    let filters = parse_registered_filters(&source);

    if filters.is_empty() {
        // Write empty generated file
        let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
        fs::write(
            out_dir.join("generated_filter_adapter.rs"),
            "// No registered filters found\n",
        )
        .unwrap();
        return;
    }

    // Duplicate detection — fail at compile time if two filters share a name
    {
        let mut seen: std::collections::HashMap<&str, &str> = std::collections::HashMap::new();
        for f in &filters {
            if let Some(existing_fn) = seen.get(f.name.as_str()) {
                panic!(
                    "\n\nDuplicate filter name '{}' registered by:\n  {} (fn {})\n  {} (fn {})\n\
                     Rename one to resolve the conflict.\n",
                    f.name, f.fn_name, f.fn_name, existing_fn, existing_fn
                );
            }
            seen.insert(&f.name, &f.fn_name);
        }
    }

    // Print summary to stderr (visible during build)
    eprintln!(
        "rasmcore build.rs: Found {} registered filter(s):",
        filters.len()
    );
    for f in &filters {
        let params: Vec<String> = f.params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
        eprintln!(
            "  {} ({}): {}({})",
            f.name,
            f.category,
            f.fn_name,
            params.join(", ")
        );
    }

    // Generate WIT declarations (printed to stderr for review)
    eprintln!("\n--- Generated WIT (copy to filters.wit if new filters added) ---");
    for f in &filters {
        let wit_params = f
            .params
            .iter()
            .map(|(n, t)| format!("{}: {}", to_wit_name(n), to_wit_type(t)))
            .collect::<Vec<_>>()
            .join(", ");

        let wit_sig = if wit_params.is_empty() {
            format!(
                "    {}: func(pixels: buffer, info: image-info) -> result<buffer, rasmcore-error>;",
                to_wit_name(&f.name)
            )
        } else {
            format!(
                "    {}: func(pixels: buffer, info: image-info, {}) -> result<buffer, rasmcore-error>;",
                to_wit_name(&f.name),
                wit_params
            )
        };
        eprintln!("{wit_sig}");
    }
    eprintln!("--- End WIT ---\n");

    // Generate Rust adapter dispatch code
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let mut adapter_code = String::new();
    adapter_code.push_str("// Auto-generated by build.rs from #[register_filter] annotations.\n");
    adapter_code.push_str("// Do not edit — regenerate by changing filters.rs and rebuilding.\n\n");

    for f in &filters {
        let fn_name = &f.fn_name;
        let params_sig: Vec<String> = f.params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
        let params_call: Vec<String> = f.params.iter().map(|(n, _)| n.clone()).collect();

        let full_sig = if params_sig.is_empty() {
            "pixels: Vec<u8>, info: types::ImageInfo".to_string()
        } else {
            format!(
                "pixels: Vec<u8>, info: types::ImageInfo, {}",
                params_sig.join(", ")
            )
        };

        let full_call = if params_call.is_empty() {
            "&pixels, &di".to_string()
        } else {
            format!("&pixels, &di, {}", params_call.join(", "))
        };

        adapter_code.push_str(&format!(
            "fn {fn_name}({full_sig}) -> Result<Vec<u8>, RasmcoreError> {{\n"
        ));
        adapter_code.push_str("    let di = to_domain_image_info(&info);\n");
        adapter_code.push_str(&format!(
            "    domain::filters::{fn_name}({full_call}).map_err(to_wit_error)\n"
        ));
        adapter_code.push_str("}\n\n");
    }

    fs::write(out_dir.join("generated_filter_adapter.rs"), &adapter_code).unwrap();

    eprintln!(
        "rasmcore build.rs: Generated adapter code at {}/generated_filter_adapter.rs",
        out_dir.display()
    );

    // ── Generate param-manifest.json ──────────────────────────────────────
    let param_structs = parse_config_params_structs(&source);
    let mut manifest = String::from("{\n  \"filters\": [\n");

    for (i, f) in filters.iter().enumerate() {
        // Match filter to its param struct by name convention: blur → BlurParams, bokeh_blur → BokehBlurParams
        let struct_name = format!("{}Params", to_pascal_case(&f.name));
        let params = param_structs.get(&struct_name);

        manifest.push_str("    {\n");
        manifest.push_str(&format!("      \"name\": \"{}\",\n", f.name));
        manifest.push_str(&format!("      \"category\": \"{}\",\n", f.category));
        manifest.push_str("      \"params\": [");

        if let Some(fields) = params {
            for (j, field) in fields.iter().enumerate() {
                if j > 0 {
                    manifest.push(',');
                }
                manifest.push_str(&format!(
                    "\n        {{\"name\":\"{}\",\"type\":\"{}\",\"min\":{},\"max\":{},\"step\":{},\"default\":{},\"label\":\"{}\"}}",
                    field.name, field.param_type,
                    field.min, field.max, field.step, field.default_val, field.label
                ));
            }
            if !fields.is_empty() {
                manifest.push('\n');
                manifest.push_str("      ");
            }
        } else if !f.params.is_empty() {
            // Fallback: use function signature params with default ranges
            for (j, (pname, ptype)) in f.params.iter().enumerate() {
                if j > 0 {
                    manifest.push(',');
                }
                let (min, max, step, def) = default_range_for_type(ptype);
                manifest.push_str(&format!(
                    "\n        {{\"name\":\"{}\",\"type\":\"{}\",\"min\":{},\"max\":{},\"step\":{},\"default\":{},\"label\":\"\"}}",
                    pname, ptype, min, max, step, def
                ));
            }
            manifest.push('\n');
            manifest.push_str("      ");
        }

        manifest.push_str("]\n    }");
        if i < filters.len() - 1 {
            manifest.push(',');
        }
        manifest.push('\n');
    }

    manifest.push_str("  ]\n}\n");

    fs::write(out_dir.join("param-manifest.json"), &manifest).unwrap();
    eprintln!(
        "rasmcore build.rs: Generated param-manifest.json ({} filters)",
        filters.len()
    );
}

/// Parsed filter registration.
struct FilterReg {
    name: String,
    category: String,
    fn_name: String,
    params: Vec<(String, String)>, // (param_name, rust_type)
}

/// Parse #[register_filter(...)] annotations from Rust source.
fn parse_registered_filters(source: &str) -> Vec<FilterReg> {
    let mut filters = Vec::new();

    // Simple regex-based parsing (avoids full syn in build.rs for speed)
    // Pattern: #[register_filter(name = "...", category = "...")] or
    //          #[rasmcore_macros::register_filter(name = "...", category = "...")]
    //          pub fn name(pixels: &[u8], info: &ImageInfo, param: type, ...) -> Result<...>

    let lines: Vec<&str> = source.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();

        // Look for register_filter attribute
        if line.contains("register_filter(") && line.contains("name") {
            // Extract name and category
            let name = extract_string_attr(line, "name");
            let category = extract_string_attr(line, "category");

            if let (Some(name), Some(category)) = (name, category) {
                // Find the next pub fn and collect its full signature (may span multiple lines)
                let mut j = i + 1;
                while j < lines.len() {
                    let fn_line = lines[j].trim();
                    if fn_line.starts_with("pub fn ") {
                        // Collect lines until we find the closing ')' and '->'
                        let mut full_sig = fn_line.to_string();
                        while !full_sig.contains("->") && j + 1 < lines.len() {
                            j += 1;
                            full_sig.push(' ');
                            full_sig.push_str(lines[j].trim());
                        }
                        if let Some(reg) = parse_fn_signature(&full_sig, &name, &category) {
                            filters.push(reg);
                        }
                        break;
                    }
                    if fn_line.starts_with("//") || fn_line.starts_with("///") || fn_line.is_empty()
                    {
                        j += 1;
                        continue;
                    }
                    break; // unexpected line, skip
                }
            }
        }
        i += 1;
    }

    filters
}

fn extract_string_attr(line: &str, attr: &str) -> Option<String> {
    let pattern = format!("{attr} = \"");
    if let Some(start) = line.find(&pattern) {
        let rest = &line[start + pattern.len()..];
        if let Some(end) = rest.find('"') {
            return Some(rest[..end].to_string());
        }
    }
    None
}

fn parse_fn_signature(line: &str, name: &str, category: &str) -> Option<FilterReg> {
    // pub fn blur(pixels: &[u8], info: &ImageInfo, radius: f32) -> Result<...>
    let fn_start = line.find("fn ")? + 3;
    let paren_start = line.find('(')?;
    let fn_name = line[fn_start..paren_start].trim().to_string();

    let paren_end = line.find(')')?;
    let params_str = &line[paren_start + 1..paren_end];

    // Parse params, skip pixels and info
    let mut params = Vec::new();
    for param in params_str.split(',') {
        let param = param.trim();
        if param.is_empty()
            || param.contains("pixels")
            || param.contains("info")
            || param.contains("&[u8]")
            || param.contains("ImageInfo")
        {
            continue;
        }
        // name: type
        let parts: Vec<&str> = param.splitn(2, ':').collect();
        if parts.len() == 2 {
            let pname = parts[0].trim().to_string();
            let ptype = parts[1].trim().to_string();
            params.push((pname, ptype));
        }
    }

    Some(FilterReg {
        name: name.to_string(),
        category: category.to_string(),
        fn_name,
        params,
    })
}

// ─── ConfigParams struct parser ─────────────────────────────────────────────

struct ParamField {
    name: String,
    param_type: String,
    min: String,
    max: String,
    step: String,
    default_val: String,
    label: String,
}

fn parse_config_params_structs(source: &str) -> std::collections::HashMap<String, Vec<ParamField>> {
    let mut result = std::collections::HashMap::new();
    let lines: Vec<&str> = source.lines().collect();
    let mut i = 0;

    while i < lines.len() {
        let line = lines[i].trim();
        if line.contains("derive") && line.contains("ConfigParams") {
            // Next non-comment line should be "pub struct FooParams {"
            let mut j = i + 1;
            while j < lines.len()
                && (lines[j].trim().starts_with("//") || lines[j].trim().is_empty())
            {
                j += 1;
            }
            if j < lines.len() && lines[j].trim().starts_with("pub struct ") {
                let struct_line = lines[j].trim();
                let struct_name = struct_line
                    .strip_prefix("pub struct ")
                    .and_then(|s| s.split([' ', '{']).next())
                    .unwrap_or("")
                    .to_string();

                // Parse fields until closing brace
                let mut fields = Vec::new();
                let mut doc_comment = String::new();
                let mut param_attrs: (String, String, String, String) =
                    ("null".into(), "null".into(), "null".into(), String::new());
                j += 1;
                while j < lines.len() {
                    let fl = lines[j].trim();
                    if fl == "}" {
                        break;
                    }

                    if fl.starts_with("///") {
                        doc_comment = fl.trim_start_matches("///").trim().to_string();
                    } else if fl.starts_with("#[param(") {
                        // Parse #[param(min = 0.0, max = 100.0, step = 0.5, default = 3.0)]
                        let inner = fl.trim_start_matches("#[param(").trim_end_matches(")]");
                        for part in inner.split(',') {
                            let part = part.trim();
                            if let Some((k, v)) = part.split_once('=') {
                                let k = k.trim();
                                let v = v.trim().trim_matches('"');
                                match k {
                                    "min" => param_attrs.0 = v.to_string(),
                                    "max" => param_attrs.1 = v.to_string(),
                                    "step" => param_attrs.2 = v.to_string(),
                                    "default" => param_attrs.3 = v.to_string(),
                                    _ => {}
                                }
                            }
                        }
                    } else if fl.starts_with("pub ") && fl.contains(':') {
                        // pub radius: f32,
                        let field_str = fl.strip_prefix("pub ").unwrap_or(fl);
                        if let Some((fname, ftype)) = field_str.split_once(':') {
                            let fname = fname.trim().to_string();
                            let ftype = ftype.trim().trim_end_matches(',').trim().to_string();
                            let default = if param_attrs.3.is_empty() {
                                default_for_type(&ftype)
                            } else {
                                param_attrs.3.clone()
                            };
                            fields.push(ParamField {
                                name: fname,
                                param_type: ftype,
                                min: param_attrs.0.clone(),
                                max: param_attrs.1.clone(),
                                step: param_attrs.2.clone(),
                                default_val: default,
                                label: doc_comment.clone(),
                            });
                            doc_comment.clear();
                            param_attrs =
                                ("null".into(), "null".into(), "null".into(), String::new());
                        }
                    }
                    j += 1;
                }

                if !fields.is_empty() {
                    result.insert(struct_name, fields);
                }
            }
        }
        i += 1;
    }
    result
}

fn default_for_type(ty: &str) -> String {
    match ty {
        "f32" | "f64" => "0.0".to_string(),
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" => "0".to_string(),
        "bool" => "false".to_string(),
        _ => "null".to_string(),
    }
}

fn default_range_for_type(ty: &str) -> (&str, &str, &str, &str) {
    match ty {
        "f32" => ("0.0", "1.0", "0.01", "0.0"),
        "u32" => ("0", "1000", "1", "0"),
        "bool" => ("null", "null", "null", "false"),
        _ => ("null", "null", "null", "null"),
    }
}

fn to_pascal_case(snake: &str) -> String {
    snake
        .split('_')
        .map(|seg| {
            let mut c = seg.chars();
            match c.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
            }
        })
        .collect()
}

fn to_wit_name(rust_name: &str) -> String {
    rust_name.replace('_', "-")
}

fn to_wit_type(rust_type: &str) -> String {
    match rust_type {
        "f32" => "f32".to_string(),
        "f64" => "f64".to_string(),
        "u8" => "u8".to_string(),
        "u16" => "u16".to_string(),
        "u32" => "u32".to_string(),
        "i32" => "s32".to_string(),
        "i64" => "s64".to_string(),
        "bool" => "bool".to_string(),
        other => other.to_string(),
    }
}
