//! Build script — scans for #[register_filter] annotations and generates:
//! 1. WIT filter declarations (printed to stderr for manual review/copy)
//! 2. Rust adapter dispatch code (written to $OUT_DIR/generated_filter_adapter.rs)
//!
//! The generated adapter code is included in adapter/mod.rs via:
//!   include!(concat!(env!("OUT_DIR"), "/generated_filter_adapter.rs"));

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let filters_path = Path::new(&manifest_dir).join("src/domain/filters.rs");

    // Tell cargo to rerun if filters.rs changes
    println!("cargo:rerun-if-changed=src/domain/filters.rs");

    if !filters_path.exists() {
        return;
    }

    let source = fs::read_to_string(&filters_path).unwrap();
    let filters = parse_registered_filters(&source);

    if filters.is_empty() {
        // Write empty generated file
        let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
        fs::write(
            out_dir.join("generated_filter_adapter.rs"),
            "// No registered filters found\n",
        )
        .unwrap();
        return;
    }

    // Print summary to stderr (visible during build)
    eprintln!("rasmcore build.rs: Found {} registered filter(s):", filters.len());
    for f in &filters {
        let params: Vec<String> = f.params.iter().map(|(n, t)| format!("{n}: {t}")).collect();
        eprintln!("  {} ({}): {}({})", f.name, f.category, f.fn_name, params.join(", "));
    }

    // Generate WIT declarations (printed to stderr for review)
    eprintln!("\n--- Generated WIT (copy to filters.wit if new filters added) ---");
    for f in &filters {
        let wit_params = f
            .params
            .iter()
            .map(|(n, t)| format!("{}: {}", to_wit_name(n), to_wit_type(t)))
            .collect::<Vec<_>>()
            .join(", ");

        let wit_sig = if wit_params.is_empty() {
            format!(
                "    {}: func(pixels: buffer, info: image-info) -> result<buffer, rasmcore-error>;",
                to_wit_name(&f.name)
            )
        } else {
            format!(
                "    {}: func(pixels: buffer, info: image-info, {}) -> result<buffer, rasmcore-error>;",
                to_wit_name(&f.name),
                wit_params
            )
        };
        eprintln!("{wit_sig}");
    }
    eprintln!("--- End WIT ---\n");

    // Generate Rust adapter dispatch code
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let mut adapter_code = String::new();
    adapter_code.push_str("// Auto-generated by build.rs from #[register_filter] annotations.\n");
    adapter_code.push_str("// Do not edit — regenerate by changing filters.rs and rebuilding.\n\n");

    for f in &filters {
        let fn_name = &f.fn_name;
        let params_sig: Vec<String> = f
            .params
            .iter()
            .map(|(n, t)| format!("{n}: {t}"))
            .collect();
        let params_call: Vec<String> = f.params.iter().map(|(n, _)| n.clone()).collect();

        let full_sig = if params_sig.is_empty() {
            "pixels: Vec<u8>, info: types::ImageInfo".to_string()
        } else {
            format!(
                "pixels: Vec<u8>, info: types::ImageInfo, {}",
                params_sig.join(", ")
            )
        };

        let full_call = if params_call.is_empty() {
            "&pixels, &di".to_string()
        } else {
            format!("&pixels, &di, {}", params_call.join(", "))
        };

        adapter_code.push_str(&format!(
            "fn {fn_name}({full_sig}) -> Result<Vec<u8>, RasmcoreError> {{\n"
        ));
        adapter_code.push_str("    let di = to_domain_image_info(&info);\n");
        adapter_code.push_str(&format!(
            "    domain::filters::{fn_name}({full_call}).map_err(to_wit_error)\n"
        ));
        adapter_code.push_str("}\n\n");
    }

    fs::write(
        out_dir.join("generated_filter_adapter.rs"),
        &adapter_code,
    )
    .unwrap();

    eprintln!(
        "rasmcore build.rs: Generated adapter code at {}/generated_filter_adapter.rs",
        out_dir.display()
    );
}

/// Parsed filter registration.
struct FilterReg {
    name: String,
    category: String,
    fn_name: String,
    params: Vec<(String, String)>, // (param_name, rust_type)
}

/// Parse #[register_filter(...)] annotations from Rust source.
fn parse_registered_filters(source: &str) -> Vec<FilterReg> {
    let mut filters = Vec::new();

    // Simple regex-based parsing (avoids full syn in build.rs for speed)
    // Pattern: #[register_filter(name = "...", category = "...")] or
    //          #[rasmcore_macros::register_filter(name = "...", category = "...")]
    //          pub fn name(pixels: &[u8], info: &ImageInfo, param: type, ...) -> Result<...>

    let lines: Vec<&str> = source.lines().collect();
    let mut i = 0;
    while i < lines.len() {
        let line = lines[i].trim();

        // Look for register_filter attribute
        if line.contains("register_filter(") && line.contains("name") {
            // Extract name and category
            let name = extract_string_attr(line, "name");
            let category = extract_string_attr(line, "category");

            if let (Some(name), Some(category)) = (name, category) {
                // Find the next pub fn and collect its full signature (may span multiple lines)
                let mut j = i + 1;
                while j < lines.len() {
                    let fn_line = lines[j].trim();
                    if fn_line.starts_with("pub fn ") {
                        // Collect lines until we find the closing ')' and '->'
                        let mut full_sig = fn_line.to_string();
                        while !full_sig.contains("->") && j + 1 < lines.len() {
                            j += 1;
                            full_sig.push(' ');
                            full_sig.push_str(lines[j].trim());
                        }
                        if let Some(reg) = parse_fn_signature(&full_sig, &name, &category) {
                            filters.push(reg);
                        }
                        break;
                    }
                    if fn_line.starts_with("//") || fn_line.starts_with("///") || fn_line.is_empty()
                    {
                        j += 1;
                        continue;
                    }
                    break; // unexpected line, skip
                }
            }
        }
        i += 1;
    }

    filters
}

fn extract_string_attr(line: &str, attr: &str) -> Option<String> {
    let pattern = format!("{attr} = \"");
    if let Some(start) = line.find(&pattern) {
        let rest = &line[start + pattern.len()..];
        if let Some(end) = rest.find('"') {
            return Some(rest[..end].to_string());
        }
    }
    None
}

fn parse_fn_signature(line: &str, name: &str, category: &str) -> Option<FilterReg> {
    // pub fn blur(pixels: &[u8], info: &ImageInfo, radius: f32) -> Result<...>
    let fn_start = line.find("fn ")? + 3;
    let paren_start = line.find('(')?;
    let fn_name = line[fn_start..paren_start].trim().to_string();

    let paren_end = line.find(')')?;
    let params_str = &line[paren_start + 1..paren_end];

    // Parse params, skip pixels and info
    let mut params = Vec::new();
    for param in params_str.split(',') {
        let param = param.trim();
        if param.is_empty()
            || param.contains("pixels")
            || param.contains("info")
            || param.contains("&[u8]")
            || param.contains("ImageInfo")
        {
            continue;
        }
        // name: type
        let parts: Vec<&str> = param.splitn(2, ':').collect();
        if parts.len() == 2 {
            let pname = parts[0].trim().to_string();
            let ptype = parts[1].trim().to_string();
            params.push((pname, ptype));
        }
    }

    Some(FilterReg {
        name: name.to_string(),
        category: category.to_string(),
        fn_name,
        params,
    })
}

fn to_wit_name(rust_name: &str) -> String {
    rust_name.replace('_', "-")
}

fn to_wit_type(rust_type: &str) -> String {
    match rust_type {
        "f32" => "f32".to_string(),
        "f64" => "f64".to_string(),
        "u8" => "u8".to_string(),
        "u16" => "u16".to_string(),
        "u32" => "u32".to_string(),
        "i32" => "s32".to_string(),
        "i64" => "s64".to_string(),
        "bool" => "bool".to_string(),
        other => other.to_string(),
    }
}
