// Command typegen generates typed Go wrappers from a rasmcore manifest.
//
// Usage:
//
//	go run github.com/ArtProcessors/rasmcore-go/cmd/typegen manifest.json > rasmcore_typed.go
//	go run github.com/ArtProcessors/rasmcore-go/cmd/typegen manifest.json -o rasmcore_typed.go
//
// Reads param-manifest.json and emits a typed Go file with methods for
// all operations. The generated code extends the dynamic RcImage.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"
)

type paramMeta struct {
	Name    string      `json:"name"`
	Type    string      `json:"type"`
	Min     *float64    `json:"min"`
	Max     *float64    `json:"max"`
	Step    *float64    `json:"step"`
	Default interface{} `json:"default"`
	Label   string      `json:"label"`
}

type operationMeta struct {
	Name      string      `json:"name"`
	Category  string      `json:"category"`
	Reference string      `json:"reference"`
	Params    []paramMeta `json:"params"`
}

type manifest struct {
	Filters []operationMeta `json:"filters"`
}

func rustTypeToGo(t string) string {
	switch t {
	case "f32":
		return "float32"
	case "f64":
		return "float64"
	case "u8":
		return "uint8"
	case "u16":
		return "uint16"
	case "u32":
		return "uint32"
	case "u64":
		return "uint64"
	case "i32":
		return "int32"
	case "i64":
		return "int64"
	case "bool":
		return "bool"
	case "string", "String":
		return "string"
	default:
		if strings.HasPrefix(t, "list<") {
			return "[]float64"
		}
		return "interface{}"
	}
}

func toPascalCase(s string) string {
	var b strings.Builder
	upper := true
	for _, r := range s {
		if r == '_' || r == '-' {
			upper = true
			continue
		}
		if upper {
			b.WriteRune(unicode.ToUpper(r))
			upper = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func toSnakeCase(s string) string {
	return strings.ReplaceAll(strings.ReplaceAll(s, "-", "_"), " ", "_")
}

func main() {
	output := flag.String("o", "", "Output file (default: stdout)")
	flag.Parse()

	if flag.NArg() < 1 {
		fmt.Fprintln(os.Stderr, "Usage: typegen <manifest.json> [-o output.go]")
		os.Exit(1)
	}

	manifestPath := flag.Arg(0)
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: %v\n", err)
		os.Exit(1)
	}

	var m manifest
	if err := json.Unmarshal(data, &m); err != nil {
		fmt.Fprintf(os.Stderr, "ERROR: invalid JSON: %v\n", err)
		os.Exit(1)
	}

	// Read hash
	hashPath := filepath.Join(filepath.Dir(manifestPath), "param-manifest.hash")
	hashBytes, _ := os.ReadFile(hashPath)
	manifestHash := strings.TrimSpace(string(hashBytes))

	fmt.Fprintf(os.Stderr, "Read manifest: %d operations, hash=%s\n", len(m.Filters), manifestHash[:min(8, len(manifestHash))])

	code := generateTypedSDK(&m, manifestHash)

	if *output != "" {
		if err := os.WriteFile(*output, []byte(code), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "Generated: %s\n", *output)
	} else {
		fmt.Print(code)
	}
}

func generateTypedSDK(m *manifest, manifestHash string) string {
	var b strings.Builder

	b.WriteString("// Auto-generated by rasmcore typegen\n")
	b.WriteString(fmt.Sprintf("// Module manifest hash: %s\n", manifestHash))
	b.WriteString(fmt.Sprintf("// Operations: %d\n", len(m.Filters)))
	b.WriteString("//\n")
	b.WriteString("// Do not edit — regenerate with:\n")
	b.WriteString("//   go run github.com/ArtProcessors/rasmcore-go/cmd/typegen <manifest.json>\n")
	b.WriteString("\npackage rasmcore\n\n")
	b.WriteString("import \"fmt\"\n\n")
	b.WriteString(fmt.Sprintf("const ManifestHash = %q\n\n", manifestHash))

	// Generate filter methods
	for _, op := range m.Filters {
		methodName := toPascalCase(op.Name)
		doc := op.Reference
		if doc == "" {
			doc = op.Name + " filter"
		}

		// Build Go params
		var goParams []string
		var mapEntries []string
		for _, p := range op.Params {
			goName := toSnakeCase(p.Name)
			goType := rustTypeToGo(p.Type)
			goParams = append(goParams, fmt.Sprintf("%s %s", goName, goType))
			mapEntries = append(mapEntries, fmt.Sprintf("%q: %s", p.Name, goName))
		}

		sig := strings.Join(goParams, ", ")

		b.WriteString(fmt.Sprintf("// %s — %s\n", methodName, doc))
		b.WriteString(fmt.Sprintf("func (r *RcImage) %s(%s) *RcImage {\n", methodName, sig))

		if len(mapEntries) > 0 {
			b.WriteString(fmt.Sprintf("\treturn r.Apply(%q, map[string]any{%s})\n",
				op.Name, strings.Join(mapEntries, ", ")))
		} else {
			b.WriteString(fmt.Sprintf("\treturn r.Apply(%q, nil)\n", op.Name))
		}
		b.WriteString("}\n\n")
	}

	// Generate encode methods
	formats := []string{"jpeg", "png", "webp", "avif", "tiff", "bmp", "ico", "qoi", "gif"}
	for _, fmt_ := range formats {
		methodName := "To" + toPascalCase(fmt_)
		b.WriteString(fmt.Sprintf("// %s encodes as %s.\n", methodName, strings.ToUpper(fmt_)))
		b.WriteString(fmt.Sprintf("func (r *RcImage) %s(config map[string]any) ([]byte, error) {\n", methodName))
		b.WriteString(fmt.Sprintf("\treturn r.Encode(%q, config)\n", fmt_))
		b.WriteString("}\n\n")
	}

	// Suppress unused import
	b.WriteString("var _ = fmt.Sprintf\n")

	return b.String()
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}
