// Auto-generated by scripts/generate-fluent-sdk.js
// Do not edit — regenerate with: node scripts/generate-fluent-sdk.js
//
// Generated from 20 chainable + 10 terminal operations

import type { ImagePipeline, NodeId, ImageInfo, Buffer as WasmBuffer } from '../../demo/sdk/interfaces/rasmcore-image-pipeline.js';
import type { AvifWriteConfig, BlendMode, BmpWriteConfig, ExifOrientation, FlipDirection, GifWriteConfig, IcoWriteConfig, JpegWriteConfig, MetadataSet, PixelFormat, PngWriteConfig, QoiWriteConfig, ResizeFilter, Rotation, TiffWriteConfig, WebpWriteConfig } from '../../demo/sdk/interfaces/rasmcore-image-pipeline.js';

/**
 * Fluent image processing chain.
 *
 * ```typescript
 * const result = await rcimage.load(bytes)
 *   .blur(3.0)
 *   .resize(800, 600, 'lanczos3')
 *   .toJpeg({ quality: 85 });
 * ```
 *
 * All operations are lazy — pixels are only computed when a terminal
 * method (toJpeg, toPng, etc.) is called.
 */
export class RcImage {
  private pipeline: ImagePipeline;
  private nodeId: number;

  /** @internal Use rcimage.load() instead */
  constructor(pipeline: ImagePipeline, nodeId: number) {
    this.pipeline = pipeline;
    this.nodeId = nodeId;
  }

  // ─── Runtime Validation ───

  private static assertNumber(name: string, value: unknown): asserts value is number {
    if (typeof value !== 'number' || Number.isNaN(value)) {
      throw new TypeError(`${name} must be a number, got ${typeof value}`);
    }
  }

  private static assertString(name: string, value: unknown): asserts value is string {
    if (typeof value !== 'string') {
      throw new TypeError(`${name} must be a string, got ${typeof value}`);
    }
  }

  private static assertUint8Array(name: string, value: unknown): asserts value is Uint8Array {
    if (!(value instanceof Uint8Array)) {
      throw new TypeError(`${name} must be a Uint8Array, got ${typeof value}`);
    }
  }

  /** Get image info (dimensions, format) without computing pixels. */
  get info(): ImageInfo {
    return this.pipeline.nodeInfo(this.nodeId);
  }

  /** Create a branch — both chains share the pipeline but diverge from here. */
  fork(): RcImage {
    return new RcImage(this.pipeline, this.nodeId);
  }

  // ─── Chainable Operations (lazy, return RcImage) ───

  resize(width: number, height: number, filter: ResizeFilter): RcImage {
    RcImage.assertNumber('width', width);
    RcImage.assertNumber('height', height);
    this.nodeId = this.pipeline.resize(this.nodeId, width, height, filter);
    return this;
  }

  crop(x: number, y: number, width: number, height: number): RcImage {
    RcImage.assertNumber('x', x);
    RcImage.assertNumber('y', y);
    RcImage.assertNumber('width', width);
    RcImage.assertNumber('height', height);
    this.nodeId = this.pipeline.crop(this.nodeId, x, y, width, height);
    return this;
  }

  rotate(angle: Rotation): RcImage {
    this.nodeId = this.pipeline.rotate(this.nodeId, angle);
    return this;
  }

  flip(direction: FlipDirection): RcImage {
    this.nodeId = this.pipeline.flip(this.nodeId, direction);
    return this;
  }

  convertFormat(target: PixelFormat): RcImage {
    this.nodeId = this.pipeline.convertFormat(this.nodeId, target);
    return this;
  }

  iccToSrgb(iccProfile: Buffer): RcImage {
    this.nodeId = this.pipeline.iccToSrgb(this.nodeId, iccProfile);
    return this;
  }

  autoOrient(orientation: ExifOrientation): RcImage {
    this.nodeId = this.pipeline.autoOrient(this.nodeId, orientation);
    return this;
  }

  blur(radius: number): RcImage {
    RcImage.assertNumber('radius', radius);
    this.nodeId = this.pipeline.blur(this.nodeId, radius);
    return this;
  }

  sharpen(amount: number): RcImage {
    RcImage.assertNumber('amount', amount);
    this.nodeId = this.pipeline.sharpen(this.nodeId, amount);
    return this;
  }

  brightness(amount: number): RcImage {
    RcImage.assertNumber('amount', amount);
    this.nodeId = this.pipeline.brightness(this.nodeId, amount);
    return this;
  }

  contrast(amount: number): RcImage {
    RcImage.assertNumber('amount', amount);
    this.nodeId = this.pipeline.contrast(this.nodeId, amount);
    return this;
  }

  grayscale(): RcImage {
    this.nodeId = this.pipeline.grayscale(this.nodeId);
    return this;
  }

  convolve(kernel: Float32Array, kernelWidth: number, kernelHeight: number, divisor: number): RcImage {
    RcImage.assertNumber('kernelWidth', kernelWidth);
    RcImage.assertNumber('kernelHeight', kernelHeight);
    RcImage.assertNumber('divisor', divisor);
    this.nodeId = this.pipeline.convolve(this.nodeId, kernel, kernelWidth, kernelHeight, divisor);
    return this;
  }

  median(radius: number): RcImage {
    RcImage.assertNumber('radius', radius);
    this.nodeId = this.pipeline.median(this.nodeId, radius);
    return this;
  }

  sobel(): RcImage {
    this.nodeId = this.pipeline.sobel(this.nodeId);
    return this;
  }

  canny(lowThreshold: number, highThreshold: number): RcImage {
    RcImage.assertNumber('lowThreshold', lowThreshold);
    RcImage.assertNumber('highThreshold', highThreshold);
    this.nodeId = this.pipeline.canny(this.nodeId, lowThreshold, highThreshold);
    return this;
  }

  keepMetadata(): RcImage {
    this.nodeId = this.pipeline.keepMetadata(this.nodeId);
    return this;
  }

  setMetadata(value: string): RcImage {
    RcImage.assertString('value', value);
    this.nodeId = this.pipeline.setMetadata(this.nodeId, value);
    return this;
  }

  loadMetadata(): RcImage {
    this.nodeId = this.pipeline.loadMetadata(this.nodeId);
    return this;
  }

  stripMetadata(): RcImage {
    this.nodeId = this.pipeline.stripMetadata(this.nodeId);
    return this;
  }

  // ─── Multi-Image Operations ───

  /**
   * Load another image into the same pipeline for compositing.
   * Returns a new RcImage sharing this pipeline — apply filters, then pass to composite().
   */
  loadLayer(data: Uint8Array): RcImage {
    RcImage.assertUint8Array('data', data);
    const nodeId = this.pipeline.read(data as unknown as WasmBuffer);
    return new RcImage(this.pipeline, nodeId);
  }

  /**
   * Composite another image over this one.
   *
   * @param other - Foreground: an RcImage from loadLayer(), or raw Uint8Array bytes
   * @param opts - x/y offset (default 0,0) and blend mode (default Porter-Duff over)
   *
   * @example
   * // Simple: composite with raw bytes
   * bg.composite(fgBytes, { x: 10, y: 10 });
   *
   * // With filters on foreground:
   * const fg = bg.loadLayer(fgBytes).blur(2.0);
   * bg.composite(fg, { x: 10, y: 10, blend: 'multiply' });
   */
  composite(other: RcImage | Uint8Array, opts?: { x?: number, y?: number, blend?: BlendMode }): RcImage {
    let fgNodeId: number;
    if (other instanceof RcImage) {
      fgNodeId = other.nodeId;
    } else {
      RcImage.assertUint8Array('other', other);
      fgNodeId = this.pipeline.read(other as unknown as WasmBuffer);
    }
    const x = opts?.x ?? 0;
    const y = opts?.y ?? 0;
    const mode = opts?.blend ?? undefined;
    this.nodeId = this.pipeline.composite(fgNodeId, this.nodeId, x, y, mode);
    return this;
  }

  // ─── Terminal Operations (execute pipeline, return data) ───

  toJpeg(config: JpegWriteConfig, metadata?: MetadataSet): Uint8Array {
    return this.pipeline.writeJpeg(this.nodeId, config, metadata) as unknown as Uint8Array;
  }

  toPng(config: PngWriteConfig, metadata?: MetadataSet): Uint8Array {
    return this.pipeline.writePng(this.nodeId, config, metadata) as unknown as Uint8Array;
  }

  toWebp(config: WebpWriteConfig, metadata?: MetadataSet): Uint8Array {
    return this.pipeline.writeWebp(this.nodeId, config, metadata) as unknown as Uint8Array;
  }

  toAvif(config: AvifWriteConfig, metadata?: MetadataSet): Uint8Array {
    return this.pipeline.writeAvif(this.nodeId, config, metadata) as unknown as Uint8Array;
  }

  toTiff(config: TiffWriteConfig): Uint8Array {
    return this.pipeline.writeTiff(this.nodeId, config) as unknown as Uint8Array;
  }

  toBmp(config: BmpWriteConfig): Uint8Array {
    return this.pipeline.writeBmp(this.nodeId, config) as unknown as Uint8Array;
  }

  toIco(config: IcoWriteConfig): Uint8Array {
    return this.pipeline.writeIco(this.nodeId, config) as unknown as Uint8Array;
  }

  toQoi(config: QoiWriteConfig): Uint8Array {
    return this.pipeline.writeQoi(this.nodeId, config) as unknown as Uint8Array;
  }

  toGif(config: GifWriteConfig, metadata?: MetadataSet): Uint8Array {
    return this.pipeline.writeGif(this.nodeId, config, metadata) as unknown as Uint8Array;
  }

  to(format: string, quality?: number, metadata?: MetadataSet): Uint8Array {
    return this.pipeline.write(this.nodeId, format, quality, metadata) as unknown as Uint8Array;
  }
}

/**
 * rasmcore image processing — fluent chainable API.
 *
 * ```typescript
 * import { rcimage } from '@rasmcore/sdk';
 * const jpeg = rcimage.load(pngBytes).blur(3).resize(800, 600).toJpeg({ quality: 85 });
 * ```
 */
export const rcimage = {
  /**
   * Load image data and start a processing chain.
   * The image is not decoded until a terminal operation is called.
   */
  load(data: Uint8Array, pipelineModule?: { ImagePipeline: new () => ImagePipeline }): RcImage {
    if (!(data instanceof Uint8Array)) {
      throw new TypeError('load() requires a Uint8Array of image data');
    }
    if (data.length === 0) {
      throw new RangeError('load() requires non-empty image data');
    }
    if (!pipelineModule) {
      throw new Error('pipelineModule is required — pass the imported pipeline module');
    }
    const pipe = new pipelineModule.ImagePipeline();
    const nodeId = pipe.read(data as unknown as WasmBuffer);
    return new RcImage(pipe, nodeId);
  },
};
