// Code generated by cmd/generate; DO NOT EDIT.

package rcimg

func boolToFloat(v bool) float32 {
	if v {
		return 1.0
	}
	return 0.0
}

// AutoOrient applies the auto_orient operation.
func (c *Chain) AutoOrient(orientation float32) *Chain {
	return c.add("auto_orient", orientation)
}

// Rotate applies the rotate operation.
func (c *Chain) Rotate(rotation float32) *Chain {
	return c.add("rotate", rotation)
}

// Flip applies the flip operation.
func (c *Chain) Flip(direction float32) *Chain {
	return c.add("flip", direction)
}

// Crop applies the crop operation.
func (c *Chain) Crop(x uint32, y uint32, width uint32, height uint32) *Chain {
	return c.add("crop", float32(x), float32(y), float32(width), float32(height))
}

// Resize applies the resize operation.
func (c *Chain) Resize(width uint32, height uint32, filter float32) *Chain {
	return c.add("resize", float32(width), float32(height), filter)
}

// IccToSrgb applies the icc_to_srgb operation.
func (c *Chain) IccToSrgb(iccProfile float32) *Chain {
	return c.add("icc_to_srgb", iccProfile)
}

// PerspectiveCorrect applies the perspective_correct operation.
func (c *Chain) PerspectiveCorrect(strength float32) *Chain {
	return c.add("perspective_correct", strength)
}

// PerspectiveWarp applies the perspective_warp operation.
func (c *Chain) PerspectiveWarp(outWidth uint32, outHeight uint32) *Chain {
	return c.add("perspective_warp", float32(outWidth), float32(outHeight))
}

// Equalize applies the equalize operation.
func (c *Chain) Equalize() *Chain {
	return c.add("equalize")
}

// Dehaze applies the dehaze operation.
func (c *Chain) Dehaze(patchRadius uint32, omega float32, tMin float32) *Chain {
	return c.add("dehaze", float32(patchRadius), omega, tMin)
}

// RetinexMsr applies the retinex_msr operation.
func (c *Chain) RetinexMsr(sigmaSmall float32, sigmaMedium float32, sigmaLarge float32) *Chain {
	return c.add("retinex_msr", sigmaSmall, sigmaMedium, sigmaLarge)
}

// FrequencyHigh applies the frequency_high operation.
func (c *Chain) FrequencyHigh(sigma float32) *Chain {
	return c.add("frequency_high", sigma)
}

// VignettePowerlaw applies the vignette_powerlaw operation.
func (c *Chain) VignettePowerlaw(strength float32, falloff float32, fullWidth uint32, fullHeight uint32, offsetX uint32, offsetY uint32) *Chain {
	return c.add("vignette_powerlaw", strength, falloff, float32(fullWidth), float32(fullHeight), float32(offsetX), float32(offsetY))
}

// Normalize applies the normalize operation.
func (c *Chain) Normalize() *Chain {
	return c.add("normalize")
}

// AutoLevel applies the auto_level operation.
func (c *Chain) AutoLevel() *Chain {
	return c.add("auto_level")
}

// RetinexSsr applies the retinex_ssr operation.
func (c *Chain) RetinexSsr(sigma float32) *Chain {
	return c.add("retinex_ssr", sigma)
}

// Clahe applies the clahe operation.
func (c *Chain) Clahe(clipLimit float32, tileGrid uint32) *Chain {
	return c.add("clahe", clipLimit, float32(tileGrid))
}

// Clarity applies the clarity operation.
func (c *Chain) Clarity(amount float32, sigma float32) *Chain {
	return c.add("clarity", amount, sigma)
}

// PyramidDetailRemap applies the pyramid_detail_remap operation.
func (c *Chain) PyramidDetailRemap(sigma float32, numLevels uint32) *Chain {
	return c.add("pyramid_detail_remap", sigma, float32(numLevels))
}

// ShadowHighlight applies the shadow_highlight operation.
func (c *Chain) ShadowHighlight(shadows float32, highlights float32, whitepoint float32, radius float32, compress float32, shadowsCcorrect float32, highlightsCcorrect float32) *Chain {
	return c.add("shadow_highlight", shadows, highlights, whitepoint, radius, compress, shadowsCcorrect, highlightsCcorrect)
}

// FrequencyLow applies the frequency_low operation.
func (c *Chain) FrequencyLow(sigma float32) *Chain {
	return c.add("frequency_low", sigma)
}

// Dodge applies the dodge operation.
func (c *Chain) Dodge(exposure float32, rng uint32) *Chain {
	return c.add("dodge", exposure, float32(rng))
}

// Vignette applies the vignette operation.
func (c *Chain) Vignette(sigma float32, xInset uint32, yInset uint32, fullWidth uint32, fullHeight uint32, tileOffsetX uint32, tileOffsetY uint32) *Chain {
	return c.add("vignette", sigma, float32(xInset), float32(yInset), float32(fullWidth), float32(fullHeight), float32(tileOffsetX), float32(tileOffsetY))
}

// NlmDenoise applies the nlm_denoise operation.
func (c *Chain) NlmDenoise(h float32, patchSize uint32, searchSize uint32) *Chain {
	return c.add("nlm_denoise", h, float32(patchSize), float32(searchSize))
}

// RetinexMsrcr applies the retinex_msrcr operation.
func (c *Chain) RetinexMsrcr(sigmaSmall float32, sigmaMedium float32, sigmaLarge float32, alpha float32, beta float32) *Chain {
	return c.add("retinex_msrcr", sigmaSmall, sigmaMedium, sigmaLarge, alpha, beta)
}

// Burn applies the burn operation.
func (c *Chain) Burn(exposure float32, rng uint32) *Chain {
	return c.add("burn", exposure, float32(rng))
}

// SigmoidalContrast applies the sigmoidal_contrast operation.
func (c *Chain) SigmoidalContrast(strength float32, midpoint float32, sharpen bool) *Chain {
	return c.add("sigmoidal_contrast", strength, midpoint, boolToFloat(sharpen))
}

// Exposure applies the exposure operation.
func (c *Chain) Exposure(ev float32, offset float32, gammaCorrection float32) *Chain {
	return c.add("exposure", ev, offset, gammaCorrection)
}

// Gamma applies the gamma operation.
func (c *Chain) Gamma(gammaValue float32) *Chain {
	return c.add("gamma", gammaValue)
}

// Contrast applies the contrast operation.
func (c *Chain) Contrast(amount float32) *Chain {
	return c.add("contrast", amount)
}

// Levels applies the levels operation.
func (c *Chain) Levels(blackPoint float32, whitePoint float32, gamma float32) *Chain {
	return c.add("levels", blackPoint, whitePoint, gamma)
}

// Invert applies the invert operation.
func (c *Chain) Invert() *Chain {
	return c.add("invert")
}

// Brightness applies the brightness operation.
func (c *Chain) Brightness(amount float32) *Chain {
	return c.add("brightness", amount)
}

// ColorBalance applies the color_balance operation.
func (c *Chain) ColorBalance(shadowCyanRed float32, shadowMagentaGreen float32, shadowYellowBlue float32, midtoneCyanRed float32, midtoneMagentaGreen float32, midtoneYellowBlue float32, highlightCyanRed float32, highlightMagentaGreen float32, highlightYellowBlue float32, preserveLuminosity bool) *Chain {
	return c.add("color_balance", shadowCyanRed, shadowMagentaGreen, shadowYellowBlue, midtoneCyanRed, midtoneMagentaGreen, midtoneYellowBlue, highlightCyanRed, highlightMagentaGreen, highlightYellowBlue, boolToFloat(preserveLuminosity))
}

// Posterize applies the posterize operation.
func (c *Chain) Posterize(levels uint8) *Chain {
	return c.add("posterize", float32(levels))
}

// CurvesGreen applies the curves_green operation.
func (c *Chain) CurvesGreen(points float32) *Chain {
	return c.add("curves_green", points)
}

// LiftGammaGain applies the lift_gamma_gain operation.
func (c *Chain) LiftGammaGain(liftR float32, liftG float32, liftB float32, gammaR float32, gammaG float32, gammaB float32, gainR float32, gainG float32, gainB float32) *Chain {
	return c.add("lift_gamma_gain", liftR, liftG, liftB, gammaR, gammaG, gammaB, gainR, gainG, gainB)
}

// CurvesRed applies the curves_red operation.
func (c *Chain) CurvesRed(points float32) *Chain {
	return c.add("curves_red", points)
}

// ApplyHaldLut applies the apply_hald_lut operation.
func (c *Chain) ApplyHaldLut(haldDim uint32) *Chain {
	return c.add("apply_hald_lut", float32(haldDim))
}

// ApplyCubeLut applies the apply_cube_lut operation.
func (c *Chain) ApplyCubeLut(cubeData float32) *Chain {
	return c.add("apply_cube_lut", cubeData)
}

// SplitToning applies the split_toning operation.
func (c *Chain) SplitToning(highlightHue float32, shadowHue float32, balance float32) *Chain {
	return c.add("split_toning", highlightHue, shadowHue, balance)
}

// HueVsSat applies the hue_vs_sat operation.
func (c *Chain) HueVsSat(points float32) *Chain {
	return c.add("hue_vs_sat", points)
}

// CurvesMaster applies the curves_master operation.
func (c *Chain) CurvesMaster(points float32) *Chain {
	return c.add("curves_master", points)
}

// CurvesBlue applies the curves_blue operation.
func (c *Chain) CurvesBlue(points float32) *Chain {
	return c.add("curves_blue", points)
}

// HueVsLum applies the hue_vs_lum operation.
func (c *Chain) HueVsLum(points float32) *Chain {
	return c.add("hue_vs_lum", points)
}

// AscCdl applies the asc_cdl operation.
func (c *Chain) AscCdl(slopeR float32, slopeG float32, slopeB float32, offsetR float32, offsetG float32, offsetB float32, powerR float32, powerG float32, powerB float32) *Chain {
	return c.add("asc_cdl", slopeR, slopeG, slopeB, offsetR, offsetG, offsetB, powerR, powerG, powerB)
}

// LumVsSat applies the lum_vs_sat operation.
func (c *Chain) LumVsSat(points float32) *Chain {
	return c.add("lum_vs_sat", points)
}

// SatVsSat applies the sat_vs_sat operation.
func (c *Chain) SatVsSat(points float32) *Chain {
	return c.add("sat_vs_sat", points)
}

// ConnectedComponents applies the connected_components operation.
func (c *Chain) ConnectedComponents(connectivity uint32) *Chain {
	return c.add("connected_components", float32(connectivity))
}

// HoughLines applies the hough_lines operation.
func (c *Chain) HoughLines(threshold uint32, minLength uint32, maxGap uint32) *Chain {
	return c.add("hough_lines", float32(threshold), float32(minLength), float32(maxGap))
}

// Depolar applies the depolar operation.
func (c *Chain) Depolar() *Chain {
	return c.add("depolar")
}

// Wave applies the wave operation.
func (c *Chain) Wave(amplitude float32, wavelength float32, vertical float32) *Chain {
	return c.add("wave", amplitude, wavelength, vertical)
}

// Polar applies the polar operation.
func (c *Chain) Polar() *Chain {
	return c.add("polar")
}

// Barrel applies the barrel operation.
func (c *Chain) Barrel(k1 float32, k2 float32) *Chain {
	return c.add("barrel", k1, k2)
}

// MeshWarp applies the mesh_warp operation.
func (c *Chain) MeshWarp(gridCols uint32, gridRows uint32, gridJson float32) *Chain {
	return c.add("mesh_warp", float32(gridCols), float32(gridRows), gridJson)
}

// Ripple applies the ripple operation.
func (c *Chain) Ripple(amplitude float32, wavelength float32, centerX float32, centerY float32) *Chain {
	return c.add("ripple", amplitude, wavelength, centerX, centerY)
}

// Swirl applies the swirl operation.
func (c *Chain) Swirl(angle float32, radius float32) *Chain {
	return c.add("swirl", angle, radius)
}

// Spherize applies the spherize operation.
func (c *Chain) Spherize(amount float32) *Chain {
	return c.add("spherize", amount)
}

// TonemapDrago applies the tonemap_drago operation.
func (c *Chain) TonemapDrago(bias float32) *Chain {
	return c.add("tonemap_drago", bias)
}

// TonemapReinhard applies the tonemap_reinhard operation.
func (c *Chain) TonemapReinhard() *Chain {
	return c.add("tonemap_reinhard")
}

// TonemapFilmic applies the tonemap_filmic operation.
func (c *Chain) TonemapFilmic(shoulderStrength float32, linearStrength float32, linearAngle float32, toeStrength float32, toeNumerator float32) *Chain {
	return c.add("tonemap_filmic", shoulderStrength, linearStrength, linearAngle, toeStrength, toeNumerator)
}

// Sepia applies the sepia operation.
func (c *Chain) Sepia(intensity float32) *Chain {
	return c.add("sepia", intensity)
}

// Saturate applies the saturate operation.
func (c *Chain) Saturate(factor float32) *Chain {
	return c.add("saturate", factor)
}

// PhotoFilter applies the photo_filter operation.
func (c *Chain) PhotoFilter(colorR uint32, colorG uint32, colorB uint32, density float32, preserveLuminosity uint32) *Chain {
	return c.add("photo_filter", float32(colorR), float32(colorG), float32(colorB), density, float32(preserveLuminosity))
}

// HueRotate applies the hue_rotate operation.
func (c *Chain) HueRotate(degrees float32) *Chain {
	return c.add("hue_rotate", degrees)
}

// Quantize applies the quantize operation.
func (c *Chain) Quantize(maxColors uint32) *Chain {
	return c.add("quantize", float32(maxColors))
}

// GradientMap applies the gradient_map operation.
func (c *Chain) GradientMap(stops float32) *Chain {
	return c.add("gradient_map", stops)
}

// Modulate applies the modulate operation.
func (c *Chain) Modulate(brightness float32, saturation float32, hue float32) *Chain {
	return c.add("modulate", brightness, saturation, hue)
}

// SelectiveColor applies the selective_color operation.
func (c *Chain) SelectiveColor(targetHue float32, hueRange float32, hueShift float32, saturation float32, lightness float32) *Chain {
	return c.add("selective_color", targetHue, hueRange, hueShift, saturation, lightness)
}

// ChannelMixer applies the channel_mixer operation.
func (c *Chain) ChannelMixer(rr float32, rg float32, rb float32, gr float32, gg float32, gb float32, br float32, bg float32, bb float32) *Chain {
	return c.add("channel_mixer", rr, rg, rb, gr, gg, gb, br, bg, bb)
}

// LabSharpen applies the lab_sharpen operation.
func (c *Chain) LabSharpen(amount float32, radius float32) *Chain {
	return c.add("lab_sharpen", amount, radius)
}

// LabAdjust applies the lab_adjust operation.
func (c *Chain) LabAdjust(aOffset float32, bOffset float32) *Chain {
	return c.add("lab_adjust", aOffset, bOffset)
}

// WhiteBalanceGrayWorld applies the white_balance_gray_world operation.
func (c *Chain) WhiteBalanceGrayWorld() *Chain {
	return c.add("white_balance_gray_world")
}

// DitherOrdered applies the dither_ordered operation.
func (c *Chain) DitherOrdered(maxColors uint32, mapSize uint32) *Chain {
	return c.add("dither_ordered", float32(maxColors), float32(mapSize))
}

// DitherFloydSteinberg applies the dither_floyd_steinberg operation.
func (c *Chain) DitherFloydSteinberg(maxColors uint32) *Chain {
	return c.add("dither_floyd_steinberg", float32(maxColors))
}

// Colorize applies the colorize operation.
func (c *Chain) Colorize(target float32, amount float32) *Chain {
	return c.add("colorize", target, amount)
}

// KmeansQuantize applies the kmeans_quantize operation.
func (c *Chain) KmeansQuantize(k uint32, maxIterations uint32, seed uint32) *Chain {
	return c.add("kmeans_quantize", float32(k), float32(maxIterations), float32(seed))
}

// SparseColor applies the sparse_color operation.
func (c *Chain) SparseColor(points float32, power float32) *Chain {
	return c.add("sparse_color", points, power)
}

// Vibrance applies the vibrance operation.
func (c *Chain) Vibrance(amount float32) *Chain {
	return c.add("vibrance", amount)
}

// WhiteBalanceTemperature applies the white_balance_temperature operation.
func (c *Chain) WhiteBalanceTemperature(temperature float32, tint float32) *Chain {
	return c.add("white_balance_temperature", temperature, tint)
}

// OilPaint applies the oil_paint operation.
func (c *Chain) OilPaint(radius uint32) *Chain {
	return c.add("oil_paint", float32(radius))
}

// PoissonNoise applies the poisson_noise operation.
func (c *Chain) PoissonNoise(scale float32, seed uint64) *Chain {
	return c.add("poisson_noise", scale, float32(seed))
}

// Solarize applies the solarize operation.
func (c *Chain) Solarize(threshold uint8) *Chain {
	return c.add("solarize", float32(threshold))
}

// SaltPepperNoise applies the salt_pepper_noise operation.
func (c *Chain) SaltPepperNoise(density float32, seed uint64) *Chain {
	return c.add("salt_pepper_noise", density, float32(seed))
}

// FilmGrain applies the film_grain operation.
func (c *Chain) FilmGrain(amount float32, size float32, seed uint32) *Chain {
	return c.add("film_grain", amount, size, float32(seed))
}

// Pixelate applies the pixelate operation.
func (c *Chain) Pixelate(blockSize uint32) *Chain {
	return c.add("pixelate", float32(blockSize))
}

// UniformNoise applies the uniform_noise operation.
func (c *Chain) UniformNoise(rng float32, seed uint64) *Chain {
	return c.add("uniform_noise", rng, float32(seed))
}

// GaussianNoise applies the gaussian_noise operation.
func (c *Chain) GaussianNoise(amount float32, mean float32, sigma float32, seed uint64) *Chain {
	return c.add("gaussian_noise", amount, mean, sigma, float32(seed))
}

// Halftone applies the halftone operation.
func (c *Chain) Halftone(dotSize float32, angleOffset float32) *Chain {
	return c.add("halftone", dotSize, angleOffset)
}

// Emboss applies the emboss operation.
func (c *Chain) Emboss() *Chain {
	return c.add("emboss")
}

// EvaluateMultiply applies the evaluate_multiply operation.
func (c *Chain) EvaluateMultiply(factor float32) *Chain {
	return c.add("evaluate_multiply", factor)
}

// EvaluateSubtract applies the evaluate_subtract operation.
func (c *Chain) EvaluateSubtract(value float32) *Chain {
	return c.add("evaluate_subtract", value)
}

// EvaluateMin applies the evaluate_min operation.
func (c *Chain) EvaluateMin(value uint8) *Chain {
	return c.add("evaluate_min", float32(value))
}

// EvaluateAbs applies the evaluate_abs operation.
func (c *Chain) EvaluateAbs() *Chain {
	return c.add("evaluate_abs")
}

// EvaluateLog applies the evaluate_log operation.
func (c *Chain) EvaluateLog(base float32) *Chain {
	return c.add("evaluate_log", base)
}

// EvaluateAdd applies the evaluate_add operation.
func (c *Chain) EvaluateAdd(value float32) *Chain {
	return c.add("evaluate_add", value)
}

// EvaluatePow applies the evaluate_pow operation.
func (c *Chain) EvaluatePow(exponent float32) *Chain {
	return c.add("evaluate_pow", exponent)
}

// EvaluateMax applies the evaluate_max operation.
func (c *Chain) EvaluateMax(value uint8) *Chain {
	return c.add("evaluate_max", float32(value))
}

// EvaluateDivide applies the evaluate_divide operation.
func (c *Chain) EvaluateDivide(factor float32) *Chain {
	return c.add("evaluate_divide", factor)
}

// ThresholdBinary applies the threshold_binary operation.
func (c *Chain) ThresholdBinary(thresh uint8, maxValue uint8) *Chain {
	return c.add("threshold_binary", float32(thresh), float32(maxValue))
}

// TriangleThreshold applies the triangle_threshold operation.
func (c *Chain) TriangleThreshold() *Chain {
	return c.add("triangle_threshold")
}

// OtsuThreshold applies the otsu_threshold operation.
func (c *Chain) OtsuThreshold() *Chain {
	return c.add("otsu_threshold")
}

// AdaptiveThreshold applies the adaptive_threshold operation.
func (c *Chain) AdaptiveThreshold(maxValue uint8, method uint32, blockSize uint32, cVal float32) *Chain {
	return c.add("adaptive_threshold", float32(maxValue), float32(method), float32(blockSize), cVal)
}

// MorphClose applies the morph_close operation.
func (c *Chain) MorphClose(ksize uint32, shape uint32) *Chain {
	return c.add("morph_close", float32(ksize), float32(shape))
}

// MorphTophat applies the morph_tophat operation.
func (c *Chain) MorphTophat(ksize uint32, shape uint32) *Chain {
	return c.add("morph_tophat", float32(ksize), float32(shape))
}

// MorphGradient applies the morph_gradient operation.
func (c *Chain) MorphGradient(ksize uint32, shape uint32) *Chain {
	return c.add("morph_gradient", float32(ksize), float32(shape))
}

// Erode applies the erode operation.
func (c *Chain) Erode(ksize uint32, shape uint32) *Chain {
	return c.add("erode", float32(ksize), float32(shape))
}

// MorphBlackhat applies the morph_blackhat operation.
func (c *Chain) MorphBlackhat(ksize uint32, shape uint32) *Chain {
	return c.add("morph_blackhat", float32(ksize), float32(shape))
}

// MorphOpen applies the morph_open operation.
func (c *Chain) MorphOpen(ksize uint32, shape uint32) *Chain {
	return c.add("morph_open", float32(ksize), float32(shape))
}

// Skeletonize applies the skeletonize operation.
func (c *Chain) Skeletonize(maxIterations uint32) *Chain {
	return c.add("skeletonize", float32(maxIterations))
}

// Dilate applies the dilate operation.
func (c *Chain) Dilate(ksize uint32, shape uint32) *Chain {
	return c.add("dilate", float32(ksize), float32(shape))
}

// GuidedFilter applies the guided_filter operation.
func (c *Chain) GuidedFilter(radius uint32, epsilon float32) *Chain {
	return c.add("guided_filter", float32(radius), epsilon)
}

// LensBlur applies the lens_blur operation.
func (c *Chain) LensBlur(radius uint32, bladeCount uint32, rotation float32) *Chain {
	return c.add("lens_blur", float32(radius), float32(bladeCount), rotation)
}

// Kuwahara applies the kuwahara operation.
func (c *Chain) Kuwahara(radius uint32) *Chain {
	return c.add("kuwahara", float32(radius))
}

// Sharpen applies the sharpen operation.
func (c *Chain) Sharpen(amount float32) *Chain {
	return c.add("sharpen", amount)
}

// DisplacementMap applies the displacement_map operation.
func (c *Chain) DisplacementMap(mapX float32, mapY float32) *Chain {
	return c.add("displacement_map", mapX, mapY)
}

// ZoomBlur applies the zoom_blur operation.
func (c *Chain) ZoomBlur(centerX float32, centerY float32, factor float32) *Chain {
	return c.add("zoom_blur", centerX, centerY, factor)
}

// Convolve applies the convolve operation.
func (c *Chain) Convolve(kw uint32, kh uint32, divisor float32) *Chain {
	return c.add("convolve", float32(kw), float32(kh), divisor)
}

// SmartSharpen applies the smart_sharpen operation.
func (c *Chain) SmartSharpen(amount float32, radius uint32, threshold float32) *Chain {
	return c.add("smart_sharpen", amount, float32(radius), threshold)
}

// HighPass applies the high_pass operation.
func (c *Chain) HighPass(radius float32) *Chain {
	return c.add("high_pass", radius)
}

// RankFilter applies the rank_filter operation.
func (c *Chain) RankFilter(radius uint32, rank float32) *Chain {
	return c.add("rank_filter", float32(radius), rank)
}

// BoxBlur applies the box_blur operation.
func (c *Chain) BoxBlur(radius uint32) *Chain {
	return c.add("box_blur", float32(radius))
}

// BokehBlur applies the bokeh_blur operation.
func (c *Chain) BokehBlur(radius uint32, shape uint32) *Chain {
	return c.add("bokeh_blur", float32(radius), float32(shape))
}

// AverageBlur applies the average_blur operation.
func (c *Chain) AverageBlur() *Chain {
	return c.add("average_blur")
}

// GaussianBlurCv applies the gaussian_blur_cv operation.
func (c *Chain) GaussianBlurCv(sigma float32) *Chain {
	return c.add("gaussian_blur_cv", sigma)
}

// TiltShift applies the tilt_shift operation.
func (c *Chain) TiltShift(focusPosition float32, bandSize float32, blurRadius float32, angle float32) *Chain {
	return c.add("tilt_shift", focusPosition, bandSize, blurRadius, angle)
}

// MotionBlur applies the motion_blur operation.
func (c *Chain) MotionBlur(length uint32, angleDegrees float32) *Chain {
	return c.add("motion_blur", float32(length), angleDegrees)
}

// Median applies the median operation.
func (c *Chain) Median(radius uint32) *Chain {
	return c.add("median", float32(radius))
}

// Blur applies the blur operation.
func (c *Chain) Blur(radius float32) *Chain {
	return c.add("blur", radius)
}

// Bilateral applies the bilateral operation.
func (c *Chain) Bilateral(diameter uint32, sigmaColor float32, sigmaSpace float32) *Chain {
	return c.add("bilateral", float32(diameter), sigmaColor, sigmaSpace)
}

// SpinBlur applies the spin_blur operation.
func (c *Chain) SpinBlur(centerX float32, centerY float32, angle float32) *Chain {
	return c.add("spin_blur", centerX, centerY, angle)
}

// Unpremultiply applies the unpremultiply operation.
func (c *Chain) Unpremultiply() *Chain {
	return c.add("unpremultiply")
}

// Premultiply applies the premultiply operation.
func (c *Chain) Premultiply() *Chain {
	return c.add("premultiply")
}

// SeamCarveWidth applies the seam_carve_width operation.
func (c *Chain) SeamCarveWidth(targetWidth uint32) *Chain {
	return c.add("seam_carve_width", float32(targetWidth))
}

// SeamCarveHeight applies the seam_carve_height operation.
func (c *Chain) SeamCarveHeight(targetHeight uint32) *Chain {
	return c.add("seam_carve_height", float32(targetHeight))
}

// SmartCrop applies the smart_crop operation.
func (c *Chain) SmartCrop(targetWidth uint32, targetHeight uint32) *Chain {
	return c.add("smart_crop", float32(targetWidth), float32(targetHeight))
}

// DrawPolygon applies the draw_polygon operation.
func (c *Chain) DrawPolygon(fillColor float32, strokeColor float32, strokeWidth float32, filled bool) *Chain {
	return c.add("draw_polygon", fillColor, strokeColor, strokeWidth, boolToFloat(filled))
}

// DrawRect applies the draw_rect operation.
func (c *Chain) DrawRect(x float32, y float32, rectWidth float32, rectHeight float32, color float32, strokeWidth float32, filled bool) *Chain {
	return c.add("draw_rect", x, y, rectWidth, rectHeight, color, strokeWidth, boolToFloat(filled))
}

// DrawLine applies the draw_line operation.
func (c *Chain) DrawLine(x1 float32, y1 float32, x2 float32, y2 float32, color float32, width float32) *Chain {
	return c.add("draw_line", x1, y1, x2, y2, color, width)
}

// DrawEllipse applies the draw_ellipse operation.
func (c *Chain) DrawEllipse(cx float32, cy float32, rx float32, ry float32, color float32, strokeWidth float32, filled bool) *Chain {
	return c.add("draw_ellipse", cx, cy, rx, ry, color, strokeWidth, boolToFloat(filled))
}

// DrawText applies the draw_text operation.
func (c *Chain) DrawText(x uint32, y uint32, scale uint32, color float32) *Chain {
	return c.add("draw_text", float32(x), float32(y), float32(scale), color)
}

// DrawTextTtf applies the draw_text_ttf operation.
func (c *Chain) DrawTextTtf(x uint32, y uint32, fontSizePt float32, colorR uint32, colorG uint32, colorB uint32, colorA uint32) *Chain {
	return c.add("draw_text_ttf", float32(x), float32(y), fontSizePt, float32(colorR), float32(colorG), float32(colorB), float32(colorA))
}

// DrawArc applies the draw_arc operation.
func (c *Chain) DrawArc(cx float32, cy float32, rx float32, ry float32, startAngle float32, endAngle float32, color float32, strokeWidth float32) *Chain {
	return c.add("draw_arc", cx, cy, rx, ry, startAngle, endAngle, color, strokeWidth)
}

// DrawCircle applies the draw_circle operation.
func (c *Chain) DrawCircle(cx float32, cy float32, radius float32, color float32, strokeWidth float32, filled bool) *Chain {
	return c.add("draw_circle", cx, cy, radius, color, strokeWidth, boolToFloat(filled))
}

// FloodFill applies the flood_fill operation.
func (c *Chain) FloodFill(seedX uint32, seedY uint32, newVal uint8, tolerance uint8, connectivity uint32) *Chain {
	return c.add("flood_fill", float32(seedX), float32(seedY), float32(newVal), float32(tolerance), float32(connectivity))
}

// GradientLinear applies the gradient_linear operation.
func (c *Chain) GradientLinear() *Chain {
	return c.add("gradient_linear")
}

// Plasma applies the plasma operation.
func (c *Chain) Plasma() *Chain {
	return c.add("plasma")
}

// GradientRadial applies the gradient_radial operation.
func (c *Chain) GradientRadial() *Chain {
	return c.add("gradient_radial")
}

// SimplexNoise applies the simplex_noise operation.
func (c *Chain) SimplexNoise() *Chain {
	return c.add("simplex_noise")
}

// PerlinNoise applies the perlin_noise operation.
func (c *Chain) PerlinNoise() *Chain {
	return c.add("perlin_noise")
}

// Checkerboard applies the checkerboard operation.
func (c *Chain) Checkerboard() *Chain {
	return c.add("checkerboard")
}

// Grayscale applies the grayscale operation.
func (c *Chain) Grayscale() *Chain {
	return c.add("grayscale")
}

// LabExtractL applies the lab_extract_l operation.
func (c *Chain) LabExtractL() *Chain {
	return c.add("lab_extract_l")
}

// LabExtractA applies the lab_extract_a operation.
func (c *Chain) LabExtractA() *Chain {
	return c.add("lab_extract_a")
}

// LabExtractB applies the lab_extract_b operation.
func (c *Chain) LabExtractB() *Chain {
	return c.add("lab_extract_b")
}

// Charcoal applies the charcoal operation.
func (c *Chain) Charcoal(radius float32, sigma float32) *Chain {
	return c.add("charcoal", radius, sigma)
}

// Canny applies the canny operation.
func (c *Chain) Canny(lowThreshold float32, highThreshold float32) *Chain {
	return c.add("canny", lowThreshold, highThreshold)
}

// Laplacian applies the laplacian operation.
func (c *Chain) Laplacian() *Chain {
	return c.add("laplacian")
}

// Scharr applies the scharr operation.
func (c *Chain) Scharr() *Chain {
	return c.add("scharr")
}

// Sobel applies the sobel operation.
func (c *Chain) Sobel() *Chain {
	return c.add("sobel")
}

// Flatten applies the flatten operation.
func (c *Chain) Flatten(bgR uint8, bgG uint8, bgB uint8) *Chain {
	return c.add("flatten", float32(bgR), float32(bgG), float32(bgB))
}

// AddAlpha applies the add_alpha operation.
func (c *Chain) AddAlpha(alpha uint8) *Chain {
	return c.add("add_alpha", float32(alpha))
}

// RemoveAlpha applies the remove_alpha operation.
func (c *Chain) RemoveAlpha() *Chain {
	return c.add("remove_alpha")
}

