#!/usr/bin/env bash
# Generate reference parity fixtures for FITS, JPEG arithmetic, and HEIC.
#
# Uses LOCAL tools (not Docker) because cjpeg -arithmetic requires libjpeg-turbo.
#
# Required tools:
#   - magick (ImageMagick 7)     — FITS and HEIC conversion
#   - cjpeg / djpeg              — JPEG arithmetic coding (libjpeg-turbo)
#   - fitsverify (optional)      — FITS structural validation
#
# Outputs go to tests/fixtures/generated/reference-parity/ (gitignored).
#
# Usage: ./tests/fixtures/generate-reference.sh [--force]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUT_DIR="$SCRIPT_DIR/generated/reference-parity"
HASH_FILE="$OUT_DIR/.manifest_hash"

CURRENT_HASH=$(shasum -a 256 "$0" | awk '{print $1}')
if [[ "${1:-}" != "--force" ]] && [[ -f "$HASH_FILE" ]]; then
  STORED_HASH=$(cat "$HASH_FILE")
  if [[ "$CURRENT_HASH" == "$STORED_HASH" ]]; then
    echo "Reference parity fixtures up to date. Use --force to regenerate."
    exit 0
  fi
fi

# --- Tool checks -------------------------------------------------------------
HAVE_MAGICK=false
HAVE_CJPEG=false
HAVE_FITSVERIFY=false

command -v magick &>/dev/null && HAVE_MAGICK=true
command -v cjpeg &>/dev/null && HAVE_CJPEG=true
command -v fitsverify &>/dev/null && HAVE_FITSVERIFY=true

if ! $HAVE_MAGICK; then
  echo "ERROR: magick (ImageMagick 7) not found. Install via: brew install imagemagick"
  exit 1
fi

echo "=== Generating reference parity fixtures ==="
echo "  magick:     $HAVE_MAGICK"
echo "  cjpeg:      $HAVE_CJPEG"
echo "  fitsverify: $HAVE_FITSVERIFY"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR/fits" "$OUT_DIR/jpeg-arith" "$OUT_DIR/heic"

# --- Create input bitmaps (PPM — universal exchange format) ------------------
echo "  Creating input PPM bitmaps..."

# 32x32 gradient (RGB, smooth ramp)
magick -size 32x32 'gradient:red-blue' "$OUT_DIR/input_gradient_32.ppm"

# 16x16 solid gray
magick -size 16x16 'xc:#808080' "$OUT_DIR/input_solid_16.ppm"

# 32x32 checkerboard
magick -size 32x32 pattern:checkerboard -normalize "$OUT_DIR/input_checker_32.ppm"

# --- FITS fixtures -----------------------------------------------------------
echo "  Generating FITS fixtures..."

# FITS fixtures are generated by the Rust test itself (our encoder → .fits file).
# ImageMagick then decodes the .fits as the reference.
# This validates: our_encode → magick_decode == our_encode → our_decode.
# The Rust test creates .fits files at runtime, not here.
# We just validate that magick can read FITS:
magick -size 4x4 'xc:gray(128)' -depth 8 "$OUT_DIR/fits/magick_sanity.fits" || true
if [[ -f "$OUT_DIR/fits/magick_sanity.fits" ]]; then
  magick "$OUT_DIR/fits/magick_sanity.fits" -depth 8 "$OUT_DIR/fits/magick_sanity_ref.pgm"
  echo "    FITS magick sanity check OK"
else
  echo "    FITS magick write failed — FITS tests will use self-consistency only"
  touch "$OUT_DIR/fits/.skip"
fi

if $HAVE_FITSVERIFY; then
  echo "  Validating FITS structural integrity..."
  fitsverify "$OUT_DIR/fits/gradient_gray8.fits" || true
  fitsverify "$OUT_DIR/fits/solid_gray8.fits" || true
fi

# --- JPEG Arithmetic fixtures ------------------------------------------------
if $HAVE_CJPEG; then
  echo "  Generating JPEG arithmetic fixtures..."

  # cjpeg needs PPM input
  cjpeg -arithmetic -quality 85 "$OUT_DIR/input_gradient_32.ppm" > "$OUT_DIR/jpeg-arith/gradient_q85_arith.jpg"
  cjpeg -arithmetic -quality 95 "$OUT_DIR/input_gradient_32.ppm" > "$OUT_DIR/jpeg-arith/gradient_q95_arith.jpg"
  cjpeg -arithmetic -quality 85 "$OUT_DIR/input_solid_16.ppm" > "$OUT_DIR/jpeg-arith/solid_q85_arith.jpg"

  # Reference decode: djpeg → PPM
  djpeg -pnm "$OUT_DIR/jpeg-arith/gradient_q85_arith.jpg" > "$OUT_DIR/jpeg-arith/gradient_q85_arith_ref.ppm"
  djpeg -pnm "$OUT_DIR/jpeg-arith/gradient_q95_arith.jpg" > "$OUT_DIR/jpeg-arith/gradient_q95_arith_ref.ppm"
  djpeg -pnm "$OUT_DIR/jpeg-arith/solid_q85_arith.jpg" > "$OUT_DIR/jpeg-arith/solid_q85_arith_ref.ppm"

  # Verify SOF9 marker is present
  if xxd "$OUT_DIR/jpeg-arith/gradient_q85_arith.jpg" | grep -q "ffc9"; then
    echo "    SOF9 marker confirmed in arithmetic JPEG"
  else
    echo "    WARNING: SOF9 marker not found — cjpeg may not support arithmetic"
  fi
else
  echo "  SKIP: cjpeg not available — no JPEG arithmetic fixtures"
fi

# --- HEIC fixtures -----------------------------------------------------------
echo "  Generating HEIC fixtures..."

# Check if ImageMagick has HEIC support
if magick identify -list format 2>/dev/null | grep -q "HEIC.*rw"; then
  magick "$OUT_DIR/input_gradient_32.ppm" -quality 90 "$OUT_DIR/heic/gradient_q90.heic" 2>/dev/null || {
    echo "    HEIC encode failed (missing libheif?). Skipping."
    touch "$OUT_DIR/heic/.skip"
  }

  if [[ -f "$OUT_DIR/heic/gradient_q90.heic" ]]; then
    # Reference decode: HEIC → PPM
    magick "$OUT_DIR/heic/gradient_q90.heic" "$OUT_DIR/heic/gradient_q90_ref.ppm"
    magick "$OUT_DIR/input_solid_16.ppm" -quality 90 "$OUT_DIR/heic/solid_q90.heic"
    magick "$OUT_DIR/heic/solid_q90.heic" "$OUT_DIR/heic/solid_q90_ref.ppm"
  fi
else
  echo "  SKIP: ImageMagick HEIC not available"
  touch "$OUT_DIR/heic/.skip"
fi

# --- Store hash --------------------------------------------------------------
echo "$CURRENT_HASH" > "$HASH_FILE"

echo "=== Done ==="
echo "  FITS:       $(ls "$OUT_DIR/fits/" 2>/dev/null | wc -l | tr -d ' ') files"
echo "  JPEG arith: $(ls "$OUT_DIR/jpeg-arith/" 2>/dev/null | wc -l | tr -d ' ') files"
echo "  HEIC:       $(ls "$OUT_DIR/heic/" 2>/dev/null | wc -l | tr -d ' ') files"
