//! Operation registration — unified build-time registry for all pipeline operations.
//!
//! Filters, codecs, transforms, and color conversions all register through the
//! same `OperationRegistration` struct. The pipeline engine queries the registry
//! without knowing what specific operations exist.
//!
//! Registration happens at build time via the `inventory` crate. External crates
//! submit registrations; the pipeline collects them at link time.

use crate::node::NodeInfo;

// ─── Operation Kind ───────────────────────────────────────────────────────────

/// What kind of operation this is.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OperationKind {
    /// Image filter (blur, sharpen, brightness, etc.)
    Filter,
    /// Image encoder (JPEG, PNG, WebP, etc.)
    Encoder,
    /// Image decoder (JPEG, PNG, EXR, etc.)
    Decoder,
    /// Spatial transform (crop, resize, rotate, flip, etc.)
    Transform,
    /// Color space conversion (sRGB→Linear, Linear→ACEScct, etc.)
    ColorConversion,
}

// ─── Parameter Descriptors ────────────────────────────────────────────────────

/// Typed resource reference in a param map.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TypedRef {
    /// Reference to another graph node.
    Node(u32),
    /// Reference to a registered Font resource.
    Font(u32),
    /// Reference to a registered LUT resource.
    Lut(u32),
}

/// Type of a parameter value.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParamType {
    F32,
    F64,
    U32,
    I32,
    Bool,
    /// String parameter (e.g., file path, mode selector).
    String,
    /// Rectangle (x, y, width, height).
    Rect,
    /// Reference to another graph node.
    NodeRef,
    /// Reference to a registered Font resource.
    FontRef,
    /// Reference to a registered LUT resource.
    LutRef,
}

/// Description of a single parameter on an operation.
///
/// Generated by derive(Operation) from `#[param(...)]` attributes.
/// Exposed to host SDKs via WIT codegen for dynamic UI construction.
#[derive(Debug, Clone)]
pub struct ParamDescriptor {
    /// Parameter name (matches struct field name).
    pub name: &'static str,
    /// Value type.
    pub value_type: ParamType,
    /// Minimum value (for numeric types).
    pub min: Option<f64>,
    /// Maximum value (for numeric types).
    pub max: Option<f64>,
    /// Step size for UI sliders.
    pub step: Option<f64>,
    /// Default value.
    pub default: Option<f64>,
    /// UI hint (e.g., "log_slider", "color_picker", "angle_dial").
    pub hint: Option<&'static str>,
    /// Human-readable description (from field doc comment).
    pub description: &'static str,
    /// Contextual constraints (validated at graph build time).
    pub constraints: &'static [ParamConstraint],
}

// ─── Contextual Validation ────────────────────────────────────────────────────

/// Reference to upstream context for contextual param validation.
///
/// Evaluated at graph build time when upstream NodeInfo is available.
#[derive(Debug, Clone)]
pub enum ContextRef {
    /// Upstream node's output width.
    UpstreamWidth,
    /// Upstream node's output height.
    UpstreamHeight,
    /// A literal numeric value.
    Literal(f64),
}

impl ContextRef {
    /// Resolve this reference against upstream info.
    pub fn resolve(&self, upstream: &NodeInfo) -> f64 {
        match self {
            ContextRef::UpstreamWidth => upstream.width as f64,
            ContextRef::UpstreamHeight => upstream.height as f64,
            ContextRef::Literal(v) => *v,
        }
    }
}

/// Constraint on a parameter value, evaluated at graph build time.
#[derive(Debug, Clone)]
pub enum ParamConstraint {
    /// Static range: value must be in [min, max].
    Range { min: f64, max: f64 },
    /// Contextual max: value must be <= resolved ContextRef.
    MaxContext(ContextRef),
    /// Contextual min: value must be >= resolved ContextRef.
    MinContext(ContextRef),
    /// Rect must fit within upstream dimensions.
    RectWithinUpstream,
}

/// Validation error for parameter constraints.
#[derive(Debug, Clone)]
pub struct ValidationError {
    pub param: String,
    pub message: String,
}

impl std::fmt::Display for ValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "param '{}': {}", self.param, self.message)
    }
}

// ─── Operation Registration ───────────────────────────────────────────────────

/// Capabilities flags for an operation.
#[derive(Debug, Clone, Copy)]
pub struct OperationCapabilities {
    /// Has a GPU compute shader.
    pub gpu: bool,
    /// Can be fused analytically (point op expression tree).
    pub analytic: bool,
    /// Can be fused via affine matrix composition.
    pub affine: bool,
    /// Can be fused via 3D CLUT composition.
    pub clut: bool,
}

/// Static registration metadata for a pipeline operation.
///
/// Collected at build time via `inventory`. The pipeline queries these
/// to discover available operations, their parameters, and capabilities.
pub struct OperationRegistration {
    /// Unique operation name (e.g., "blur", "jpeg_encode", "crop").
    pub name: &'static str,
    /// Human-readable display name.
    pub display_name: &'static str,
    /// Category for grouping (e.g., "spatial", "adjustment", "distortion").
    pub category: &'static str,
    /// What kind of operation.
    pub kind: OperationKind,
    /// Parameter descriptors (schema for UI/validation).
    pub params: &'static [ParamDescriptor],
    /// Operation capabilities (GPU, fusion flags).
    pub capabilities: OperationCapabilities,
    /// Relative path to AsciiDoc documentation file. Empty = no docs.
    pub doc_path: &'static str,
    /// Algorithmic cost relative to pixel count (e.g., "O(n)", "O(n * r)"). Empty = unspecified.
    pub cost: &'static str,
}

inventory::collect!(&'static OperationRegistration);

// ─── Query API ────────────────────────────────────────────────────────────────

/// List all registered operations.
pub fn registered_operations() -> Vec<&'static OperationRegistration> {
    inventory::iter::<&'static OperationRegistration>
        .into_iter()
        .copied()
        .collect()
}

/// Find an operation by name.
pub fn find_operation(name: &str) -> Option<&'static OperationRegistration> {
    inventory::iter::<&'static OperationRegistration>
        .into_iter()
        .copied()
        .find(|r| r.name == name)
}

/// List operations by category.
pub fn operations_by_category(category: &str) -> Vec<&'static OperationRegistration> {
    inventory::iter::<&'static OperationRegistration>
        .into_iter()
        .copied()
        .filter(|r| r.category == category)
        .collect()
}

/// List operations by kind.
pub fn operations_by_kind(kind: OperationKind) -> Vec<&'static OperationRegistration> {
    inventory::iter::<&'static OperationRegistration>
        .into_iter()
        .copied()
        .filter(|r| r.kind == kind)
        .collect()
}

/// Get parameter descriptors for an operation.
pub fn param_descriptors(name: &str) -> Option<&'static [ParamDescriptor]> {
    find_operation(name).map(|r| r.params)
}

// ─── Dynamic Filter Factory ──────────────────────────────────────────────────

use std::collections::HashMap;

/// A map of parameter values for dynamic filter construction.
#[derive(Clone, Default)]
pub struct ParamMap {
    pub floats: HashMap<String, f32>,
    pub ints: HashMap<String, i64>,
    pub bools: HashMap<String, bool>,
    pub strings: HashMap<String, String>,
    /// Typed resource references (node refs, font refs, LUT refs).
    pub refs: HashMap<String, TypedRef>,
    /// Resolved font resources (populated by pipeline before factory call).
    pub resolved_fonts: HashMap<String, std::rc::Rc<crate::font::Font>>,
    /// Resolved LUT resources (populated by pipeline before factory call).
    pub resolved_luts: HashMap<String, crate::lmt::Lmt>,
}

impl ParamMap {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn get_f32(&self, key: &str) -> f32 {
        self.floats.get(key).copied().unwrap_or(0.0)
    }

    pub fn get_u32(&self, key: &str) -> u32 {
        self.ints.get(key).copied().unwrap_or(0) as u32
    }

    pub fn get_i32(&self, key: &str) -> i32 {
        self.ints.get(key).copied().unwrap_or(0) as i32
    }

    pub fn get_u64(&self, key: &str) -> u64 {
        self.ints.get(key).copied().unwrap_or(0) as u64
    }

    pub fn get_bool(&self, key: &str) -> bool {
        self.bools.get(key).copied().unwrap_or(false)
    }

    pub fn get_string(&self, key: &str) -> String {
        self.strings.get(key).cloned().unwrap_or_default()
    }

    pub fn get_ref(&self, key: &str) -> Option<TypedRef> {
        self.refs.get(key).copied()
    }

    pub fn get_node_ref(&self, key: &str) -> Option<u32> {
        match self.refs.get(key) { Some(TypedRef::Node(id)) => Some(*id), _ => None }
    }

    pub fn get_font_ref(&self, key: &str) -> Option<u32> {
        match self.refs.get(key) { Some(TypedRef::Font(id)) => Some(*id), _ => None }
    }

    pub fn get_lut_ref(&self, key: &str) -> Option<u32> {
        match self.refs.get(key) { Some(TypedRef::Lut(id)) => Some(*id), _ => None }
    }

    pub fn get_font(&self, key: &str) -> Option<std::rc::Rc<crate::font::Font>> {
        self.resolved_fonts.get(key).cloned()
    }

    pub fn get_lut(&self, key: &str) -> Option<crate::lmt::Lmt> {
        self.resolved_luts.get(key).cloned()
    }

    /// Deterministic byte serialization for content hashing.
    ///
    /// Keys are sorted alphabetically within each type group to ensure
    /// the same params always produce the same bytes regardless of insertion order.
    pub fn to_hash_bytes(&self) -> Vec<u8> {
        let mut out = Vec::new();
        // Floats (sorted by key)
        let mut fkeys: Vec<_> = self.floats.keys().collect();
        fkeys.sort();
        for k in fkeys {
            out.extend_from_slice(k.as_bytes());
            out.extend_from_slice(&self.floats[k].to_le_bytes());
        }
        // Ints (sorted by key)
        let mut ikeys: Vec<_> = self.ints.keys().collect();
        ikeys.sort();
        for k in ikeys {
            out.extend_from_slice(k.as_bytes());
            out.extend_from_slice(&self.ints[k].to_le_bytes());
        }
        // Bools (sorted by key)
        let mut bkeys: Vec<_> = self.bools.keys().collect();
        bkeys.sort();
        for k in bkeys {
            out.extend_from_slice(k.as_bytes());
            out.push(if self.bools[k] { 1 } else { 0 });
        }
        // Strings (sorted by key)
        let mut skeys: Vec<_> = self.strings.keys().collect();
        skeys.sort();
        for k in skeys {
            out.extend_from_slice(k.as_bytes());
            out.extend_from_slice(self.strings[k].as_bytes());
        }
        // Refs
        let mut rkeys: Vec<_> = self.refs.keys().collect();
        rkeys.sort();
        for k in rkeys {
            out.extend_from_slice(k.as_bytes());
            match &self.refs[k] {
                TypedRef::Node(id) => { out.push(0x03); out.extend_from_slice(&id.to_le_bytes()); }
                TypedRef::Font(id) => { out.push(0x04); out.extend_from_slice(&id.to_le_bytes()); }
                TypedRef::Lut(id) => { out.push(0x05); out.extend_from_slice(&id.to_le_bytes()); }
            }
        }
        out
    }
}

/// Factory function that constructs a filter from dynamic parameters.
///
/// Returns a boxed Node (FilterNode wrapping the concrete filter).
/// The factory is responsible for extracting typed params from the ParamMap.
pub type FilterFactory = fn(
    upstream_id: u32,
    info: NodeInfo,
    params: &ParamMap,
) -> Box<dyn crate::node::Node>;

/// Registration entry for a dynamically-constructible filter.
///
/// Combines factory function with operation metadata. This is the single
/// registration point for V2 filters — no separate OperationRegistration needed.
pub struct FilterFactoryRegistration {
    /// Unique filter name (e.g., "brightness", "gaussian_blur").
    pub name: &'static str,
    /// Human-readable display name. Empty = auto-generate from name.
    pub display_name: &'static str,
    /// Category for grouping. Empty = "uncategorized".
    pub category: &'static str,
    /// Parameter descriptors for SDK/UI generation. Empty = no metadata.
    pub params: &'static [ParamDescriptor],
    /// Relative path to AsciiDoc documentation file. Empty = no docs.
    pub doc_path: &'static str,
    /// Algorithmic cost relative to pixel count (e.g., "O(n)", "O(n * r)"). Empty = unspecified.
    pub cost: &'static str,
    /// Factory function that constructs the filter from dynamic params.
    pub factory: FilterFactory,
}

/// Helper to create a FilterFactoryRegistration with minimal fields.
/// Used by manual registrations that haven't been migrated to #[derive(V2Filter)] yet.
#[macro_export]
macro_rules! filter_factory {
    ($name:expr, $factory:expr) => {
        &$crate::FilterFactoryRegistration {
            name: $name,
            display_name: "",
            category: "",
            params: &[],
            doc_path: "",
            cost: "",
            factory: $factory,
        }
    };
}

inventory::collect!(&'static FilterFactoryRegistration);

/// Construct a filter node by name with dynamic parameters.
///
/// Returns None if no factory is registered for the given name.
pub fn create_filter_node(
    name: &str,
    upstream_id: u32,
    info: NodeInfo,
    params: &ParamMap,
) -> Option<Box<dyn crate::node::Node>> {
    inventory::iter::<&'static FilterFactoryRegistration>
        .into_iter()
        .copied()
        .find(|r| r.name == name)
        .map(|r| (r.factory)(upstream_id, info, params))
}

/// List all registered filter factories (names only).
pub fn registered_filter_factories() -> Vec<&'static str> {
    inventory::iter::<&'static FilterFactoryRegistration>
        .into_iter()
        .copied()
        .map(|r| r.name)
        .collect()
}

/// List all registered filter factory registrations (full metadata).
pub fn registered_filter_registrations() -> Vec<&'static FilterFactoryRegistration> {
    inventory::iter::<&'static FilterFactoryRegistration>
        .into_iter()
        .copied()
        .collect()
}

// ─── Encoder Factory Registration ────────────────────────────────────────────

/// Encode function: takes f32 RGBA pixels + dimensions + params → encoded bytes.
pub type EncoderFactory = fn(
    pixels: &[f32],
    width: u32,
    height: u32,
    params: &ParamMap,
) -> Result<Vec<u8>, crate::node::PipelineError>;

/// Registration entry for a V2 encoder.
///
/// The encoder adapter handles conversion from f32 pipeline format to the
/// codec's native format. The codec implementation itself is independent
/// of the pipeline.
pub struct EncoderFactoryRegistration {
    /// Format name (e.g., "png", "jpeg"). Used for dispatch.
    pub name: &'static str,
    /// Human-readable display name.
    pub display_name: &'static str,
    /// MIME type.
    pub mime: &'static str,
    /// File extensions.
    pub extensions: &'static [&'static str],
    /// Parameter descriptors for SDK/UI.
    pub params: &'static [ParamDescriptor],
    /// Relative path to AsciiDoc documentation file. Empty = no docs.
    pub doc_path: &'static str,
    /// Whether this format expects scene-referred (linear) input.
    /// When true, the pipeline skips auto-OT insertion on write().
    /// Formats like EXR, TIFF-float, HDR are scene-referred.
    /// Formats like PNG, JPEG, WebP are display-referred.
    pub scene_referred: bool,
    /// Encode function.
    pub encode: EncoderFactory,
}

inventory::collect!(&'static EncoderFactoryRegistration);

/// Encode f32 pixels to the specified format via registry lookup.
pub fn encode_via_registry(
    format: &str,
    pixels: &[f32],
    width: u32,
    height: u32,
    params: &ParamMap,
) -> Option<Result<Vec<u8>, crate::node::PipelineError>> {
    inventory::iter::<&'static EncoderFactoryRegistration>
        .into_iter()
        .copied()
        .find(|r| r.name == format || r.extensions.contains(&format))
        .map(|r| (r.encode)(pixels, width, height, params))
}

/// Check if a format is scene-referred (skips OT) by querying the encoder registry.
pub fn is_scene_referred_format(format: &str) -> bool {
    inventory::iter::<&'static EncoderFactoryRegistration>
        .into_iter()
        .copied()
        .find(|r| r.name == format || r.extensions.contains(&format))
        .map(|r| r.scene_referred)
        .unwrap_or(false) // unknown formats default to display-referred
}

/// List all registered encoders.
pub fn registered_encoders() -> Vec<&'static EncoderFactoryRegistration> {
    inventory::iter::<&'static EncoderFactoryRegistration>
        .into_iter()
        .copied()
        .collect()
}

// ─── Decoder Factory Registration ────────────────────────────────────────────

/// Decoded result from a V2 decoder.
pub struct DecodedImageV2 {
    pub pixels: Vec<f32>,
    pub width: u32,
    pub height: u32,
    pub color_space: crate::color_space::ColorSpace,
}

/// Decode function: takes encoded bytes → f32 RGBA pixels.
pub type DecoderFactory = fn(
    data: &[u8],
) -> Result<DecodedImageV2, crate::node::PipelineError>;

/// Detection function: checks if data matches this codec's format.
pub type FormatDetector = fn(data: &[u8]) -> bool;

/// Registration entry for a V2 decoder.
pub struct DecoderFactoryRegistration {
    /// Format name (e.g., "png", "jpeg").
    pub name: &'static str,
    /// Human-readable display name.
    pub display_name: &'static str,
    /// File extensions.
    pub extensions: &'static [&'static str],
    /// Relative path to AsciiDoc documentation file. Empty = no docs.
    pub doc_path: &'static str,
    /// Format detection (magic bytes check).
    pub detect: FormatDetector,
    /// Decode function.
    pub decode: DecoderFactory,
}

inventory::collect!(&'static DecoderFactoryRegistration);

/// Decode bytes by auto-detecting format via registry.
pub fn decode_via_registry(
    data: &[u8],
) -> Option<Result<DecodedImageV2, crate::node::PipelineError>> {
    inventory::iter::<&'static DecoderFactoryRegistration>
        .into_iter()
        .copied()
        .find(|r| (r.detect)(data))
        .map(|r| (r.decode)(data))
}

/// Decode bytes with a format hint.
pub fn decode_with_hint_via_registry(
    data: &[u8],
    hint: &str,
) -> Option<Result<DecodedImageV2, crate::node::PipelineError>> {
    inventory::iter::<&'static DecoderFactoryRegistration>
        .into_iter()
        .copied()
        .find(|r| r.name == hint || r.extensions.contains(&hint))
        .map(|r| (r.decode)(data))
}

/// List all registered decoders.
pub fn registered_decoders() -> Vec<&'static DecoderFactoryRegistration> {
    inventory::iter::<&'static DecoderFactoryRegistration>
        .into_iter()
        .copied()
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    // Register a test operation
    static TEST_BRIGHTNESS_PARAMS: [ParamDescriptor; 1] = [ParamDescriptor {
        name: "offset",
        value_type: ParamType::F32,
        min: Some(-1.0),
        max: Some(1.0),
        step: Some(0.01),
        default: Some(0.0),
        hint: Some("slider"),
        description: "",
        constraints: &[],
    }];

    inventory::submit! {
        &OperationRegistration {
            name: "test_brightness",
            display_name: "Test Brightness",
            category: "adjustment",
            kind: OperationKind::Filter,
            params: &TEST_BRIGHTNESS_PARAMS,
            capabilities: OperationCapabilities {
                gpu: true, analytic: true, affine: false, clut: false,
            },
            doc_path: "",
            cost: "",
        }
    }

    static CONSTRAINT_MAX_W: [ParamConstraint; 1] =
        [ParamConstraint::MaxContext(ContextRef::UpstreamWidth)];
    static CONSTRAINT_MAX_H: [ParamConstraint; 1] =
        [ParamConstraint::MaxContext(ContextRef::UpstreamHeight)];

    static TEST_CROP_PARAMS: [ParamDescriptor; 4] = [
        ParamDescriptor {
            name: "x", value_type: ParamType::U32,
            min: Some(0.0), max: None, step: Some(1.0), default: Some(0.0),
            hint: None, description: "", constraints: &CONSTRAINT_MAX_W,
        },
        ParamDescriptor {
            name: "y", value_type: ParamType::U32,
            min: Some(0.0), max: None, step: Some(1.0), default: Some(0.0),
            hint: None, description: "", constraints: &CONSTRAINT_MAX_H,
        },
        ParamDescriptor {
            name: "width", value_type: ParamType::U32,
            min: Some(1.0), max: None, step: Some(1.0), default: Some(100.0),
            hint: None, description: "", constraints: &CONSTRAINT_MAX_W,
        },
        ParamDescriptor {
            name: "height", value_type: ParamType::U32,
            min: Some(1.0), max: None, step: Some(1.0), default: Some(100.0),
            hint: None, description: "", constraints: &CONSTRAINT_MAX_H,
        },
    ];

    inventory::submit! {
        &OperationRegistration {
            name: "test_crop",
            display_name: "Test Crop",
            category: "transform",
            kind: OperationKind::Transform,
            params: &TEST_CROP_PARAMS,
            capabilities: OperationCapabilities {
                gpu: false, analytic: false, affine: false, clut: false,
            },
            doc_path: "",
            cost: "",
        }
    }

    #[test]
    fn find_registered_operation() {
        let op = find_operation("test_brightness");
        assert!(op.is_some());
        let op = op.unwrap();
        assert_eq!(op.name, "test_brightness");
        assert_eq!(op.category, "adjustment");
        assert_eq!(op.kind, OperationKind::Filter);
        assert!(op.capabilities.gpu);
        assert!(op.capabilities.analytic);
    }

    #[test]
    fn query_by_category() {
        let ops = operations_by_category("adjustment");
        assert!(ops.iter().any(|o| o.name == "test_brightness"));
    }

    #[test]
    fn query_by_kind() {
        let transforms = operations_by_kind(OperationKind::Transform);
        assert!(transforms.iter().any(|o| o.name == "test_crop"));
    }

    #[test]
    fn param_descriptors_match() {
        let params = param_descriptors("test_brightness").unwrap();
        assert_eq!(params.len(), 1);
        assert_eq!(params[0].name, "offset");
        assert_eq!(params[0].value_type, ParamType::F32);
        assert_eq!(params[0].min, Some(-1.0));
        assert_eq!(params[0].max, Some(1.0));
        assert_eq!(params[0].hint, Some("slider"));
    }

    #[test]
    fn contextual_constraint_resolves() {
        let upstream = crate::node::NodeInfo {
            width: 1920,
            height: 1080,
            color_space: crate::color_space::ColorSpace::Linear,
        };

        assert_eq!(ContextRef::UpstreamWidth.resolve(&upstream), 1920.0);
        assert_eq!(ContextRef::UpstreamHeight.resolve(&upstream), 1080.0);
        assert_eq!(ContextRef::Literal(42.0).resolve(&upstream), 42.0);
    }

    #[test]
    fn crop_params_have_contextual_constraints() {
        let params = param_descriptors("test_crop").unwrap();
        let x_param = &params[0];
        assert_eq!(x_param.name, "x");
        assert!(!x_param.constraints.is_empty());
        assert!(matches!(
            x_param.constraints[0],
            ParamConstraint::MaxContext(ContextRef::UpstreamWidth)
        ));
    }

    #[test]
    fn not_found_returns_none() {
        assert!(find_operation("nonexistent").is_none());
        assert!(param_descriptors("nonexistent").is_none());
    }

    #[test]
    fn operations_list_contains_all() {
        let all = registered_operations();
        assert!(all.len() >= 2); // at least our two test registrations
    }

    #[test]
    fn v2_filters_appear_in_registered_operations() {
        let all = registered_operations();
        let filters: Vec<_> = all.iter().filter(|o| o.kind == OperationKind::Filter).collect();
        // V2Filter derive macro should register both FilterFactoryRegistration AND OperationRegistration
        // "brightness" is a V2Filter — it must appear in registered_operations()
        assert!(
            filters.iter().any(|o| o.name == "brightness"),
            "brightness filter not in registered_operations(); got {} filters: {:?}",
            filters.len(),
            filters.iter().map(|o| o.name).collect::<Vec<_>>()
        );
    }

    #[test]
    fn filter_factory_creates_brightness() {
        let factories = registered_filter_factories();
        assert!(factories.contains(&"brightness"), "brightness factory not registered");

        let info = crate::node::NodeInfo { width: 4, height: 4, color_space: crate::color_space::ColorSpace::Linear };
        let mut params = ParamMap::new();
        params.floats.insert("amount".into(), 0.1);

        let node = create_filter_node("brightness", 0, info, &params);
        assert!(node.is_some(), "factory should return a node");
    }

    #[test]
    fn filter_factory_unknown_returns_none() {
        let info = crate::node::NodeInfo { width: 4, height: 4, color_space: crate::color_space::ColorSpace::Linear };
        let params = ParamMap::new();
        assert!(create_filter_node("nonexistent_filter", 0, info, &params).is_none());
    }

    #[test]
    fn all_adjustment_factories_registered() {
        let factories = registered_filter_factories();
        for name in &["brightness", "contrast", "gamma", "exposure", "invert", "levels",
                       "posterize", "dodge", "burn", "solarize"] {
            assert!(factories.contains(name), "{name} factory not registered");
        }
    }
}
