//! Operation registration — unified build-time registry for all pipeline operations.
//!
//! Filters, codecs, transforms, and color conversions all register through the
//! same `OperationRegistration` struct. The pipeline engine queries the registry
//! without knowing what specific operations exist.
//!
//! Registration happens at build time via the `inventory` crate. External crates
//! submit registrations; the pipeline collects them at link time.

use crate::node::NodeInfo;

// ─── Operation Kind ───────────────────────────────────────────────────────────

/// What kind of operation this is.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum OperationKind {
    /// Image filter (blur, sharpen, brightness, etc.)
    Filter,
    /// Image encoder (JPEG, PNG, WebP, etc.)
    Encoder,
    /// Image decoder (JPEG, PNG, EXR, etc.)
    Decoder,
    /// Spatial transform (crop, resize, rotate, flip, etc.)
    Transform,
    /// Color space conversion (sRGB→Linear, Linear→ACEScct, etc.)
    ColorConversion,
}

// ─── Parameter Descriptors ────────────────────────────────────────────────────

/// Type of a parameter value.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParamType {
    F32,
    F64,
    U32,
    I32,
    Bool,
    /// String parameter (e.g., file path, mode selector).
    String,
    /// Rectangle (x, y, width, height).
    Rect,
}

/// Description of a single parameter on an operation.
///
/// Generated by derive(Operation) from `#[param(...)]` attributes.
/// Exposed to host SDKs via WIT codegen for dynamic UI construction.
#[derive(Debug, Clone)]
pub struct ParamDescriptor {
    /// Parameter name (matches struct field name).
    pub name: &'static str,
    /// Value type.
    pub value_type: ParamType,
    /// Minimum value (for numeric types).
    pub min: Option<f64>,
    /// Maximum value (for numeric types).
    pub max: Option<f64>,
    /// Step size for UI sliders.
    pub step: Option<f64>,
    /// Default value.
    pub default: Option<f64>,
    /// UI hint (e.g., "log_slider", "color_picker", "angle_dial").
    pub hint: Option<&'static str>,
    /// Contextual constraints (validated at graph build time).
    pub constraints: &'static [ParamConstraint],
}

// ─── Contextual Validation ────────────────────────────────────────────────────

/// Reference to upstream context for contextual param validation.
///
/// Evaluated at graph build time when upstream NodeInfo is available.
#[derive(Debug, Clone)]
pub enum ContextRef {
    /// Upstream node's output width.
    UpstreamWidth,
    /// Upstream node's output height.
    UpstreamHeight,
    /// A literal numeric value.
    Literal(f64),
}

impl ContextRef {
    /// Resolve this reference against upstream info.
    pub fn resolve(&self, upstream: &NodeInfo) -> f64 {
        match self {
            ContextRef::UpstreamWidth => upstream.width as f64,
            ContextRef::UpstreamHeight => upstream.height as f64,
            ContextRef::Literal(v) => *v,
        }
    }
}

/// Constraint on a parameter value, evaluated at graph build time.
#[derive(Debug, Clone)]
pub enum ParamConstraint {
    /// Static range: value must be in [min, max].
    Range { min: f64, max: f64 },
    /// Contextual max: value must be <= resolved ContextRef.
    MaxContext(ContextRef),
    /// Contextual min: value must be >= resolved ContextRef.
    MinContext(ContextRef),
    /// Rect must fit within upstream dimensions.
    RectWithinUpstream,
}

/// Validation error for parameter constraints.
#[derive(Debug, Clone)]
pub struct ValidationError {
    pub param: String,
    pub message: String,
}

impl std::fmt::Display for ValidationError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "param '{}': {}", self.param, self.message)
    }
}

// ─── Operation Registration ───────────────────────────────────────────────────

/// Capabilities flags for an operation.
#[derive(Debug, Clone, Copy)]
pub struct OperationCapabilities {
    /// Has a GPU compute shader.
    pub gpu: bool,
    /// Can be fused analytically (point op expression tree).
    pub analytic: bool,
    /// Can be fused via affine matrix composition.
    pub affine: bool,
    /// Can be fused via 3D CLUT composition.
    pub clut: bool,
    /// Safe to use in ACES pipelines (linear math, no sRGB assumptions).
    pub aces_safe: bool,
}

/// Static registration metadata for a pipeline operation.
///
/// Collected at build time via `inventory`. The pipeline queries these
/// to discover available operations, their parameters, and capabilities.
pub struct OperationRegistration {
    /// Unique operation name (e.g., "blur", "jpeg_encode", "crop").
    pub name: &'static str,
    /// Human-readable display name.
    pub display_name: &'static str,
    /// Category for grouping (e.g., "spatial", "adjustment", "distortion").
    pub category: &'static str,
    /// What kind of operation.
    pub kind: OperationKind,
    /// Parameter descriptors (schema for UI/validation).
    pub params: &'static [ParamDescriptor],
    /// Operation capabilities (GPU, fusion flags).
    pub capabilities: OperationCapabilities,
}

inventory::collect!(&'static OperationRegistration);

// ─── Query API ────────────────────────────────────────────────────────────────

/// List all registered operations.
pub fn registered_operations() -> Vec<&'static OperationRegistration> {
    inventory::iter::<&'static OperationRegistration>
        .into_iter()
        .copied()
        .collect()
}

/// Find an operation by name.
pub fn find_operation(name: &str) -> Option<&'static OperationRegistration> {
    inventory::iter::<&'static OperationRegistration>
        .into_iter()
        .copied()
        .find(|r| r.name == name)
}

/// List operations by category.
pub fn operations_by_category(category: &str) -> Vec<&'static OperationRegistration> {
    inventory::iter::<&'static OperationRegistration>
        .into_iter()
        .copied()
        .filter(|r| r.category == category)
        .collect()
}

/// List operations by kind.
pub fn operations_by_kind(kind: OperationKind) -> Vec<&'static OperationRegistration> {
    inventory::iter::<&'static OperationRegistration>
        .into_iter()
        .copied()
        .filter(|r| r.kind == kind)
        .collect()
}

/// Get parameter descriptors for an operation.
pub fn param_descriptors(name: &str) -> Option<&'static [ParamDescriptor]> {
    find_operation(name).map(|r| r.params)
}

#[cfg(test)]
mod tests {
    use super::*;

    // Register a test operation
    static TEST_BRIGHTNESS_PARAMS: [ParamDescriptor; 1] = [ParamDescriptor {
        name: "offset",
        value_type: ParamType::F32,
        min: Some(-1.0),
        max: Some(1.0),
        step: Some(0.01),
        default: Some(0.0),
        hint: Some("slider"),
        constraints: &[],
    }];

    inventory::submit! {
        &OperationRegistration {
            name: "test_brightness",
            display_name: "Test Brightness",
            category: "adjustment",
            kind: OperationKind::Filter,
            params: &TEST_BRIGHTNESS_PARAMS,
            capabilities: OperationCapabilities {
                gpu: true,
                analytic: true,
                affine: false,
                clut: false,
                aces_safe: true,
            },
        }
    }

    static CONSTRAINT_MAX_W: [ParamConstraint; 1] =
        [ParamConstraint::MaxContext(ContextRef::UpstreamWidth)];
    static CONSTRAINT_MAX_H: [ParamConstraint; 1] =
        [ParamConstraint::MaxContext(ContextRef::UpstreamHeight)];

    static TEST_CROP_PARAMS: [ParamDescriptor; 4] = [
        ParamDescriptor {
            name: "x",
            value_type: ParamType::U32,
            min: Some(0.0),
            max: None,
            step: Some(1.0),
            default: Some(0.0),
            hint: None,
            constraints: &CONSTRAINT_MAX_W,
        },
        ParamDescriptor {
            name: "y",
            value_type: ParamType::U32,
            min: Some(0.0),
            max: None,
            step: Some(1.0),
            default: Some(0.0),
            hint: None,
            constraints: &CONSTRAINT_MAX_H,
        },
        ParamDescriptor {
            name: "width",
            value_type: ParamType::U32,
            min: Some(1.0),
            max: None,
            step: Some(1.0),
            default: Some(100.0),
            hint: None,
            constraints: &CONSTRAINT_MAX_W,
        },
        ParamDescriptor {
            name: "height",
            value_type: ParamType::U32,
            min: Some(1.0),
            max: None,
            step: Some(1.0),
            default: Some(100.0),
            hint: None,
            constraints: &CONSTRAINT_MAX_H,
        },
    ];

    inventory::submit! {
        &OperationRegistration {
            name: "test_crop",
            display_name: "Test Crop",
            category: "transform",
            kind: OperationKind::Transform,
            params: &TEST_CROP_PARAMS,
            capabilities: OperationCapabilities {
                gpu: false, analytic: false, affine: false, clut: false, aces_safe: true,
            },
        }
    }

    #[test]
    fn find_registered_operation() {
        let op = find_operation("test_brightness");
        assert!(op.is_some());
        let op = op.unwrap();
        assert_eq!(op.name, "test_brightness");
        assert_eq!(op.category, "adjustment");
        assert_eq!(op.kind, OperationKind::Filter);
        assert!(op.capabilities.gpu);
        assert!(op.capabilities.analytic);
    }

    #[test]
    fn query_by_category() {
        let ops = operations_by_category("adjustment");
        assert!(ops.iter().any(|o| o.name == "test_brightness"));
    }

    #[test]
    fn query_by_kind() {
        let transforms = operations_by_kind(OperationKind::Transform);
        assert!(transforms.iter().any(|o| o.name == "test_crop"));
    }

    #[test]
    fn param_descriptors_match() {
        let params = param_descriptors("test_brightness").unwrap();
        assert_eq!(params.len(), 1);
        assert_eq!(params[0].name, "offset");
        assert_eq!(params[0].value_type, ParamType::F32);
        assert_eq!(params[0].min, Some(-1.0));
        assert_eq!(params[0].max, Some(1.0));
        assert_eq!(params[0].hint, Some("slider"));
    }

    #[test]
    fn contextual_constraint_resolves() {
        let upstream = crate::node::NodeInfo {
            width: 1920,
            height: 1080,
            color_space: crate::color_space::ColorSpace::Linear,
        };

        assert_eq!(ContextRef::UpstreamWidth.resolve(&upstream), 1920.0);
        assert_eq!(ContextRef::UpstreamHeight.resolve(&upstream), 1080.0);
        assert_eq!(ContextRef::Literal(42.0).resolve(&upstream), 42.0);
    }

    #[test]
    fn crop_params_have_contextual_constraints() {
        let params = param_descriptors("test_crop").unwrap();
        let x_param = &params[0];
        assert_eq!(x_param.name, "x");
        assert!(!x_param.constraints.is_empty());
        assert!(matches!(
            x_param.constraints[0],
            ParamConstraint::MaxContext(ContextRef::UpstreamWidth)
        ));
    }

    #[test]
    fn not_found_returns_none() {
        assert!(find_operation("nonexistent").is_none());
        assert!(param_descriptors("nonexistent").is_none());
    }

    #[test]
    fn operations_list_contains_all() {
        let all = registered_operations();
        assert!(all.len() >= 2); // at least our two test registrations
    }
}
