//! Golden validation tests — compare reference + pipeline against external tool output.
//!
//! Golden data is generated by `golden/generate.py` (via `uv run python generate.py`).
//! It uses external libraries (OpenCV, numpy, colour-science) as the ground truth.
//!
//! This test:
//! 1. Regenerates golden data if missing (runs uv)
//! 2. Loads golden JSON
//! 3. For each filter: runs reference fn + pipeline filter on the same input
//! 4. Asserts both match the golden output within tolerance
//!
//! Tolerance: 1e-5 for point ops (exact math, just f32 precision)

use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::process::Command;

use rasmcore_pipeline_v2 as v2;
use rasmcore_pipeline_v2::node::{Node, NodeInfo, PipelineError, Upstream};
use rasmcore_pipeline_v2::color_space::ColorSpace;
use rasmcore_pipeline_v2::rect::Rect;
use rasmcore_pipeline_v2::registry::{ParamMap, ParamType};
use rasmcore_reference as refimpl;

use serde::Deserialize;

// ─── Golden data structures ─────────────────────────────────────────────────

#[derive(Deserialize)]
struct GoldenFile {
    meta: GoldenMeta,
    input: Vec<[f64; 4]>,
    filters: HashMap<String, GoldenEntry>,
}

#[derive(Deserialize)]
struct GoldenMeta {
    width: u32,
    height: u32,
}

#[derive(Deserialize)]
struct GoldenEntry {
    filter: String,
    params: HashMap<String, serde_json::Value>,
    tool: String,
    output: Vec<[f64; 4]>,
    #[serde(default)]
    custom_input: Option<Vec<[f64; 4]>>,
}

// ─── Helpers ────────────────────────────────────────────────────────────────

fn golden_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("golden")
}

fn golden_data_path() -> PathBuf {
    golden_dir().join("golden_data").join("pointops.json")
}

fn ensure_golden_data() {
    let path = golden_data_path();
    if path.exists() {
        return;
    }
    eprintln!("Golden data missing, generating via uv...");
    let status = Command::new("uv")
        .args(["run", "python", "generate.py"])
        .current_dir(golden_dir())
        .status()
        .expect("failed to run uv — is it installed?");
    assert!(status.success(), "golden data generation failed");
    assert!(path.exists(), "golden data not created after generation");
}

fn load_golden() -> GoldenFile {
    ensure_golden_data();
    let data = std::fs::read_to_string(golden_data_path()).expect("read golden JSON");
    serde_json::from_str(&data).expect("parse golden JSON")
}

fn pixels_f64_to_f32(pixels: &[[f64; 4]]) -> Vec<f32> {
    pixels.iter().flat_map(|p| [p[0] as f32, p[1] as f32, p[2] as f32, p[3] as f32]).collect()
}

fn max_diff(a: &[f32], b: &[f32]) -> f32 {
    assert_eq!(a.len(), b.len(), "buffer length mismatch");
    a.iter().zip(b.iter()).map(|(x, y)| (x - y).abs()).fold(0.0f32, f32::max)
}

/// Source node for pipeline execution.
struct SourceNode { pixels: Vec<f32>, info: NodeInfo }
impl Node for SourceNode {
    fn info(&self) -> NodeInfo { self.info.clone() }
    fn compute(&self, _r: Rect, _u: &mut dyn Upstream) -> Result<Vec<f32>, PipelineError> {
        Ok(self.pixels.clone())
    }
    fn upstream_ids(&self) -> Vec<u32> { vec![] }
}

fn run_pipeline(input: &[f32], w: u32, h: u32, filter_name: &str, params: &ParamMap) -> Vec<f32> {
    let info = NodeInfo { width: w, height: h, color_space: ColorSpace::Linear };
    let mut graph = v2::Graph::new(0);
    graph.set_color_managed(false);
    let src_id = graph.add_node(Box::new(SourceNode { pixels: input.to_vec(), info: info.clone() }));
    let filter = v2::create_filter_node(filter_name, src_id, info, params)
        .unwrap_or_else(|| panic!("filter '{filter_name}' not in registry"));
    let fid = graph.add_node(filter);
    graph.request_full(fid).unwrap_or_else(|e| panic!("pipeline {filter_name} failed: {e}"))
}

fn golden_params_to_parammap(params: &HashMap<String, serde_json::Value>, filter_name: &str) -> ParamMap {
    let mut map = ParamMap::new();
    let regs = v2::registry::registered_filter_registrations();
    let reg = regs.iter().find(|r| r.name == filter_name);

    for (k, v) in params {
        let param_type = reg.and_then(|r| r.params.iter().find(|p| p.name == k.as_str()))
            .map(|p| p.value_type);

        match param_type {
            Some(ParamType::U32) | Some(ParamType::I32) => {
                map.ints.insert(k.clone(), v.as_f64().unwrap_or(0.0) as i64);
            }
            Some(ParamType::Bool) => {
                map.bools.insert(k.clone(), v.as_bool().unwrap_or(false));
            }
            _ => {
                map.floats.insert(k.clone(), v.as_f64().unwrap_or(0.0) as f32);
            }
        }
    }
    map
}

// ─── Reference function dispatch ────────────────────────────────────────────
// Maps golden filter name → reference function call.

fn run_reference(_filter_key: &str, entry: &GoldenEntry, input: &[f32], w: u32, h: u32) -> Option<Vec<f32>> {
    let p = &entry.params;
    let f = |k: &str| p.get(k).and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;

    Some(match entry.filter.as_str() {
        "brightness" => refimpl::point_ops::brightness(input, w, h, f("amount")),
        "contrast" => refimpl::point_ops::contrast(input, w, h, f("amount")),
        "gamma" => refimpl::point_ops::gamma(input, w, h, f("gamma")),
        "exposure" => refimpl::point_ops::exposure(input, w, h, f("ev")),
        "invert" => refimpl::point_ops::invert(input, w, h),
        "levels" => refimpl::point_ops::levels(input, w, h, f("black"), f("white"), f("gamma")),
        "posterize" => refimpl::point_ops::posterize(input, w, h, f("levels") as u32),
        "solarize" => refimpl::point_ops::solarize(input, w, h, f("threshold")),
        "sepia" => refimpl::color_ops::sepia(input, w, h, f("intensity")),
        "evaluate_add" => refimpl::evaluate_ops::evaluate_add(input, w, h, f("value")),
        "evaluate_multiply" => refimpl::evaluate_ops::evaluate_multiply(input, w, h, f("value")),
        "evaluate_subtract" => refimpl::evaluate_ops::evaluate_subtract(input, w, h, f("value")),
        "evaluate_abs" => refimpl::evaluate_ops::evaluate_abs(input, w, h, f("value")),
        "evaluate_divide" => refimpl::evaluate_ops::evaluate_divide(input, w, h, f("value")),
        "evaluate_pow" => refimpl::evaluate_ops::evaluate_pow(input, w, h, f("exponent")),
        "evaluate_log" => refimpl::evaluate_ops::evaluate_log(input, w, h, f("scale")),
        "evaluate_max" => refimpl::evaluate_ops::evaluate_max(input, w, h, f("threshold")),
        "evaluate_min" => refimpl::evaluate_ops::evaluate_min(input, w, h, f("threshold")),
        _ => return None,
    })
}

// ─── Tests ──────────────────────────────────────────────────────────────────

const TOLERANCE: f32 = 1e-5;

#[test]
fn golden_reference_validation() {
    let golden = load_golden();
    let w = golden.meta.width;
    let h = golden.meta.height;
    let default_input = pixels_f64_to_f32(&golden.input);

    let mut passed = 0;
    let mut failed = 0;
    let mut skipped = 0;

    for (key, entry) in &golden.filters {
        let input = entry.custom_input.as_ref()
            .map(|ci| pixels_f64_to_f32(ci))
            .unwrap_or_else(|| default_input.clone());

        let expected = pixels_f64_to_f32(&entry.output);

        match run_reference(key, entry, &input, w, h) {
            Some(ref_output) => {
                let diff = max_diff(&ref_output, &expected);
                if diff <= TOLERANCE {
                    eprintln!("  ✓ ref  {key}: max_diff={diff:.8} (tool: {})", entry.tool);
                    passed += 1;
                } else {
                    eprintln!("  ✗ ref  {key}: max_diff={diff:.8} > {TOLERANCE} (tool: {})", entry.tool);
                    failed += 1;
                }
            }
            None => {
                eprintln!("  - skip {key}: no reference function mapped");
                skipped += 1;
            }
        }
    }

    eprintln!("\nReference vs golden: {passed} pass, {failed} fail, {skipped} skip");
    assert_eq!(failed, 0, "{failed} reference functions don't match golden data");
}

#[test]
fn golden_pipeline_validation() {
    let golden = load_golden();
    let w = golden.meta.width;
    let h = golden.meta.height;
    let default_input = pixels_f64_to_f32(&golden.input);

    let mut passed = 0;
    let mut failed = 0;
    let mut skipped = 0;

    for (key, entry) in &golden.filters {
        let input = entry.custom_input.as_ref()
            .map(|ci| pixels_f64_to_f32(ci))
            .unwrap_or_else(|| default_input.clone());

        let expected = pixels_f64_to_f32(&entry.output);
        let params = golden_params_to_parammap(&entry.params, &entry.filter);

        // Check if filter exists in registry
        let regs = v2::registry::registered_filter_registrations();
        if !regs.iter().any(|r| r.name == entry.filter) {
            eprintln!("  - skip {key}: filter '{}' not in pipeline registry", entry.filter);
            skipped += 1;
            continue;
        }

        let pipeline_output = run_pipeline(&input, w, h, &entry.filter, &params);
        let diff = max_diff(&pipeline_output, &expected);
        if diff <= TOLERANCE {
            eprintln!("  ✓ pipe {key}: max_diff={diff:.8} (tool: {})", entry.tool);
            passed += 1;
        } else {
            eprintln!("  ✗ pipe {key}: max_diff={diff:.8} > {TOLERANCE} (tool: {})", entry.tool);
            failed += 1;
        }
    }

    eprintln!("\nPipeline vs golden: {passed} pass, {failed} fail, {skipped} skip");
    assert_eq!(failed, 0, "{failed} pipeline filters don't match golden data");
}
