/**
 * rasmcore pipeline builder v2 — visual chain editor.
 *
 * Features:
 * - Auto-discovered operations from ImagePipeline
 * - Complete param metadata for all operations
 * - Drag-to-reorder layers
 * - Edit mode with small preview (downscaled for speed)
 * - Apply button commits to full-res pipeline
 * - 1-second debounce on slider drags
 */

// ─── SDK ────────────────────────────────────────────────────────────────────

let sdk, Pipeline;
try {
  sdk = await import('../sdk/rasmcore-image.js');
  Pipeline = sdk.pipeline.ImagePipeline;
} catch (e) {
  document.getElementById('palette-items').textContent = `SDK failed: ${e.message}`;
  throw e;
}

// ─── Auto-Discover Export Formats ───────────────────────────────────────────

try {
  const writeFormats = sdk.pipeline.supportedWriteFormats();
  const formatSelect = document.getElementById('export-format');
  if (writeFormats && writeFormats.length > 0) {
    formatSelect.innerHTML = '';
    for (const fmt of writeFormats) {
      const opt = document.createElement('option');
      opt.value = fmt; opt.textContent = fmt.toUpperCase();
      formatSelect.appendChild(opt);
    }
  }
} catch (e) {
  console.warn('Could not auto-discover write formats:', e.message);
}

// ─── Operation Metadata (auto-loaded from generated manifest) ───────────────

// Convert manifest snake_case names to Pipeline camelCase method names
function snakeToCamel(s) { return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase()); }

// Convert #rrggbb hex color to [r, g, b] array
function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}

// Expand param values for pipeline dispatch — color hints expand to separate r,g,b args
function expandArgs(params, paramValues) {
  const args = [];
  for (const p of params) {
    if (p.type === 'color') {
      const [r, g, b] = hexToRgb(paramValues[p.name] || '#808080');
      args.push(r, g, b);
    } else {
      args.push(paramValues[p.name]);
    }
  }
  return args;
}

// Load param manifest generated by build.rs from ConfigParams structs.
// Falls back to minimal hardcoded metadata if manifest unavailable.
let PARAM_META = {};
let MANIFEST_CATEGORIES = {}; // manifest filter name → category
let MANIFEST_GROUPS = {};     // manifest filter name → { group, variant, reference }

try {
  const manifest = await fetch('/sdk/param-manifest.json').then(r => r.json());
  for (const filter of manifest.filters) {
    const camelName = snakeToCamel(filter.name);
    MANIFEST_CATEGORIES[camelName] = filter.category;
    MANIFEST_GROUPS[camelName] = {
      group: filter.group || '',
      variant: filter.variant || '',
      reference: filter.reference || '',
    };
    PARAM_META[camelName] = filter.params
      .filter(p => {
        // Include simple numeric types
        const t = p.type;
        if (t === 'f32' || t === 'f64' || t === 'u32' || t === 'u16' || t === 'u8' || t === 'i32' || t === 'bool') return true;
        // Include complex types if they have a recognized rc. hint
        if (p.hint && p.hint.startsWith('rc.')) return true;
        return false;
      })
      .map(p => {
        // Map rc. hints to UI control types
        if (p.hint === 'rc.color_rgb' || p.hint === 'rc.color_rgba') {
          return { name: p.name, type: 'color', hint: p.hint, default: '#808080', label: p.label || p.name };
        }
        if (p.hint === 'rc.angle_deg') {
          return { name: p.name, type: 'number', hint: p.hint, min: 0, max: 360, step: 1, default: 0, label: p.label || p.name };
        }
        if (p.hint === 'rc.percentage') {
          return { name: p.name, type: 'number', hint: p.hint, min: 0, max: 100, step: 1, default: 50, label: p.label || p.name };
        }
        return {
          name: p.name,
          type: 'number',
          hint: p.hint || '',
          min: p.min != null ? parseFloat(p.min) : undefined,
          max: p.max != null ? parseFloat(p.max) : undefined,
          step: p.step != null ? parseFloat(p.step) : undefined,
          default: p.default != null && p.default !== '' ? (isNaN(Number(p.default)) ? p.default : Number(p.default)) : 0,
          label: p.label || p.name,
        };
      });
  }
  console.log(`Loaded param manifest: ${manifest.filters.length} filters`);
} catch (e) {
  console.warn('Could not load param-manifest.json, using fallback:', e.message);
}

// Pipeline-only operations not in the manifest (enum/complex params, no ConfigParams struct)
const PIPELINE_EXTRAS = {
  resize:        { category: 'transform', params: [
    { name: 'width', type: 'number', min: 1, max: 8192, step: 1, default: 256, label: 'Width in pixels' },
    { name: 'height', type: 'number', min: 1, max: 8192, step: 1, default: 256, label: 'Height in pixels' },
    { name: 'filter', type: 'enum', options: ['nearest', 'bilinear', 'bicubic', 'lanczos3'], default: 'lanczos3', label: 'Resize filter' },
  ]},
  crop:          { category: 'transform', params: [
    { name: 'x', type: 'number', min: 0, max: 8192, step: 1, default: 0, label: 'X offset' },
    { name: 'y', type: 'number', min: 0, max: 8192, step: 1, default: 0, label: 'Y offset' },
    { name: 'width', type: 'number', min: 1, max: 8192, step: 1, default: 256, label: 'Crop width' },
    { name: 'height', type: 'number', min: 1, max: 8192, step: 1, default: 256, label: 'Crop height' },
  ]},
  rotate:        { category: 'transform', params: [
    { name: 'angle', type: 'enum', options: ['r90', 'r180', 'r270'], default: 'r90', label: 'Rotation angle' },
  ]},
  flip:          { category: 'transform', params: [
    { name: 'direction', type: 'enum', options: ['horizontal', 'vertical'], default: 'horizontal', label: 'Flip direction' },
  ]},
  grayscale:     { category: 'color', params: [] },
  convertFormat: { category: 'color', params: [
    { name: 'target', type: 'enum', options: ['rgb8', 'rgba8', 'gray8'], default: 'rgb8', label: 'Target pixel format' },
  ]},
};

// Merge extras into PARAM_META (extras don't override manifest entries)
for (const [name, extra] of Object.entries(PIPELINE_EXTRAS)) {
  if (!PARAM_META[name]) {
    PARAM_META[name] = extra.params;
    MANIFEST_CATEGORIES[name] = extra.category;
  }
}

// Category display names (manifest uses lowercase, UI uses title case)
const CATEGORY_LABELS = {
  spatial: 'Filters', adjustment: 'Adjustment', color: 'Color',
  edge: 'Edge', transform: 'Transform', alpha: 'Alpha', other: 'Other',
  enhancement: 'Enhancement', morphology: 'Morphology', threshold: 'Threshold',
  grading: 'Grading', tonemapping: 'Tonemapping', effect: 'Effects',
  distortion: 'Distortion', draw: 'Draw', generator: 'Generator', tool: 'Tool',
  advanced: 'Advanced',
};

// Operations to skip (internal pipeline methods, not useful in chain builder)
const SKIP = new Set(['constructor', 'read', 'nodeInfo', 'composite', 'iccToSrgb', 'autoOrient']);

// Discover operations: only include methods that exist on Pipeline AND have param metadata
const operations = [];
const tempPipe = new Pipeline();
const proto = Object.getPrototypeOf(tempPipe);
const methodNames = Object.getOwnPropertyNames(proto)
  .filter(n => typeof proto[n] === 'function' && !SKIP.has(n) && !n.startsWith('write'));

for (const name of methodNames) {
  if (!PARAM_META[name]) continue;
  const rawCat = MANIFEST_CATEGORIES[name] || 'other';
  const category = CATEGORY_LABELS[rawCat] || rawCat.charAt(0).toUpperCase() + rawCat.slice(1);
  operations.push({ name, category, params: PARAM_META[name] });
}

// ─── Palette ────────────────────────────────────────────────────────────────

const paletteEl = document.getElementById('palette-items');
paletteEl.innerHTML = '';

// Group operations by category
const grouped = {};
for (const op of operations) {
  if (!grouped[op.category]) grouped[op.category] = [];
  grouped[op.category].push(op);
}

// Title-case a group name: "edge_detect" → "Edge Detect"
function groupLabel(g) {
  return g.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

// Display label for an operation: use variant name if in a group, else full name
function opLabel(op) {
  const meta = MANIFEST_GROUPS[op.name];
  if (meta && meta.variant) return meta.variant.replace(/_/g, ' ');
  return op.name;
}

for (const [cat, ops] of Object.entries(grouped)) {
  const h3 = document.createElement('h3');
  h3.textContent = cat;
  h3.style.cssText = 'font-size:0.65rem;text-transform:uppercase;letter-spacing:0.08em;color:#666;margin:0.75rem 0 0.3rem';
  paletteEl.appendChild(h3);

  // Separate into variant groups and standalone operations
  const variantGroups = {};  // group name → [op, ...]
  const standalone = [];
  for (const op of ops) {
    const meta = MANIFEST_GROUPS[op.name];
    if (meta && meta.group) {
      if (!variantGroups[meta.group]) variantGroups[meta.group] = [];
      variantGroups[meta.group].push(op);
    } else {
      standalone.push(op);
    }
  }

  // Render variant groups (collapsible)
  for (const [grp, variants] of Object.entries(variantGroups)) {
    const groupDiv = document.createElement('div');
    groupDiv.className = 'palette-group';

    const header = document.createElement('div');
    header.className = 'palette-group-header';
    header.innerHTML = `<span class="palette-group-arrow">&#9654;</span> ${groupLabel(grp)} <span style="color:#555;font-size:0.65rem">(${variants.length})</span>`;
    header.addEventListener('click', () => {
      const items = groupDiv.querySelector('.palette-group-items');
      const arrow = header.querySelector('.palette-group-arrow');
      const collapsed = items.style.display === 'none';
      items.style.display = collapsed ? 'block' : 'none';
      arrow.innerHTML = collapsed ? '&#9660;' : '&#9654;';
    });
    groupDiv.appendChild(header);

    const itemsDiv = document.createElement('div');
    itemsDiv.className = 'palette-group-items';
    itemsDiv.style.display = 'none'; // collapsed by default

    for (const op of variants) {
      const div = document.createElement('div');
      div.className = 'palette-item palette-variant';
      const meta = MANIFEST_GROUPS[op.name];
      const label = opLabel(op);
      const paramHint = op.params.length > 0 ? ` (${op.params.length})` : '';
      div.innerHTML = `${label}<span style="color:#555;font-size:0.7rem">${paramHint}</span>`;
      if (meta && meta.reference) div.title = meta.reference;
      div.addEventListener('click', () => addNode(op));
      itemsDiv.appendChild(div);
    }

    groupDiv.appendChild(itemsDiv);
    paletteEl.appendChild(groupDiv);
  }

  // Render standalone operations (same as before)
  for (const op of standalone) {
    const div = document.createElement('div');
    div.className = 'palette-item';
    const meta = MANIFEST_GROUPS[op.name];
    const paramHint = op.params.length > 0 ? ` (${op.params.length})` : '';
    div.innerHTML = `${op.name}<span style="color:#555;font-size:0.7rem">${paramHint}</span>`;
    if (meta && meta.reference) div.title = meta.reference;
    div.addEventListener('click', () => addNode(op));
    paletteEl.appendChild(div);
  }
}

// ─── Web Worker ─────────────────────────────────────────────────────────────

const worker = new Worker(new URL('./pipeline-worker.js', import.meta.url), { type: 'module' });
let workerReady = false;
let isProcessing = false;
let queuedRequest = null; // Single-slot queue: latest pending request
let imageInfo = null;     // { width, height } from loaded image

worker.postMessage({ type: 'init' });

function setProcessing(active) {
  isProcessing = active;
  const canvas = document.getElementById('preview-canvas');
  canvas.style.opacity = active ? '0.5' : '1';
  document.getElementById('total-time').textContent = active
    ? (queuedRequest ? 'Processing... (queued)' : 'Processing...')
    : document.getElementById('total-time').textContent;
}

function requestWorker(msg) {
  if (!workerReady) return;
  if (isProcessing) {
    queuedRequest = msg; // Replace any pending — single-slot
    setProcessing(true); // Update "queued" indicator
    return;
  }
  isProcessing = true;
  queuedRequest = null;
  setProcessing(true);
  worker.postMessage(msg, msg.imageBytes ? [msg.imageBytes] : []);
}

function serializeChain() {
  const chain = getChain();
  return chain.map(n => ({
    name: n.op.name,
    params: n.op.params,
    paramValues: { ...n.paramValues },
  }));
}

function serializeLayers() {
  return layers.filter(l => l.visible).map((l, idx) => ({
    id: l.id,
    chain: l.chain.map(n => ({
      name: n.op.name,
      params: n.op.params,
      paramValues: { ...n.paramValues },
    })),
    blendMode: idx === 0 ? null : (l.blendMode === 'over' ? null : l.blendMode),
    x: l.x,
    y: l.y,
  }));
}

function requestCompositeProcess() {
  if (layers.length === 0) return;
  if (layers.length === 1) {
    // Single layer — use simple process
    const copy = layers[0].imageBytes.buffer.slice(0);
    requestWorker({ type: 'load', imageBytes: copy }, [copy]);
    return;
  }
  // Multi-layer — send all layer data to worker
  const layerData = layers.filter(l => l.visible).map(l => ({
    id: l.id,
    imageBytes: l.imageBytes.buffer.slice(0),
    chain: l.chain.map(n => ({
      name: n.op.name,
      params: n.op.params,
      paramValues: { ...n.paramValues },
    })),
    blendMode: l === layers[0] ? null : (l.blendMode === 'over' ? null : l.blendMode),
    x: l.x,
    y: l.y,
  }));
  const transfers = layerData.map(l => l.imageBytes);
  requestWorker({ type: 'composite', layers: layerData }, transfers);
}

worker.onmessage = (e) => {
  const { type } = e.data;

  if (type === 'ready') {
    workerReady = true;
    return;
  }

  if (type === 'loaded') {
    imageInfo = e.data.info;
    compareBtn.style.display = 'inline-block';
    dropHint.style.display = 'block';
    if (imageInfo) {
      previewInfo.textContent = `${imageInfo.width}×${imageInfo.height}`;
    }
    // Trigger initial render
    requestWorker({ type: 'process', chain: serializeChain(), mode: 'full' });
    return;
  }

  if (type === 'result') {
    isProcessing = false;
    const blob = new Blob([e.data.png], { type: 'image/png' });
    const url = URL.createObjectURL(blob);
    const img = new Image();
    img.onload = () => {
      const canvas = e.data.mode === 'thumb'
        ? document.getElementById('thumb-preview')
        : previewCanvas;
      if (canvas) {
        canvas.width = img.width;
        canvas.height = img.height;
        canvas.getContext('2d').drawImage(img, 0, 0);
      }
      URL.revokeObjectURL(url);
    };
    img.src = url;

    // Update timings
    if (e.data.mode === 'full' && e.data.timings) {
      totalTimeEl.textContent = `Total: ${e.data.totalMs}ms (${e.data.timings.length} ops)`;
      totalTimeEl.style.color = '#4ade80';
      for (const t of e.data.timings) {
        for (const cn of chain) {
          if (cn.op.name === t.name) {
            cn.timingMs = t.ms;
            break;
          }
        }
      }
      // Update timing in cards
      for (const cn of chain) {
        const card = chainEl.querySelector(`[data-id="${cn.id}"]`);
        if (card) {
          const tEl = card.querySelector('.node-timing');
          if (tEl) tEl.textContent = `${cn.timingMs}ms`;
        }
      }
    }

    setProcessing(false);

    // Show Before/After button once we have a result to compare
    if (e.data.mode === 'full' && compareBtn) {
      compareBtn.style.display = '';
    }

    // Drain single-slot queue
    if (queuedRequest) {
      const next = queuedRequest;
      queuedRequest = null;
      requestWorker(next);
    }
    return;
  }

  if (type === 'exported') {
    isProcessing = false;
    setProcessing(false);
    const blob = new Blob([e.data.data], { type: e.data.mime });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `rasmcore-pipeline.${e.data.format}`;
    a.click();
    return;
  }

  if (type === 'error') {
    isProcessing = false;
    setProcessing(false);
    totalTimeEl.textContent = `Error: ${e.data.message}`;
    totalTimeEl.style.color = '#f87171';
    // Drain queue even on error
    if (queuedRequest) {
      const next = queuedRequest;
      queuedRequest = null;
      requestWorker(next);
    }
    return;
  }
};

// ─── State ──────────────────────────────────────────────────────────────────

// Layer model: each layer has its own image + filter chain
let layers = []; // [{ id, name, imageBytes, chain: [], blendMode: 'over', x: 0, y: 0, visible: true }]
let activeLayerId = null; // Which layer's chain is being edited
let nextLayerId = 0;
let nextId = 0;
let editingNodeId = null;
let dragSrcIdx = null;
let showingOriginal = false;

// Convenience: get active layer
function activeLayer() { return layers.find(l => l.id === activeLayerId); }
// Convenience: get active layer's chain (for backwards compat)
function getChain() { const l = activeLayer(); return l ? l.chain : []; }

const chainEl = document.getElementById('chain');
const dropHint = document.getElementById('drop-hint');
const previewCanvas = document.getElementById('preview-canvas');
const originalCanvas = document.getElementById('original-canvas');
const previewInfo = document.getElementById('preview-info');
const totalTimeEl = document.getElementById('total-time');
const fileInput = document.getElementById('file-input');
const compareBtn = document.getElementById('compare-btn');
const layersEl = document.getElementById('layers');
const addLayerBtn = document.getElementById('add-layer-btn');
const layerFileInput = document.getElementById('layer-file-input');
const activeLayerLabel = document.getElementById('active-layer-label');

// ─── Image Loading (Layer-Aware) ────────────────────────────────────────────

document.querySelector('.preview').addEventListener('click', () => { if (layers.length === 0) fileInput.click(); });
document.querySelector('.preview').addEventListener('dragover', (e) => e.preventDefault());
document.querySelector('.preview').addEventListener('drop', (e) => {
  e.preventDefault();
  if (e.dataTransfer.files[0]) addLayer(e.dataTransfer.files[0]);
});
fileInput.addEventListener('change', () => { if (fileInput.files[0]) addLayer(fileInput.files[0]); });

// Add layer button
addLayerBtn.addEventListener('click', () => layerFileInput.click());
layerFileInput.addEventListener('change', () => {
  if (layerFileInput.files[0]) addLayer(layerFileInput.files[0]);
  layerFileInput.value = '';
});

async function addLayer(file) {
  const bytes = new Uint8Array(await file.arrayBuffer());
  const layer = {
    id: nextLayerId++,
    name: file.name.replace(/\.[^.]+$/, ''),
    imageBytes: bytes,
    chain: [],
    blendMode: layers.length === 0 ? 'over' : 'over', // base layer has no blend
    x: 0,
    y: 0,
    visible: true,
    thumbUrl: null,
  };

  // Create thumbnail for layer card
  try {
    const blob = new Blob([bytes], { type: file.type || 'image/png' });
    layer.thumbUrl = URL.createObjectURL(blob);
  } catch (_) {}

  layers.push(layer);
  if (layers.length === 1) {
    activeLayerId = layer.id;
    // Render original for before/after
    try {
      const blob = new Blob([bytes], { type: file.type || 'image/png' });
      const url = URL.createObjectURL(blob);
      const img = new Image();
      img.onload = () => {
        originalCanvas.width = img.width;
        originalCanvas.height = img.height;
        originalCanvas.getContext('2d').drawImage(img, 0, 0);
        URL.revokeObjectURL(url);
      };
      img.src = url;
    } catch (_) {}
    compareBtn.style.display = 'inline-block';
  }

  renderLayers();
  renderChain();
  requestCompositeProcess();
}

function removeLayer(id) {
  layers = layers.filter(l => l.id !== id);
  if (activeLayerId === id) activeLayerId = layers.length > 0 ? layers[0].id : null;
  renderLayers();
  renderChain();
  requestCompositeProcess();
}

function setActiveLayer(id) {
  activeLayerId = id;
  editingNodeId = null;
  renderLayers();
  renderChain();
}

// ─── Layer Panel Rendering ─────────────────────────────────────────────────

const BLEND_MODES = ['over', 'multiply', 'screen', 'overlay', 'darken', 'lighten', 'soft-light', 'hard-light', 'difference', 'exclusion'];

function renderLayers() {
  layersEl.innerHTML = '';
  activeLayerLabel.textContent = activeLayer() ? `(${activeLayer().name})` : '';

  layers.forEach((layer, idx) => {
    const card = document.createElement('div');
    card.className = 'layer-card' + (layer.id === activeLayerId ? ' active' : '');
    card.addEventListener('click', () => setActiveLayer(layer.id));

    const header = document.createElement('div');
    header.className = 'layer-header';

    if (layer.thumbUrl) {
      const thumb = document.createElement('img');
      thumb.className = 'layer-thumb';
      thumb.src = layer.thumbUrl;
      header.appendChild(thumb);
    }

    const nameEl = document.createElement('span');
    nameEl.className = 'layer-name';
    nameEl.textContent = `${idx === 0 ? 'BG' : `L${idx}`}: ${layer.name}`;
    header.appendChild(nameEl);

    const visBtn = document.createElement('span');
    visBtn.className = 'layer-vis' + (layer.visible ? '' : ' hidden');
    visBtn.textContent = layer.visible ? '👁' : '👁‍🗨';
    visBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      layer.visible = !layer.visible;
      renderLayers();
      requestCompositeProcess();
    });
    header.appendChild(visBtn);

    if (layers.length > 1) {
      const removeBtn = document.createElement('span');
      removeBtn.className = 'node-remove';
      removeBtn.textContent = '✕';
      removeBtn.addEventListener('click', (e) => { e.stopPropagation(); removeLayer(layer.id); });
      header.appendChild(removeBtn);
    }

    card.appendChild(header);

    // Blend mode + offset controls (not for base layer)
    if (idx > 0) {
      const controls = document.createElement('div');
      controls.className = 'layer-controls';

      const blendSelect = document.createElement('select');
      for (const mode of BLEND_MODES) {
        const opt = document.createElement('option');
        opt.value = mode; opt.textContent = mode;
        if (mode === layer.blendMode) opt.selected = true;
        blendSelect.appendChild(opt);
      }
      blendSelect.addEventListener('change', (e) => {
        e.stopPropagation();
        layer.blendMode = blendSelect.value;
        requestCompositeProcess();
      });
      controls.appendChild(blendSelect);

      const xInput = document.createElement('input');
      xInput.type = 'number'; xInput.value = layer.x; xInput.placeholder = 'X';
      xInput.addEventListener('change', (e) => { e.stopPropagation(); layer.x = parseInt(xInput.value) || 0; requestCompositeProcess(); });
      xInput.addEventListener('click', (e) => e.stopPropagation());
      controls.appendChild(xInput);

      const yInput = document.createElement('input');
      yInput.type = 'number'; yInput.value = layer.y; yInput.placeholder = 'Y';
      yInput.addEventListener('change', (e) => { e.stopPropagation(); layer.y = parseInt(yInput.value) || 0; requestCompositeProcess(); });
      yInput.addEventListener('click', (e) => e.stopPropagation());
      controls.appendChild(yInput);

      card.appendChild(controls);
    }

    layersEl.appendChild(card);
  });
}

// ─── Node Management ────────────────────────────────────────────────────────

function addNode(op) {
  const layer = activeLayer();
  if (!layer) { fileInput.click(); return; }
  const node = {
    id: nextId++,
    op,
    paramValues: Object.fromEntries(op.params.map(p => [p.name, p.default])),
    applied: true,
    timingMs: 0,
  };
  layer.chain.push(node);
  editingNodeId = node.id;
  renderChain();
  previewEditing();
}

function removeNode(id) {
  const layer = activeLayer();
  if (layer) layer.chain = layer.chain.filter(n => n.id !== id);
  if (editingNodeId === id) editingNodeId = null;
  renderChain();
  requestCompositeProcess();
}

function moveNode(fromIdx, toIdx) {
  const chain = getChain();
  if (fromIdx === toIdx || !chain.length) return;
  const [node] = chain.splice(fromIdx, 1);
  chain.splice(toIdx, 0, node);
  renderChain();
  requestCompositeProcess();
}

// ─── Render Chain ───────────────────────────────────────────────────────────

function renderChain() {
  chainEl.innerHTML = '';
  const chain = getChain();

  chain.forEach((node, idx) => {
    const card = document.createElement('div');
    card.className = 'node-card' + (editingNodeId === node.id ? ' editing' : '');
    card.dataset.id = node.id;
    card.dataset.idx = idx;
    card.draggable = true;

    // Drag handlers
    card.addEventListener('dragstart', (e) => {
      dragSrcIdx = idx;
      card.style.opacity = '0.4';
      e.dataTransfer.effectAllowed = 'move';
    });
    card.addEventListener('dragend', () => { card.style.opacity = '1'; dragSrcIdx = null; });
    card.addEventListener('dragover', (e) => {
      e.preventDefault();
      e.dataTransfer.dropEffect = 'move';
      card.style.borderTop = '2px solid #3b82f6';
    });
    card.addEventListener('dragleave', () => { card.style.borderTop = ''; });
    card.addEventListener('drop', (e) => {
      e.preventDefault();
      card.style.borderTop = '';
      if (dragSrcIdx !== null && dragSrcIdx !== idx) {
        moveNode(dragSrcIdx, idx);
      }
    });

    // Header
    const header = document.createElement('div');
    header.className = 'node-header';

    const nameSpan = document.createElement('span');
    nameSpan.className = 'node-name';
    nameSpan.textContent = `${idx + 1}. ${node.op.name}`;

    const actions = document.createElement('span');
    actions.style.cssText = 'display:flex;gap:6px;align-items:center';

    const timingSpan = document.createElement('span');
    timingSpan.className = 'node-timing';
    timingSpan.textContent = node.timingMs > 0 ? `${node.timingMs}ms` : '';

    if (editingNodeId !== node.id && node.op.params.length > 0) {
      const editBtn = document.createElement('span');
      editBtn.textContent = '✎';
      editBtn.style.cssText = 'cursor:pointer;color:#60a5fa;font-size:0.85rem';
      editBtn.title = 'Edit parameters';
      editBtn.addEventListener('click', () => { editingNodeId = node.id; renderChain(); previewEditing(); });
      actions.appendChild(editBtn);
    }

    const removeBtn = document.createElement('span');
    removeBtn.className = 'node-remove';
    removeBtn.textContent = '✕';
    removeBtn.addEventListener('click', () => removeNode(node.id));

    actions.appendChild(timingSpan);
    actions.appendChild(removeBtn);
    header.appendChild(nameSpan);
    header.appendChild(actions);
    card.appendChild(header);

    // Param summary (when not editing)
    if (editingNodeId !== node.id && node.op.params.length > 0) {
      const summary = document.createElement('div');
      summary.style.cssText = 'font-size:0.65rem;color:#666;margin-top:2px';
      summary.textContent = node.op.params.map(p => `${p.name}=${node.paramValues[p.name]}`).join(', ');
      card.appendChild(summary);
    }

    // Edit mode: param controls + preview + apply
    if (editingNodeId === node.id) {
      for (const p of node.op.params) {
        const paramDiv = document.createElement('div');
        paramDiv.className = 'node-param';

        if (p.type === 'color') {
          const label = document.createElement('label');
          label.textContent = p.label || p.name;
          paramDiv.appendChild(label);
          const input = document.createElement('input');
          input.type = 'color';
          input.value = node.paramValues[p.name] || '#808080';
          input.style.cssText = 'width:100%;height:28px;border:none;cursor:pointer';
          input.addEventListener('input', () => {
            node.paramValues[p.name] = input.value;
            schedulePreview();
          });
          paramDiv.appendChild(input);
        } else if (p.type === 'number') {
          const label = document.createElement('label');
          const valSpan = document.createElement('span');
          valSpan.textContent = node.paramValues[p.name];
          label.textContent = (p.label || p.name) + ' ';
          label.appendChild(valSpan);
          paramDiv.appendChild(label);

          const input = document.createElement('input');
          input.type = 'range';
          input.min = p.min; input.max = p.max; input.step = p.step;
          input.value = node.paramValues[p.name];
          input.addEventListener('input', () => {
            node.paramValues[p.name] = parseFloat(input.value);
            valSpan.textContent = input.value;
            schedulePreview(); // debounced small preview
          });
          paramDiv.appendChild(input);
        } else if (p.type === 'enum') {
          const label = document.createElement('label');
          label.textContent = p.label || p.name;
          paramDiv.appendChild(label);
          const select = document.createElement('select');
          for (const opt of p.options) {
            const option = document.createElement('option');
            option.value = opt; option.textContent = opt;
            if (opt === node.paramValues[p.name]) option.selected = true;
            select.appendChild(option);
          }
          select.addEventListener('change', () => {
            node.paramValues[p.name] = select.value;
            schedulePreview();
          });
          paramDiv.appendChild(select);
        }
        card.appendChild(paramDiv);
      }

      // Small preview canvas
      const previewWrap = document.createElement('div');
      previewWrap.style.cssText = 'margin-top:6px;text-align:center';
      const thumbCanvas = document.createElement('canvas');
      thumbCanvas.id = 'thumb-preview';
      thumbCanvas.style.cssText = 'max-width:100%;border:1px solid #333;border-radius:3px';
      previewWrap.appendChild(thumbCanvas);
      card.appendChild(previewWrap);

      // Apply button
      const btnRow = document.createElement('div');
      btnRow.style.cssText = 'margin-top:6px;display:flex;gap:6px';
      const applyBtn = document.createElement('button');
      applyBtn.textContent = 'Apply';
      applyBtn.addEventListener('click', () => {
        editingNodeId = null;
        renderChain();
        applyFullChain();
      });
      const cancelBtn = document.createElement('button');
      cancelBtn.textContent = 'Cancel';
      cancelBtn.className = 'secondary';
      cancelBtn.style.cssText = 'background:#333';
      cancelBtn.addEventListener('click', () => {
        editingNodeId = null;
        renderChain();
      });
      btnRow.appendChild(applyBtn);
      btnRow.appendChild(cancelBtn);
      card.appendChild(btnRow);
    }

    chainEl.appendChild(card);
  });
}

// ─── Preview (small thumbnail, debounced) ───────────────────────────────────

let previewTimer = null;
const PREVIEW_DEBOUNCE_MS = 1000; // Wait 1 second after last slider movement

function schedulePreview() {
  clearTimeout(previewTimer);
  previewTimer = setTimeout(previewEditing, PREVIEW_DEBOUNCE_MS);
}

function previewEditing() {
  const layer = activeLayer();
  if (!layer?.imageBytes || editingNodeId === null) return;
  requestWorker({ type: 'process', chain: serializeChain(), mode: 'thumb' });
}

// ─── Full Processing (on Apply) ─────────────────────────────────────────────

function applyFullChain() {
  const layer = activeLayer();
  if (!layer?.imageBytes) return;
  requestWorker({ type: 'process', chain: serializeChain(), mode: 'full' });
}

// ─── Before/After Comparison ────────────────────────────────────────────────

compareBtn.addEventListener('click', () => {
  showingOriginal = !showingOriginal;
  previewCanvas.style.display = showingOriginal ? 'none' : 'block';
  originalCanvas.style.display = showingOriginal ? 'block' : 'none';
  compareBtn.textContent = showingOriginal ? 'Show Result' : 'Before/After';
  compareBtn.style.background = showingOriginal ? '#8b5cf6' : '#333';
});

// ─── Export ──────────────────────────────────────────────────────────────────

document.getElementById('quality').addEventListener('input', (e) => {
  document.getElementById('quality-val').textContent = e.target.value;
});

document.getElementById('download-btn').addEventListener('click', () => {
  if (layers.length === 0) return;
  const format = document.getElementById('export-format').value;
  const quality = parseInt(document.getElementById('quality').value);
  // For single layer, use export; for multi-layer, export is TODO (use composite result)
  if (layers.length === 1) {
    requestWorker({ type: 'export', chain: serializeChain(), format, quality });
  } else {
    // Multi-layer export — composite then download the result
    // For now, download the preview canvas content
    const canvas = document.getElementById('preview-canvas');
    canvas.toBlob((blob) => {
      const a = document.createElement('a');
      a.href = URL.createObjectURL(blob);
      a.download = `rasmcore-composite.${format === 'jpeg' ? 'jpg' : format}`;
      a.click();
    }, format === 'jpeg' ? 'image/jpeg' : format === 'webp' ? 'image/webp' : 'image/png',
    format === 'png' ? undefined : parseInt(document.getElementById('quality').value) / 100);
  }
});

// ─── Code Generation ────────────────────────────────────────────────────────

function generateCode() {
  const format = document.getElementById('export-format').value;
  const quality = parseInt(document.getElementById('quality').value);

  const lines = [];
  lines.push(`import { rcimage } from '@rasmcore/sdk';`);
  lines.push('');

  const visibleLayers = layers.filter(l => l.visible);
  if (visibleLayers.length <= 1) {
    lines.push('const result = rcimage.load(imageBytes)');
  } else {
    // Multi-layer: generate loadLayer + composite code
    lines.push(`const bg = rcimage.load(layer0Bytes)`);
    for (const node of (visibleLayers[0]?.chain || [])) {
      lines.push(`  .${node.op.name}(${node.op.params.map(p => {
        const val = node.paramValues[p.name];
        return typeof val === 'string' ? `'${val}'` : val;
      }).join(', ')})`);
    }
    lines.push('');
    for (let i = 1; i < visibleLayers.length; i++) {
      const l = visibleLayers[i];
      lines.push(`const layer${i} = bg.loadLayer(layer${i}Bytes)`);
      for (const node of l.chain) {
        lines.push(`  .${node.op.name}(${node.op.params.map(p => {
          const val = node.paramValues[p.name];
          return typeof val === 'string' ? `'${val}'` : val;
        }).join(', ')})`);
      }
      const opts = [];
      if (l.x) opts.push(`x: ${l.x}`);
      if (l.y) opts.push(`y: ${l.y}`);
      if (l.blendMode && l.blendMode !== 'over') opts.push(`blend: '${l.blendMode}'`);
      const optsStr = opts.length ? `{ ${opts.join(', ')} }` : '';
      lines.push(`bg.composite(layer${i}${optsStr ? ', ' + optsStr : ''});`);
      lines.push('');
    }
    lines.push('const result = bg');
  }

  const chain = getChain();
  for (const node of (visibleLayers.length <= 1 ? chain : [])) {
    if (node.op.params.length === 0) {
      lines.push(`  .${node.op.name}()`);
    } else {
      const args = [];
      for (const p of node.op.params) {
        const val = node.paramValues[p.name];
        if (p.type === 'color') {
          const [r, g, b] = hexToRgb(val || '#808080');
          args.push(r, g, b);
        } else if (p.type === 'enum' || typeof val === 'string') {
          args.push(`'${val}'`);
        } else {
          args.push(val);
        }
      }
      lines.push(`  .${node.op.name}(${args.join(', ')})`);
    }
  }

  // Terminal method
  const formatMap = {
    jpeg: { method: 'toJpeg', config: `{ quality: ${quality} }` },
    png:  { method: 'toPng', config: '{}' },
    webp: { method: 'toWebp', config: `{ quality: ${quality} }` },
  };
  const fmt = formatMap[format] || formatMap.jpeg;
  lines.push(`  .${fmt.method}(${fmt.config});`);

  return lines.join('\n');
}

function highlightCode(code) {
  return code
    .replace(/\b(import|from|const)\b/g, '<span class="kw">$1</span>')
    .replace(/'([^']+)'/g, "'<span class=\"str\">$1</span>'")
    .replace(/\b(\d+\.?\d*)\b/g, '<span class="num">$1</span>')
    .replace(/\.(\w+)\(/g, '.<span class="fn">$1</span>(');
}

const codeModal = document.getElementById('code-modal');
const codeOutput = document.getElementById('code-output');

document.getElementById('code-btn').addEventListener('click', () => {
  const code = generateCode();
  codeOutput.innerHTML = highlightCode(code);
  codeModal.classList.add('open');
});

document.getElementById('close-modal-btn').addEventListener('click', () => {
  codeModal.classList.remove('open');
});

codeModal.addEventListener('click', (e) => {
  if (e.target === codeModal) codeModal.classList.remove('open');
});

document.getElementById('copy-code-btn').addEventListener('click', () => {
  const code = generateCode();
  navigator.clipboard.writeText(code).then(() => {
    const btn = document.getElementById('copy-code-btn');
    btn.textContent = 'Copied!';
    setTimeout(() => { btn.textContent = 'Copy to Clipboard'; }, 1500);
  });
});
