//! Filter registration — annotation-driven registration via proc macros + inventory.
//!
//! All filters are registered using `#[register_filter]` attributes on their
//! implementation functions. The `inventory` crate collects registrations at
//! link time across crate boundaries. Build.rs codegen uses these registrations
//! to generate WIT adapters, pipeline nodes, CLI dispatch, and param manifests.
//!
//! # Adding a filter
//!
//! Annotate the implementation function and rebuild:
//!
//! ```ignore
//! #[rasmcore_macros::register_filter(name = "my_blur", category = "spatial")]
//! pub fn my_blur(
//!     request: rasmcore_pipeline::Rect,
//!     upstream: &mut dyn FnMut(rasmcore_pipeline::Rect) -> Result<Vec<u8>, ImageError>,
//!     info: &ImageInfo,
//!     config: &MyBlurParams,
//! ) -> Result<Vec<u8>, ImageError> {
//!     // ... implementation
//! }
//! ```
//!
//! This single annotation generates all adapter code, pipeline nodes, and
//! WIT interface declarations automatically.

// ─── JSON Param Descriptor (for ConfigParams derive + manifest) ────────────

/// Parameter descriptor for JSON manifest generation.
/// Generated by `#[derive(ConfigParams)]` from struct fields + `#[param]` attributes.
#[derive(Debug, Clone)]
pub struct ParamDescriptorJson {
    pub name: String,
    pub param_type: String,
    pub min: String,
    pub max: String,
    pub step: String,
    pub default_val: String,
    pub label: String,
    pub hint: String,
}

// ─── Static Registration (for proc macro + inventory) ─────────────────────

/// Static filter registration metadata — generated by `#[register_filter]` proc macro.
///
/// Collected across crate boundaries via `inventory`. The adapter layer iterates
/// all registrations to build dispatch tables automatically.
#[derive(Debug)]
pub struct StaticFilterRegistration {
    /// Filter name as exposed in WIT/SDK (e.g., "blur")
    pub name: &'static str,
    /// Category for grouping (e.g., "spatial", "color")
    pub category: &'static str,
    /// UI group — related variants share a group (e.g., "blur" for blur/bokeh_blur/motion_blur)
    pub group: &'static str,
    /// Variant name within the group (e.g., "bokeh", "motion"). Empty for default/standalone.
    pub variant: &'static str,
    /// Provenance — algorithm, paper, or physical model (e.g., "Reinhard 2002")
    pub reference: &'static str,
    /// Number of parameters (beyond pixels + info)
    pub param_count: usize,
    /// Function name in source code
    pub fn_name: &'static str,
    /// Module path for dispatch
    pub module_path: &'static str,
}

inventory::collect!(&'static StaticFilterRegistration);

/// Iterate all registered filters (from all crates linked into the binary).
pub fn registered_filters() -> Vec<&'static StaticFilterRegistration> {
    inventory::iter::<&'static StaticFilterRegistration>
        .into_iter()
        .copied()
        .collect()
}

// ─── Generator Registration ───────────────────────────────────────────────

/// Static generator registration — procedural image sources (no pixel input).
#[derive(Debug)]
pub struct StaticGeneratorRegistration {
    pub name: &'static str,
    pub category: &'static str,
    pub group: &'static str,
    pub variant: &'static str,
    pub reference: &'static str,
    pub param_count: usize,
    pub fn_name: &'static str,
    pub module_path: &'static str,
}

inventory::collect!(&'static StaticGeneratorRegistration);

pub fn registered_generators() -> Vec<&'static StaticGeneratorRegistration> {
    inventory::iter::<&'static StaticGeneratorRegistration>
        .into_iter()
        .copied()
        .collect()
}

// ─── Compositor Registration ──────────────────────────────────────────────

/// Static compositor registration — multi-input blending/composition.
#[derive(Debug)]
pub struct StaticCompositorRegistration {
    pub name: &'static str,
    pub category: &'static str,
    pub group: &'static str,
    pub variant: &'static str,
    pub reference: &'static str,
    pub param_count: usize,
    pub fn_name: &'static str,
    pub module_path: &'static str,
}

inventory::collect!(&'static StaticCompositorRegistration);

pub fn registered_compositors() -> Vec<&'static StaticCompositorRegistration> {
    inventory::iter::<&'static StaticCompositorRegistration>
        .into_iter()
        .copied()
        .collect()
}

// ─── Mapper Registration ──────────────────────────────────────────────────

/// Static mapper registration — format-changing operations.
#[derive(Debug)]
pub struct StaticMapperRegistration {
    pub name: &'static str,
    pub category: &'static str,
    pub group: &'static str,
    pub variant: &'static str,
    pub reference: &'static str,
    pub param_count: usize,
    pub fn_name: &'static str,
    pub module_path: &'static str,
}

inventory::collect!(&'static StaticMapperRegistration);

pub fn registered_mappers() -> Vec<&'static StaticMapperRegistration> {
    inventory::iter::<&'static StaticMapperRegistration>
        .into_iter()
        .copied()
        .collect()
}

// ─── Transform Registration ──────────────────────────────────────────────

/// Static transform registration — dimension-changing operations (crop, resize, rotate, etc.).
///
/// Unlike filters (which preserve dimensions), transforms alter output dimensions
/// and require custom `ImageNode::info()` implementations. Registered via
/// `#[register_transform]` on `impl ImageNode` blocks.
#[derive(Debug)]
pub struct StaticTransformRegistration {
    pub name: &'static str,
    /// Node struct name (e.g., "CropNode")
    pub node_type: &'static str,
    /// Module path for dispatch
    pub module_path: &'static str,
}

inventory::collect!(&'static StaticTransformRegistration);

pub fn registered_transforms() -> Vec<&'static StaticTransformRegistration> {
    inventory::iter::<&'static StaticTransformRegistration>
        .into_iter()
        .copied()
        .collect()
}

// ─── Metric Registration ─────────────────────────────────────────────────

/// Static metric registration — compare operations (psnr, ssim, etc.).
///
/// All metrics have uniform signature: `(a, info_a, b, info_b) -> Result<f64>`.
/// Registered via `#[register_metric]` on metric functions.
#[derive(Debug)]
pub struct StaticMetricRegistration {
    pub name: &'static str,
    pub fn_name: &'static str,
    pub module_path: &'static str,
}

inventory::collect!(&'static StaticMetricRegistration);

pub fn registered_metrics() -> Vec<&'static StaticMetricRegistration> {
    inventory::iter::<&'static StaticMetricRegistration>
        .into_iter()
        .copied()
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn static_registration_via_proc_macro() {
        // The #[register_filter] attribute on blur() in filters.rs should
        // register it via inventory. Verify it's discoverable.
        let regs = registered_filters();
        let blur_reg = regs.iter().find(|r| r.name == "blur");
        assert!(
            blur_reg.is_some(),
            "blur should be registered via #[register_filter]. Found: {:?}",
            regs.iter().map(|r| r.name).collect::<Vec<_>>()
        );
        let blur = blur_reg.unwrap();
        assert_eq!(blur.category, "spatial");
        assert_eq!(blur.fn_name, "blur");
    }

    #[test]
    fn transform_registration_via_proc_macro() {
        let regs = registered_transforms();
        let names: Vec<&str> = regs.iter().map(|r| r.name).collect();
        for expected in [
            "resize",
            "crop",
            "rotate",
            "flip",
            "auto_orient",
            "icc_to_srgb",
            "composite",
        ] {
            assert!(
                names.contains(&expected),
                "missing transform registration: {expected}. Found: {names:?}"
            );
        }
    }

    #[test]
    fn config_params_derive_generates_descriptors() {
        let descriptors = crate::domain::filters::BlurParams::param_descriptors();
        assert_eq!(descriptors.len(), 1);
        assert_eq!(descriptors[0].name, "radius");
        assert_eq!(descriptors[0].param_type, "f32");
        assert_eq!(descriptors[0].min, "0.0");
        assert_eq!(descriptors[0].max, "100.0");
        assert_eq!(descriptors[0].step, "0.5");
        assert_eq!(descriptors[0].default_val, "3.0");
        assert_eq!(descriptors[0].label, "Blur radius in pixels");
    }

    #[test]
    fn config_params_derive_generates_default() {
        let params = crate::domain::filters::BlurParams::default();
        assert!((params.radius - 3.0).abs() < 0.001);
    }
}
